LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ifeq ($(TARGET_ARCH),arm)
LOCAL_CFLAGS += -DANDROID_ARM
LOCAL_ARM_MODE := arm
endif

ifeq ($(TARGET_ARCH),x86)
LOCAL_CFLAGS +=  -DANDROID_X86
endif

ifeq ($(TARGET_ARCH),mips)
LOCAL_CFLAGS += -DANDROID_MIPS
endif

LOCAL_MODULE    := libretro

MAME_DIR= ../../../

SOURCES := $(MAME_DIR)/src/version.c $(MAME_DIR)/src/mame.c $(MAME_DIR)/src/common.c $(MAME_DIR)/src/drawgfx.c \
$(MAME_DIR)/src/usrintrf.c \
$(MAME_DIR)/src/ui_text.c \
$(MAME_DIR)/src/cpuintrf.c \
$(MAME_DIR)/src/cpuexec.c \
$(MAME_DIR)/src/cpuint.c \
$(MAME_DIR)/src/mame-memory.c \
$(MAME_DIR)/src/timer.c \
$(MAME_DIR)/src/palette.c \
$(MAME_DIR)/src/input.c \
$(MAME_DIR)/src/inptport.c \
$(MAME_DIR)/src/config.c \
$(MAME_DIR)/src/unzip.c \
$(MAME_DIR)/src/audit.c \
$(MAME_DIR)/src/info.c \
$(MAME_DIR)/src/png.c \
$(MAME_DIR)/src/artwork.c \
$(MAME_DIR)/src/tilemap.c \
$(MAME_DIR)/src/fileio.c \
$(MAME_DIR)/src/state.c \
$(MAME_DIR)/src/datafile.c \
$(MAME_DIR)/src/hiscore.c \
$(MAME_DIR)/src/cpu/adsp2100/adsp2100.c \
$(MAME_DIR)/src/cpu/arm/arm.c \
$(MAME_DIR)/src/cpu/asap/asap.c \
$(MAME_DIR)/src/cpu/ccpu/ccpu.c \
$(MAME_DIR)/src/cpu/dsp32/dsp32.c \
$(MAME_DIR)/src/cpu/e132xs/e132xs.c \
$(MAME_DIR)/src/cpu/g65816/g65816.c \
$(MAME_DIR)/src/cpu/g65816/g65816o0.c \
$(MAME_DIR)/src/cpu/g65816/g65816o1.c \
$(MAME_DIR)/src/cpu/g65816/g65816o2.c \
$(MAME_DIR)/src/cpu/g65816/g65816o3.c \
$(MAME_DIR)/src/cpu/g65816/g65816o4.c \
$(MAME_DIR)/src/cpu/h6280/h6280.c \
$(MAME_DIR)/src/cpu/hd6309/hd6309.c \
$(MAME_DIR)/src/cpu/i8039/i8039.c \
$(MAME_DIR)/src/cpu/i8085/i8085.c \
$(MAME_DIR)/src/cpu/i86/i86.c \
$(MAME_DIR)/src/cpu/i8x41/i8x41.c \
$(MAME_DIR)/src/cpu/jaguar/jaguar.c \
$(MAME_DIR)/src/cpu/konami/konami.c \
$(MAME_DIR)/src/cpu/m6502/m6502.c \
$(MAME_DIR)/src/cpu/m6800/m6800.c \
$(MAME_DIR)/src/cpu/m68000/m68kmame.c \
$(MAME_DIR)/src/cpu/m6805/m6805.c \
$(MAME_DIR)/src/cpu/m6809/m6809.c \
$(MAME_DIR)/src/cpu/mips/mips3.c \
$(MAME_DIR)/src/cpu/mips/psx.c \
$(MAME_DIR)/src/cpu/mips/r3000.c \
$(MAME_DIR)/src/cpu/nec/nec.c \
$(MAME_DIR)/src/cpu/pic16c5x/pic16c5x.c \
$(MAME_DIR)/src/cpu/s2650/s2650.c \
$(MAME_DIR)/src/cpu/sh2/sh2.c \
$(MAME_DIR)/src/cpu/spc700/spc700.c \
$(MAME_DIR)/src/cpu/t11/t11.c \
$(MAME_DIR)/src/cpu/tms32010/tms32010.c \
$(MAME_DIR)/src/cpu/tms32025/tms32025.c \
$(MAME_DIR)/src/cpu/tms32031/tms32031.c \
$(MAME_DIR)/src/cpu/tms34010/34010fld.c \
$(MAME_DIR)/src/cpu/tms34010/tms34010.c \
$(MAME_DIR)/src/cpu/tms9900/tms9980a.c \
$(MAME_DIR)/src/cpu/tms9900/tms9995.c \
$(MAME_DIR)/src/cpu/upd7810/upd7810.c \
$(MAME_DIR)/src/cpu/v60/v60.c \
$(MAME_DIR)/src/cpu/z180/z180.c \
$(MAME_DIR)/src/cpu/z80/z80.c \
$(MAME_DIR)/src/cpu/z8000/z8000.c \
$(MAME_DIR)/src/vidhrdw/cinemat.c \
$(MAME_DIR)/src/sndintrf.c \
$(MAME_DIR)/src/sound/streams.c \
$(MAME_DIR)/src/sound/mixer.c \
$(MAME_DIR)/src/sound/filter.c \
$(MAME_DIR)/src/sound/2151intf.c \
$(MAME_DIR)/src/sound/2203intf.c \
$(MAME_DIR)/src/sound/2413intf.c \
$(MAME_DIR)/src/sound/2608intf.c \
$(MAME_DIR)/src/sound/2610intf.c \
$(MAME_DIR)/src/sound/2612intf.c \
$(MAME_DIR)/src/sound/262intf.c \
$(MAME_DIR)/src/sound/3812intf.c \
$(MAME_DIR)/src/sound/5110intf.c \
$(MAME_DIR)/src/sound/5220intf.c \
$(MAME_DIR)/src/sound/adpcm.c \
$(MAME_DIR)/src/sound/astrocde.c \
$(MAME_DIR)/src/sound/ay8910.c \
$(MAME_DIR)/src/sound/bsmt2000.c \
$(MAME_DIR)/src/sound/c140.c \
$(MAME_DIR)/src/sound/c6280.c \
$(MAME_DIR)/src/sound/cem3394.c \
$(MAME_DIR)/src/sound/dac.c \
$(MAME_DIR)/src/sound/discrete.c \
$(MAME_DIR)/src/sound/es5506.c \
$(MAME_DIR)/src/sound/fm.c \
$(MAME_DIR)/src/sound/fmopl.c \
$(MAME_DIR)/src/sound/gaelco.c \
$(MAME_DIR)/src/sound/hc55516.c \
$(MAME_DIR)/src/sound/iremga20.c \
$(MAME_DIR)/src/sound/k005289.c \
$(MAME_DIR)/src/sound/k007232.c \
$(MAME_DIR)/src/sound/k051649.c \
$(MAME_DIR)/src/sound/k053260.c \
$(MAME_DIR)/src/sound/k054539.c \
$(MAME_DIR)/src/sound/msm5205.c \
$(MAME_DIR)/src/sound/msm5232.c \
$(MAME_DIR)/src/sound/multipcm.c \
$(MAME_DIR)/src/sound/namco.c \
$(MAME_DIR)/src/sound/namcona.c \
$(MAME_DIR)/src/sound/nes_apu.c \
$(MAME_DIR)/src/sound/pokey.c \
$(MAME_DIR)/src/sound/psx.c \
$(MAME_DIR)/src/sound/qsound.c \
$(MAME_DIR)/src/sound/rf5c68.c \
$(MAME_DIR)/src/sound/saa1099.c \
$(MAME_DIR)/src/sound/samples.c \
$(MAME_DIR)/src/sound/scsp.c \
$(MAME_DIR)/src/sound/segapcm.c \
$(MAME_DIR)/src/sound/sn76477.c \
$(MAME_DIR)/src/sound/sn76496.c \
$(MAME_DIR)/src/sound/sp0250.c \
$(MAME_DIR)/src/sound/tiaintf.c \
$(MAME_DIR)/src/sound/tiasound.c \
$(MAME_DIR)/src/sound/tms36xx.c \
$(MAME_DIR)/src/sound/tms5110.c \
$(MAME_DIR)/src/sound/tms5220.c \
$(MAME_DIR)/src/sound/upd7759.c \
$(MAME_DIR)/src/sound/vlm5030.c \
$(MAME_DIR)/src/sound/x1_010.c \
$(MAME_DIR)/src/sound/ym2151.c \
$(MAME_DIR)/src/sound/ym2413.c \
$(MAME_DIR)/src/sound/ymdeltat.c \
$(MAME_DIR)/src/sound/ymf262.c \
$(MAME_DIR)/src/sound/ymf271.c \
$(MAME_DIR)/src/sound/ymf278b.c \
$(MAME_DIR)/src/sound/ymz280b.c \
$(MAME_DIR)/src/sound/votrax.c \
$(MAME_DIR)/src/machine/tmp68301.c \
$(MAME_DIR)/src/machine/6532riot.c \
$(MAME_DIR)/src/machine/z80fmly.c \
$(MAME_DIR)/src/machine/6821pia.c \
$(MAME_DIR)/src/machine/8255ppi.c \
$(MAME_DIR)/src/machine/7474.c \
$(MAME_DIR)/src/machine/74123.c \
$(MAME_DIR)/src/machine/74153.c \
$(MAME_DIR)/src/machine/74148.c \
$(MAME_DIR)/src/vidhrdw/generic.c \
$(MAME_DIR)/src/vidhrdw/vector.c \
$(MAME_DIR)/src/vidhrdw/avgdvg.c \
$(MAME_DIR)/src/machine/mathbox.c \
$(MAME_DIR)/src/vidhrdw/poly.c \
$(MAME_DIR)/src/vidhrdw/matrix3d.c \
$(MAME_DIR)/src/vidhrdw/tlc34076.c \
$(MAME_DIR)/src/machine/ticket.c \
$(MAME_DIR)/src/machine/eeprom.c \
$(MAME_DIR)/src/machine/6522via.c \
$(MAME_DIR)/src/machine/mb87078.c \
$(MAME_DIR)/src/machine/random.c \
$(MAME_DIR)/src/mamedbg.c \
$(MAME_DIR)/src/window.c \
$(MAME_DIR)/src/profiler.c \
$(MAME_DIR)/src/hash.c \
$(MAME_DIR)/src/sha1.c \
$(MAME_DIR)/src/chd.c \
$(MAME_DIR)/src/harddisk.c \
$(MAME_DIR)/src/md5.c \
$(MAME_DIR)/src/machine/idectrl.c \
$(MAME_DIR)/src/sound/wavwrite.c \
$(MAME_DIR)/src/x86drc.c \
$(MAME_DIR)/src/drivers/pacman.c \
$(MAME_DIR)/src/machine/mspacman.c \
$(MAME_DIR)/src/machine/pacplus.c \
$(MAME_DIR)/src/machine/jumpshot.c \
$(MAME_DIR)/src/machine/theglobp.c \
$(MAME_DIR)/src/machine/acitya.c \
$(MAME_DIR)/src/drivers/jrpacman.c \
$(MAME_DIR)/src/vidhrdw/jrpacman.c \
$(MAME_DIR)/src/vidhrdw/pengo.c \
$(MAME_DIR)/src/drivers/pengo.c \
$(MAME_DIR)/src/drivers/epos.c \
$(MAME_DIR)/src/vidhrdw/epos.c \
$(MAME_DIR)/src/vidhrdw/cclimber.c \
$(MAME_DIR)/src/sndhrdw/cclimber.c \
$(MAME_DIR)/src/drivers/cclimber.c \
$(MAME_DIR)/src/drivers/yamato.c \
$(MAME_DIR)/src/vidhrdw/gomoku.c \
$(MAME_DIR)/src/sndhrdw/gomoku.c \
$(MAME_DIR)/src/drivers/gomoku.c \
$(MAME_DIR)/src/vidhrdw/wiping.c \
$(MAME_DIR)/src/sndhrdw/wiping.c \
$(MAME_DIR)/src/drivers/wiping.c \
$(MAME_DIR)/src/vidhrdw/seicross.c \
$(MAME_DIR)/src/drivers/seicross.c \
$(MAME_DIR)/src/vidhrdw/clshroad.c \
$(MAME_DIR)/src/drivers/clshroad.c \
$(MAME_DIR)/src/vidhrdw/tubep.c \
$(MAME_DIR)/src/drivers/tubep.c \
$(MAME_DIR)/src/vidhrdw/magmax.c \
$(MAME_DIR)/src/drivers/magmax.c \
$(MAME_DIR)/src/vidhrdw/cop01.c \
$(MAME_DIR)/src/drivers/cop01.c \
$(MAME_DIR)/src/vidhrdw/terracre.c \
$(MAME_DIR)/src/drivers/terracre.c \
$(MAME_DIR)/src/vidhrdw/galivan.c \
$(MAME_DIR)/src/drivers/galivan.c \
$(MAME_DIR)/src/vidhrdw/armedf.c \
$(MAME_DIR)/src/drivers/armedf.c \
$(MAME_DIR)/src/machine/nb1413m3.c \
$(MAME_DIR)/src/vidhrdw/hyhoo.c \
$(MAME_DIR)/src/drivers/hyhoo.c \
$(MAME_DIR)/src/vidhrdw/pastelgl.c \
$(MAME_DIR)/src/drivers/pastelgl.c \
$(MAME_DIR)/src/vidhrdw/nbmj8688.c \
$(MAME_DIR)/src/drivers/nbmj8688.c \
$(MAME_DIR)/src/vidhrdw/nbmj8891.c \
$(MAME_DIR)/src/drivers/nbmj8891.c \
$(MAME_DIR)/src/vidhrdw/nbmj8991.c \
$(MAME_DIR)/src/drivers/nbmj8991.c \
$(MAME_DIR)/src/vidhrdw/nbmj9195.c \
$(MAME_DIR)/src/drivers/nbmj9195.c \
$(MAME_DIR)/src/vidhrdw/niyanpai.c \
$(MAME_DIR)/src/drivers/niyanpai.c \
$(MAME_DIR)/src/machine/m68kfmly.c \
$(MAME_DIR)/src/drivers/safarir.c \
$(MAME_DIR)/src/vidhrdw/phoenix.c \
$(MAME_DIR)/src/sndhrdw/phoenix.c \
$(MAME_DIR)/src/drivers/phoenix.c \
$(MAME_DIR)/src/sndhrdw/pleiads.c \
$(MAME_DIR)/src/vidhrdw/naughtyb.c \
$(MAME_DIR)/src/drivers/naughtyb.c \
$(MAME_DIR)/src/machine/geebee.c \
$(MAME_DIR)/src/vidhrdw/geebee.c \
$(MAME_DIR)/src/sndhrdw/geebee.c \
$(MAME_DIR)/src/drivers/geebee.c \
$(MAME_DIR)/src/vidhrdw/warpwarp.c \
$(MAME_DIR)/src/sndhrdw/warpwarp.c \
$(MAME_DIR)/src/drivers/warpwarp.c \
$(MAME_DIR)/src/vidhrdw/tankbatt.c \
$(MAME_DIR)/src/drivers/tankbatt.c \
$(MAME_DIR)/src/vidhrdw/galaxian.c \
$(MAME_DIR)/src/sndhrdw/galaxian.c \
$(MAME_DIR)/src/drivers/galaxian.c \
$(MAME_DIR)/src/vidhrdw/rallyx.c \
$(MAME_DIR)/src/drivers/rallyx.c \
$(MAME_DIR)/src/drivers/locomotn.c \
$(MAME_DIR)/src/machine/bosco.c \
$(MAME_DIR)/src/sndhrdw/bosco.c \
$(MAME_DIR)/src/vidhrdw/bosco.c \
$(MAME_DIR)/src/drivers/bosco.c \
$(MAME_DIR)/src/machine/galaga.c \
$(MAME_DIR)/src/vidhrdw/galaga.c \
$(MAME_DIR)/src/drivers/galaga.c \
$(MAME_DIR)/src/machine/digdug.c \
$(MAME_DIR)/src/vidhrdw/digdug.c \
$(MAME_DIR)/src/drivers/digdug.c \
$(MAME_DIR)/src/vidhrdw/xevious.c \
$(MAME_DIR)/src/machine/xevious.c \
$(MAME_DIR)/src/drivers/xevious.c \
$(MAME_DIR)/src/machine/superpac.c \
$(MAME_DIR)/src/vidhrdw/superpac.c \
$(MAME_DIR)/src/drivers/superpac.c \
$(MAME_DIR)/src/machine/phozon.c \
$(MAME_DIR)/src/vidhrdw/phozon.c \
$(MAME_DIR)/src/drivers/phozon.c \
$(MAME_DIR)/src/machine/mappy.c \
$(MAME_DIR)/src/vidhrdw/mappy.c \
$(MAME_DIR)/src/drivers/mappy.c \
$(MAME_DIR)/src/machine/grobda.c \
$(MAME_DIR)/src/vidhrdw/grobda.c \
$(MAME_DIR)/src/drivers/grobda.c \
$(MAME_DIR)/src/machine/gaplus.c \
$(MAME_DIR)/src/vidhrdw/gaplus.c \
$(MAME_DIR)/src/drivers/gaplus.c \
$(MAME_DIR)/src/machine/toypop.c \
$(MAME_DIR)/src/vidhrdw/toypop.c \
$(MAME_DIR)/src/drivers/toypop.c \
$(MAME_DIR)/src/machine/polepos.c \
$(MAME_DIR)/src/vidhrdw/polepos.c \
$(MAME_DIR)/src/sndhrdw/polepos.c \
$(MAME_DIR)/src/drivers/polepos.c \
$(MAME_DIR)/src/vidhrdw/pacland.c \
$(MAME_DIR)/src/drivers/pacland.c \
$(MAME_DIR)/src/vidhrdw/skykid.c \
$(MAME_DIR)/src/drivers/skykid.c \
$(MAME_DIR)/src/vidhrdw/baraduke.c \
$(MAME_DIR)/src/drivers/baraduke.c \
$(MAME_DIR)/src/vidhrdw/namcos86.c \
$(MAME_DIR)/src/drivers/namcos86.c \
$(MAME_DIR)/src/vidhrdw/tceptor.c \
$(MAME_DIR)/src/drivers/tceptor.c \
$(MAME_DIR)/src/machine/namcos1.c \
$(MAME_DIR)/src/vidhrdw/namcos1.c \
$(MAME_DIR)/src/drivers/namcos1.c \
$(MAME_DIR)/src/machine/namcos2.c \
$(MAME_DIR)/src/vidhrdw/namcos2.c \
$(MAME_DIR)/src/drivers/namcos2.c \
$(MAME_DIR)/src/drivers/namcoic.c \
$(MAME_DIR)/src/vidhrdw/namcona1.c \
$(MAME_DIR)/src/drivers/namcona1.c \
$(MAME_DIR)/src/vidhrdw/namconb1.c \
$(MAME_DIR)/src/drivers/namconb1.c \
$(MAME_DIR)/src/machine/namcond1.c \
$(MAME_DIR)/src/vidhrdw/ygv608.c \
$(MAME_DIR)/src/drivers/namcond1.c \
$(MAME_DIR)/src/vidhrdw/psx.c \
$(MAME_DIR)/src/machine/psx.c \
$(MAME_DIR)/src/drivers/namcos10.c \
$(MAME_DIR)/src/drivers/namcos11.c \
$(MAME_DIR)/src/drivers/namcos12.c \
$(MAME_DIR)/src/vidhrdw/namcos3d.c \
$(MAME_DIR)/src/vidhrdw/namcos21.c \
$(MAME_DIR)/src/drivers/namcos21.c \
$(MAME_DIR)/src/vidhrdw/namcos22.c \
$(MAME_DIR)/src/drivers/namcos22.c \
$(MAME_DIR)/src/vidhrdw/cosmic.c \
$(MAME_DIR)/src/drivers/cosmic.c \
$(MAME_DIR)/src/vidhrdw/redclash.c \
$(MAME_DIR)/src/drivers/redclash.c \
$(MAME_DIR)/src/vidhrdw/ladybug.c \
$(MAME_DIR)/src/drivers/ladybug.c \
$(MAME_DIR)/src/vidhrdw/cheekyms.c \
$(MAME_DIR)/src/drivers/cheekyms.c \
$(MAME_DIR)/src/vidhrdw/mrdo.c \
$(MAME_DIR)/src/drivers/mrdo.c \
$(MAME_DIR)/src/machine/docastle.c \
$(MAME_DIR)/src/vidhrdw/docastle.c \
$(MAME_DIR)/src/drivers/docastle.c \
$(MAME_DIR)/src/vidhrdw/dkong.c \
$(MAME_DIR)/src/sndhrdw/dkong.c \
$(MAME_DIR)/src/drivers/dkong.c \
$(MAME_DIR)/src/machine/strtheat.c \
$(MAME_DIR)/src/vidhrdw/mario.c \
$(MAME_DIR)/src/sndhrdw/mario.c \
$(MAME_DIR)/src/drivers/mario.c \
$(MAME_DIR)/src/vidhrdw/popeye.c \
$(MAME_DIR)/src/drivers/popeye.c \
$(MAME_DIR)/src/vidhrdw/punchout.c \
$(MAME_DIR)/src/drivers/punchout.c \
$(MAME_DIR)/src/machine/rp5h01.c \
$(MAME_DIR)/src/vidhrdw/ppu2c03b.c \
$(MAME_DIR)/src/machine/playch10.c \
$(MAME_DIR)/src/vidhrdw/playch10.c \
$(MAME_DIR)/src/drivers/playch10.c \
$(MAME_DIR)/src/machine/vsnes.c \
$(MAME_DIR)/src/vidhrdw/vsnes.c \
$(MAME_DIR)/src/drivers/vsnes.c \
$(MAME_DIR)/src/machine/snes.c \
$(MAME_DIR)/src/vidhrdw/snes.c \
$(MAME_DIR)/src/sndhrdw/snes.c \
$(MAME_DIR)/src/drivers/nss.c \
$(MAME_DIR)/src/machine/8080bw.c \
$(MAME_DIR)/src/vidhrdw/8080bw.c \
$(MAME_DIR)/src/sndhrdw/8080bw.c \
$(MAME_DIR)/src/drivers/8080bw.c \
$(MAME_DIR)/src/vidhrdw/sspeedr.c \
$(MAME_DIR)/src/drivers/sspeedr.c \
$(MAME_DIR)/src/vidhrdw/m79amb.c \
$(MAME_DIR)/src/drivers/m79amb.c \
$(MAME_DIR)/src/drivers/rotaryf.c \
$(MAME_DIR)/src/drivers/lazercmd.c \
$(MAME_DIR)/src/vidhrdw/lazercmd.c \
$(MAME_DIR)/src/drivers/meadows.c \
$(MAME_DIR)/src/sndhrdw/meadows.c \
$(MAME_DIR)/src/vidhrdw/meadows.c \
$(MAME_DIR)/src/drivers/cvs.c \
$(MAME_DIR)/src/vidhrdw/cvs.c \
$(MAME_DIR)/src/vidhrdw/s2636.c \
$(MAME_DIR)/src/machine/astrocde.c \
$(MAME_DIR)/src/vidhrdw/astrocde.c \
$(MAME_DIR)/src/sndhrdw/astrocde.c \
$(MAME_DIR)/src/sndhrdw/gorf.c \
$(MAME_DIR)/src/drivers/astrocde.c \
$(MAME_DIR)/src/machine/mcr.c \
$(MAME_DIR)/src/sndhrdw/mcr.c \
$(MAME_DIR)/src/vidhrdw/mcr12.c \
$(MAME_DIR)/src/vidhrdw/mcr3.c \
$(MAME_DIR)/src/drivers/mcr1.c \
$(MAME_DIR)/src/drivers/mcr2.c \
$(MAME_DIR)/src/drivers/mcr3.c \
$(MAME_DIR)/src/vidhrdw/mcr68.c \
$(MAME_DIR)/src/drivers/mcr68.c \
$(MAME_DIR)/src/vidhrdw/balsente.c \
$(MAME_DIR)/src/machine/balsente.c \
$(MAME_DIR)/src/drivers/balsente.c \
$(MAME_DIR)/src/vidhrdw/gridlee.c \
$(MAME_DIR)/src/sndhrdw/gridlee.c \
$(MAME_DIR)/src/drivers/gridlee.c \
$(MAME_DIR)/src/drivers/seattle.c \
$(MAME_DIR)/src/vidhrdw/voodoo.c \
$(MAME_DIR)/src/vidhrdw/exterm.c \
$(MAME_DIR)/src/drivers/exterm.c \
$(MAME_DIR)/src/machine/midwayic.c \
$(MAME_DIR)/src/sndhrdw/dcs.c \
$(MAME_DIR)/src/machine/midyunit.c \
$(MAME_DIR)/src/vidhrdw/midyunit.c \
$(MAME_DIR)/src/drivers/midyunit.c \
$(MAME_DIR)/src/drivers/midxunit.c \
$(MAME_DIR)/src/machine/midwunit.c \
$(MAME_DIR)/src/drivers/midwunit.c \
$(MAME_DIR)/src/vidhrdw/midvunit.c \
$(MAME_DIR)/src/drivers/midvunit.c \
$(MAME_DIR)/src/machine/midtunit.c \
$(MAME_DIR)/src/vidhrdw/midtunit.c \
$(MAME_DIR)/src/drivers/midtunit.c \
$(MAME_DIR)/src/vidhrdw/skychut.c \
$(MAME_DIR)/src/drivers/skychut.c \
$(MAME_DIR)/src/drivers/olibochu.c \
$(MAME_DIR)/src/sndhrdw/irem.c \
$(MAME_DIR)/src/vidhrdw/mpatrol.c \
$(MAME_DIR)/src/drivers/mpatrol.c \
$(MAME_DIR)/src/vidhrdw/troangel.c \
$(MAME_DIR)/src/drivers/troangel.c \
$(MAME_DIR)/src/vidhrdw/yard.c \
$(MAME_DIR)/src/drivers/yard.c \
$(MAME_DIR)/src/vidhrdw/travrusa.c \
$(MAME_DIR)/src/drivers/travrusa.c \
$(MAME_DIR)/src/drivers/wilytowr.c \
$(MAME_DIR)/src/vidhrdw/m62.c \
$(MAME_DIR)/src/drivers/m62.c \
$(MAME_DIR)/src/vidhrdw/vigilant.c \
$(MAME_DIR)/src/drivers/vigilant.c \
$(MAME_DIR)/src/vidhrdw/m72.c \
$(MAME_DIR)/src/sndhrdw/m72.c \
$(MAME_DIR)/src/drivers/m72.c \
$(MAME_DIR)/src/vidhrdw/shisen.c \
$(MAME_DIR)/src/drivers/shisen.c \
$(MAME_DIR)/src/machine/irem_cpu.c \
$(MAME_DIR)/src/vidhrdw/m90.c \
$(MAME_DIR)/src/drivers/m90.c \
$(MAME_DIR)/src/vidhrdw/m92.c \
$(MAME_DIR)/src/drivers/m92.c \
$(MAME_DIR)/src/vidhrdw/m107.c \
$(MAME_DIR)/src/drivers/m107.c \
$(MAME_DIR)/src/vidhrdw/gottlieb.c \
$(MAME_DIR)/src/sndhrdw/gottlieb.c \
$(MAME_DIR)/src/drivers/gottlieb.c \
$(MAME_DIR)/src/drivers/sbowling.c \
$(MAME_DIR)/src/machine/chaknpop.c \
$(MAME_DIR)/src/vidhrdw/chaknpop.c \
$(MAME_DIR)/src/drivers/chaknpop.c \
$(MAME_DIR)/src/machine/qix.c \
$(MAME_DIR)/src/vidhrdw/qix.c \
$(MAME_DIR)/src/drivers/qix.c \
$(MAME_DIR)/src/machine/taitosj.c \
$(MAME_DIR)/src/vidhrdw/taitosj.c \
$(MAME_DIR)/src/drivers/taitosj.c \
$(MAME_DIR)/src/machine/grchamp.c \
$(MAME_DIR)/src/vidhrdw/grchamp.c \
$(MAME_DIR)/src/drivers/grchamp.c \
$(MAME_DIR)/src/machine/pitnrun.c \
$(MAME_DIR)/src/vidhrdw/pitnrun.c \
$(MAME_DIR)/src/drivers/pitnrun.c \
$(MAME_DIR)/src/drivers/marinedt.c \
$(MAME_DIR)/src/vidhrdw/crbaloon.c \
$(MAME_DIR)/src/drivers/crbaloon.c \
$(MAME_DIR)/src/vidhrdw/bking2.c \
$(MAME_DIR)/src/drivers/bking2.c \
$(MAME_DIR)/src/vidhrdw/gsword.c \
$(MAME_DIR)/src/drivers/gsword.c \
$(MAME_DIR)/src/machine/tait8741.c \
$(MAME_DIR)/src/vidhrdw/msisaac.c \
$(MAME_DIR)/src/drivers/msisaac.c \
$(MAME_DIR)/src/machine/retofinv.c \
$(MAME_DIR)/src/vidhrdw/retofinv.c \
$(MAME_DIR)/src/drivers/retofinv.c \
$(MAME_DIR)/src/vidhrdw/rollrace.c \
$(MAME_DIR)/src/drivers/rollrace.c \
$(MAME_DIR)/src/vidhrdw/40love.c \
$(MAME_DIR)/src/drivers/40love.c \
$(MAME_DIR)/src/vidhrdw/ssrj.c \
$(MAME_DIR)/src/drivers/ssrj.c \
$(MAME_DIR)/src/machine/bigevglf.c \
$(MAME_DIR)/src/vidhrdw/bigevglf.c \
$(MAME_DIR)/src/drivers/bigevglf.c \
$(MAME_DIR)/src/vidhrdw/tsamurai.c \
$(MAME_DIR)/src/drivers/tsamurai.c \
$(MAME_DIR)/src/machine/flstory.c \
$(MAME_DIR)/src/vidhrdw/flstory.c \
$(MAME_DIR)/src/drivers/flstory.c \
$(MAME_DIR)/src/vidhrdw/gladiatr.c \
$(MAME_DIR)/src/drivers/gladiatr.c \
$(MAME_DIR)/src/machine/nycaptor.c \
$(MAME_DIR)/src/vidhrdw/nycaptor.c \
$(MAME_DIR)/src/drivers/nycaptor.c \
$(MAME_DIR)/src/drivers/halleys.c \
$(MAME_DIR)/src/machine/lsasquad.c \
$(MAME_DIR)/src/vidhrdw/lsasquad.c \
$(MAME_DIR)/src/drivers/lsasquad.c \
$(MAME_DIR)/src/machine/bublbobl.c \
$(MAME_DIR)/src/vidhrdw/bublbobl.c \
$(MAME_DIR)/src/drivers/bublbobl.c \
$(MAME_DIR)/src/drivers/missb2.c \
$(MAME_DIR)/src/machine/mexico86.c \
$(MAME_DIR)/src/vidhrdw/mexico86.c \
$(MAME_DIR)/src/drivers/mexico86.c \
$(MAME_DIR)/src/vidhrdw/darius.c \
$(MAME_DIR)/src/drivers/darius.c \
$(MAME_DIR)/src/vidhrdw/rastan.c \
$(MAME_DIR)/src/sndhrdw/rastan.c \
$(MAME_DIR)/src/drivers/rastan.c \
$(MAME_DIR)/src/machine/rainbow.c \
$(MAME_DIR)/src/drivers/rainbow.c \
$(MAME_DIR)/src/drivers/opwolf.c \
$(MAME_DIR)/src/vidhrdw/othunder.c \
$(MAME_DIR)/src/drivers/othunder.c \
$(MAME_DIR)/src/vidhrdw/topspeed.c \
$(MAME_DIR)/src/drivers/topspeed.c \
$(MAME_DIR)/src/machine/arkanoid.c \
$(MAME_DIR)/src/vidhrdw/arkanoid.c \
$(MAME_DIR)/src/drivers/arkanoid.c \
$(MAME_DIR)/src/vidhrdw/superqix.c \
$(MAME_DIR)/src/drivers/superqix.c \
$(MAME_DIR)/src/vidhrdw/pbillian.c \
$(MAME_DIR)/src/drivers/pbillian.c \
$(MAME_DIR)/src/sndhrdw/pbillian.c \
$(MAME_DIR)/src/vidhrdw/exzisus.c \
$(MAME_DIR)/src/drivers/exzisus.c \
$(MAME_DIR)/src/drivers/taito_x.c \
$(MAME_DIR)/src/machine/cchip.c \
$(MAME_DIR)/src/vidhrdw/minivadr.c \
$(MAME_DIR)/src/drivers/minivadr.c \
$(MAME_DIR)/src/drivers/ashnojoe.c \
$(MAME_DIR)/src/vidhrdw/ashnojoe.c \
$(MAME_DIR)/src/machine/volfied.c \
$(MAME_DIR)/src/vidhrdw/volfied.c \
$(MAME_DIR)/src/drivers/volfied.c \
$(MAME_DIR)/src/machine/bonzeadv.c \
$(MAME_DIR)/src/vidhrdw/asuka.c \
$(MAME_DIR)/src/drivers/asuka.c \
$(MAME_DIR)/src/vidhrdw/wgp.c \
$(MAME_DIR)/src/drivers/wgp.c \
$(MAME_DIR)/src/vidhrdw/slapshot.c \
$(MAME_DIR)/src/drivers/slapshot.c \
$(MAME_DIR)/src/vidhrdw/ninjaw.c \
$(MAME_DIR)/src/drivers/ninjaw.c \
$(MAME_DIR)/src/vidhrdw/warriorb.c \
$(MAME_DIR)/src/drivers/warriorb.c \
$(MAME_DIR)/src/machine/tnzs.c \
$(MAME_DIR)/src/vidhrdw/tnzs.c \
$(MAME_DIR)/src/drivers/tnzs.c \
$(MAME_DIR)/src/machine/buggychl.c \
$(MAME_DIR)/src/vidhrdw/buggychl.c \
$(MAME_DIR)/src/drivers/buggychl.c \
$(MAME_DIR)/src/machine/lkage.c \
$(MAME_DIR)/src/vidhrdw/lkage.c \
$(MAME_DIR)/src/drivers/lkage.c \
$(MAME_DIR)/src/vidhrdw/taitoic.c \
$(MAME_DIR)/src/sndhrdw/taitosnd.c \
$(MAME_DIR)/src/vidhrdw/taito_l.c \
$(MAME_DIR)/src/drivers/taito_l.c \
$(MAME_DIR)/src/vidhrdw/taito_h.c \
$(MAME_DIR)/src/drivers/taito_h.c \
$(MAME_DIR)/src/vidhrdw/taito_b.c \
$(MAME_DIR)/src/drivers/taito_b.c \
$(MAME_DIR)/src/vidhrdw/taito_z.c \
$(MAME_DIR)/src/drivers/taito_z.c \
$(MAME_DIR)/src/vidhrdw/gunbustr.c \
$(MAME_DIR)/src/drivers/gunbustr.c \
$(MAME_DIR)/src/vidhrdw/superchs.c \
$(MAME_DIR)/src/drivers/superchs.c \
$(MAME_DIR)/src/vidhrdw/undrfire.c \
$(MAME_DIR)/src/drivers/undrfire.c \
$(MAME_DIR)/src/vidhrdw/groundfx.c \
$(MAME_DIR)/src/drivers/groundfx.c \
$(MAME_DIR)/src/vidhrdw/taito_f2.c \
$(MAME_DIR)/src/drivers/taito_f2.c \
$(MAME_DIR)/src/vidhrdw/taito_f3.c \
$(MAME_DIR)/src/sndhrdw/taito_f3.c \
$(MAME_DIR)/src/drivers/taito_f3.c \
$(MAME_DIR)/src/vidhrdw/taitoair.c \
$(MAME_DIR)/src/drivers/taitoair.c \
$(MAME_DIR)/src/machine/slapfght.c \
$(MAME_DIR)/src/vidhrdw/slapfght.c \
$(MAME_DIR)/src/drivers/slapfght.c \
$(MAME_DIR)/src/machine/twincobr.c \
$(MAME_DIR)/src/vidhrdw/twincobr.c \
$(MAME_DIR)/src/drivers/twincobr.c \
$(MAME_DIR)/src/drivers/wardner.c \
$(MAME_DIR)/src/drivers/mjsister.c \
$(MAME_DIR)/src/vidhrdw/mjsister.c \
$(MAME_DIR)/src/machine/toaplan1.c \
$(MAME_DIR)/src/vidhrdw/toaplan1.c \
$(MAME_DIR)/src/drivers/toaplan1.c \
$(MAME_DIR)/src/vidhrdw/snowbros.c \
$(MAME_DIR)/src/drivers/snowbros.c \
$(MAME_DIR)/src/vidhrdw/toaplan2.c \
$(MAME_DIR)/src/drivers/toaplan2.c \
$(MAME_DIR)/src/vidhrdw/cave.c \
$(MAME_DIR)/src/drivers/cave.c \
$(MAME_DIR)/src/vidhrdw/kyugo.c \
$(MAME_DIR)/src/machine/kyugo.c \
$(MAME_DIR)/src/drivers/kyugo.c \
$(MAME_DIR)/src/machine/williams.c \
$(MAME_DIR)/src/vidhrdw/williams.c \
$(MAME_DIR)/src/sndhrdw/williams.c \
$(MAME_DIR)/src/drivers/williams.c \
$(MAME_DIR)/src/vidhrdw/vulgus.c \
$(MAME_DIR)/src/drivers/vulgus.c \
$(MAME_DIR)/src/vidhrdw/sonson.c \
$(MAME_DIR)/src/drivers/sonson.c \
$(MAME_DIR)/src/vidhrdw/higemaru.c \
$(MAME_DIR)/src/drivers/higemaru.c \
$(MAME_DIR)/src/vidhrdw/1942.c \
$(MAME_DIR)/src/drivers/1942.c \
$(MAME_DIR)/src/vidhrdw/exedexes.c \
$(MAME_DIR)/src/drivers/exedexes.c \
$(MAME_DIR)/src/vidhrdw/commando.c \
$(MAME_DIR)/src/drivers/commando.c \
$(MAME_DIR)/src/vidhrdw/gng.c \
$(MAME_DIR)/src/drivers/gng.c \
$(MAME_DIR)/src/vidhrdw/gunsmoke.c \
$(MAME_DIR)/src/drivers/gunsmoke.c \
$(MAME_DIR)/src/vidhrdw/srumbler.c \
$(MAME_DIR)/src/drivers/srumbler.c \
$(MAME_DIR)/src/vidhrdw/lwings.c \
$(MAME_DIR)/src/drivers/lwings.c \
$(MAME_DIR)/src/vidhrdw/sidearms.c \
$(MAME_DIR)/src/drivers/sidearms.c \
$(MAME_DIR)/src/vidhrdw/bionicc.c \
$(MAME_DIR)/src/drivers/bionicc.c \
$(MAME_DIR)/src/vidhrdw/1943.c \
$(MAME_DIR)/src/drivers/1943.c \
$(MAME_DIR)/src/vidhrdw/blktiger.c \
$(MAME_DIR)/src/drivers/blktiger.c \
$(MAME_DIR)/src/vidhrdw/tigeroad.c \
$(MAME_DIR)/src/drivers/tigeroad.c \
$(MAME_DIR)/src/vidhrdw/lastduel.c \
$(MAME_DIR)/src/drivers/lastduel.c \
$(MAME_DIR)/src/vidhrdw/sf1.c \
$(MAME_DIR)/src/drivers/sf1.c \
$(MAME_DIR)/src/machine/kabuki.c \
$(MAME_DIR)/src/vidhrdw/mitchell.c \
$(MAME_DIR)/src/drivers/mitchell.c \
$(MAME_DIR)/src/vidhrdw/cbasebal.c \
$(MAME_DIR)/src/drivers/cbasebal.c \
$(MAME_DIR)/src/vidhrdw/cps1.c \
$(MAME_DIR)/src/drivers/cps1.c \
$(MAME_DIR)/src/drivers/cps2.c \
$(MAME_DIR)/src/drivers/zn.c \
$(MAME_DIR)/src/vidhrdw/tms34061.c \
$(MAME_DIR)/src/machine/capbowl.c \
$(MAME_DIR)/src/vidhrdw/capbowl.c \
$(MAME_DIR)/src/drivers/capbowl.c \
$(MAME_DIR)/src/vidhrdw/itech8.c \
$(MAME_DIR)/src/drivers/itech8.c \
$(MAME_DIR)/src/machine/slikshot.c \
$(MAME_DIR)/src/vidhrdw/itech32.c \
$(MAME_DIR)/src/drivers/itech32.c \
$(MAME_DIR)/src/vidhrdw/blockade.c \
$(MAME_DIR)/src/drivers/blockade.c \
$(MAME_DIR)/src/vidhrdw/vicdual.c \
$(MAME_DIR)/src/drivers/vicdual.c \
$(MAME_DIR)/src/sndhrdw/carnival.c \
$(MAME_DIR)/src/sndhrdw/depthch.c \
$(MAME_DIR)/src/sndhrdw/invinco.c \
$(MAME_DIR)/src/sndhrdw/pulsar.c \
$(MAME_DIR)/src/machine/segacrpt.c \
$(MAME_DIR)/src/sndhrdw/segasnd.c \
$(MAME_DIR)/src/vidhrdw/sega.c \
$(MAME_DIR)/src/sndhrdw/sega.c \
$(MAME_DIR)/src/machine/sega.c \
$(MAME_DIR)/src/drivers/sega.c \
$(MAME_DIR)/src/vidhrdw/segar.c \
$(MAME_DIR)/src/sndhrdw/segar.c \
$(MAME_DIR)/src/machine/segar.c \
$(MAME_DIR)/src/drivers/segar.c \
$(MAME_DIR)/src/vidhrdw/tms9928a.c \
$(MAME_DIR)/src/drivers/sg1000a.c \
$(MAME_DIR)/src/vidhrdw/zaxxon.c \
$(MAME_DIR)/src/sndhrdw/zaxxon.c \
$(MAME_DIR)/src/drivers/zaxxon.c \
$(MAME_DIR)/src/machine/turbo.c \
$(MAME_DIR)/src/vidhrdw/turbo.c \
$(MAME_DIR)/src/drivers/turbo.c \
$(MAME_DIR)/src/drivers/kopunch.c \
$(MAME_DIR)/src/vidhrdw/kopunch.c \
$(MAME_DIR)/src/vidhrdw/suprloco.c \
$(MAME_DIR)/src/drivers/suprloco.c \
$(MAME_DIR)/src/vidhrdw/dotrikun.c \
$(MAME_DIR)/src/drivers/dotrikun.c \
$(MAME_DIR)/src/vidhrdw/angelkds.c \
$(MAME_DIR)/src/drivers/angelkds.c \
$(MAME_DIR)/src/vidhrdw/system1.c \
$(MAME_DIR)/src/drivers/system1.c \
$(MAME_DIR)/src/vidhrdw/segasyse.c \
$(MAME_DIR)/src/drivers/segasyse.c \
$(MAME_DIR)/src/machine/system16.c \
$(MAME_DIR)/src/vidhrdw/system16.c \
$(MAME_DIR)/src/vidhrdw/sys16spr.c \
$(MAME_DIR)/src/sndhrdw/system16.c \
$(MAME_DIR)/src/drivers/system16.c \
$(MAME_DIR)/src/drivers/aburner.c \
$(MAME_DIR)/src/drivers/outrun.c \
$(MAME_DIR)/src/drivers/sharrier.c \
$(MAME_DIR)/src/drivers/system18.c \
$(MAME_DIR)/src/drivers/system24.c \
$(MAME_DIR)/src/machine/system24.c \
$(MAME_DIR)/src/vidhrdw/system24.c \
$(MAME_DIR)/src/vidhrdw/segaic24.c \
$(MAME_DIR)/src/drivers/system32.c \
$(MAME_DIR)/src/drivers/multi32.c \
$(MAME_DIR)/src/vidhrdw/system32.c \
$(MAME_DIR)/src/vidhrdw/segac2.c \
$(MAME_DIR)/src/drivers/segac2.c \
$(MAME_DIR)/src/drivers/stv.c \
$(MAME_DIR)/src/drivers/stvhacks.c \
$(MAME_DIR)/src/machine/stvcd.c \
$(MAME_DIR)/src/machine/scudsp.c \
$(MAME_DIR)/src/vidhrdw/stvvdp1.c \
$(MAME_DIR)/src/vidhrdw/stvvdp2.c \
$(MAME_DIR)/src/vidhrdw/deniam.c \
$(MAME_DIR)/src/drivers/deniam.c \
$(MAME_DIR)/src/machine/btime.c \
$(MAME_DIR)/src/vidhrdw/btime.c \
$(MAME_DIR)/src/drivers/btime.c \
$(MAME_DIR)/src/machine/decocass.c \
$(MAME_DIR)/src/vidhrdw/decocass.c \
$(MAME_DIR)/src/drivers/decocass.c \
$(MAME_DIR)/src/vidhrdw/astrof.c \
$(MAME_DIR)/src/sndhrdw/astrof.c \
$(MAME_DIR)/src/drivers/astrof.c \
$(MAME_DIR)/src/vidhrdw/liberate.c \
$(MAME_DIR)/src/drivers/liberate.c \
$(MAME_DIR)/src/vidhrdw/bwing.c \
$(MAME_DIR)/src/drivers/bwing.c \
$(MAME_DIR)/src/vidhrdw/kchamp.c \
$(MAME_DIR)/src/drivers/kchamp.c \
$(MAME_DIR)/src/vidhrdw/firetrap.c \
$(MAME_DIR)/src/drivers/firetrap.c \
$(MAME_DIR)/src/vidhrdw/brkthru.c \
$(MAME_DIR)/src/drivers/brkthru.c \
$(MAME_DIR)/src/vidhrdw/metlclsh.c \
$(MAME_DIR)/src/drivers/metlclsh.c \
$(MAME_DIR)/src/drivers/compgolf.c \
$(MAME_DIR)/src/drivers/tryout.c \
$(MAME_DIR)/src/vidhrdw/shootout.c \
$(MAME_DIR)/src/drivers/shootout.c \
$(MAME_DIR)/src/vidhrdw/sidepckt.c \
$(MAME_DIR)/src/drivers/sidepckt.c \
$(MAME_DIR)/src/vidhrdw/exprraid.c \
$(MAME_DIR)/src/drivers/exprraid.c \
$(MAME_DIR)/src/vidhrdw/pcktgal.c \
$(MAME_DIR)/src/drivers/pcktgal.c \
$(MAME_DIR)/src/vidhrdw/battlera.c \
$(MAME_DIR)/src/drivers/battlera.c \
$(MAME_DIR)/src/vidhrdw/actfancr.c \
$(MAME_DIR)/src/drivers/actfancr.c \
$(MAME_DIR)/src/vidhrdw/dec8.c \
$(MAME_DIR)/src/drivers/dec8.c \
$(MAME_DIR)/src/vidhrdw/karnov.c \
$(MAME_DIR)/src/drivers/karnov.c \
$(MAME_DIR)/src/machine/decocrpt.c \
$(MAME_DIR)/src/machine/decoprot.c \
$(MAME_DIR)/src/vidhrdw/deco16ic.c \
$(MAME_DIR)/src/machine/dec0.c \
$(MAME_DIR)/src/vidhrdw/dec0.c \
$(MAME_DIR)/src/drivers/dec0.c \
$(MAME_DIR)/src/vidhrdw/stadhero.c \
$(MAME_DIR)/src/drivers/stadhero.c \
$(MAME_DIR)/src/vidhrdw/madmotor.c \
$(MAME_DIR)/src/drivers/madmotor.c \
$(MAME_DIR)/src/vidhrdw/vaportra.c \
$(MAME_DIR)/src/drivers/vaportra.c \
$(MAME_DIR)/src/vidhrdw/cbuster.c \
$(MAME_DIR)/src/drivers/cbuster.c \
$(MAME_DIR)/src/vidhrdw/darkseal.c \
$(MAME_DIR)/src/drivers/darkseal.c \
$(MAME_DIR)/src/vidhrdw/supbtime.c \
$(MAME_DIR)/src/drivers/supbtime.c \
$(MAME_DIR)/src/vidhrdw/cninja.c \
$(MAME_DIR)/src/drivers/cninja.c \
$(MAME_DIR)/src/vidhrdw/dassault.c \
$(MAME_DIR)/src/drivers/dassault.c \
$(MAME_DIR)/src/vidhrdw/rohga.c \
$(MAME_DIR)/src/drivers/rohga.c \
$(MAME_DIR)/src/vidhrdw/tumblep.c \
$(MAME_DIR)/src/drivers/tumblep.c \
$(MAME_DIR)/src/vidhrdw/lemmings.c \
$(MAME_DIR)/src/drivers/lemmings.c \
$(MAME_DIR)/src/vidhrdw/funkyjet.c \
$(MAME_DIR)/src/drivers/funkyjet.c \
$(MAME_DIR)/src/vidhrdw/deco32.c \
$(MAME_DIR)/src/drivers/deco32.c \
$(MAME_DIR)/src/vidhrdw/avengrgs.c \
$(MAME_DIR)/src/drivers/avengrgs.c \
$(MAME_DIR)/src/vidhrdw/sshangha.c \
$(MAME_DIR)/src/drivers/sshangha.c \
$(MAME_DIR)/src/sndhrdw/senjyo.c \
$(MAME_DIR)/src/vidhrdw/senjyo.c \
$(MAME_DIR)/src/drivers/senjyo.c \
$(MAME_DIR)/src/vidhrdw/bombjack.c \
$(MAME_DIR)/src/drivers/bombjack.c \
$(MAME_DIR)/src/vidhrdw/pbaction.c \
$(MAME_DIR)/src/drivers/pbaction.c \
$(MAME_DIR)/src/vidhrdw/tehkanwc.c \
$(MAME_DIR)/src/drivers/tehkanwc.c \
$(MAME_DIR)/src/vidhrdw/solomon.c \
$(MAME_DIR)/src/drivers/solomon.c \
$(MAME_DIR)/src/vidhrdw/tecmo.c \
$(MAME_DIR)/src/drivers/tecmo.c \
$(MAME_DIR)/src/vidhrdw/tbowl.c \
$(MAME_DIR)/src/drivers/tbowl.c \
$(MAME_DIR)/src/vidhrdw/gaiden.c \
$(MAME_DIR)/src/drivers/gaiden.c \
$(MAME_DIR)/src/vidhrdw/wc90.c \
$(MAME_DIR)/src/drivers/wc90.c \
$(MAME_DIR)/src/vidhrdw/wc90b.c \
$(MAME_DIR)/src/drivers/wc90b.c \
$(MAME_DIR)/src/vidhrdw/spbactn.c \
$(MAME_DIR)/src/drivers/spbactn.c \
$(MAME_DIR)/src/vidhrdw/tecmo16.c \
$(MAME_DIR)/src/drivers/tecmo16.c \
$(MAME_DIR)/src/drivers/tecmosys.c \
$(MAME_DIR)/src/machine/scramble.c \
$(MAME_DIR)/src/sndhrdw/scramble.c \
$(MAME_DIR)/src/drivers/scramble.c \
$(MAME_DIR)/src/drivers/frogger.c \
$(MAME_DIR)/src/drivers/scobra.c \
$(MAME_DIR)/src/drivers/amidar.c \
$(MAME_DIR)/src/vidhrdw/fastfred.c \
$(MAME_DIR)/src/drivers/fastfred.c \
$(MAME_DIR)/src/sndhrdw/timeplt.c \
$(MAME_DIR)/src/vidhrdw/tutankhm.c \
$(MAME_DIR)/src/drivers/tutankhm.c \
$(MAME_DIR)/src/drivers/junofrst.c \
$(MAME_DIR)/src/vidhrdw/pooyan.c \
$(MAME_DIR)/src/drivers/pooyan.c \
$(MAME_DIR)/src/vidhrdw/timeplt.c \
$(MAME_DIR)/src/drivers/timeplt.c \
$(MAME_DIR)/src/vidhrdw/megazone.c \
$(MAME_DIR)/src/drivers/megazone.c \
$(MAME_DIR)/src/vidhrdw/pandoras.c \
$(MAME_DIR)/src/drivers/pandoras.c \
$(MAME_DIR)/src/sndhrdw/gyruss.c \
$(MAME_DIR)/src/vidhrdw/gyruss.c \
$(MAME_DIR)/src/drivers/gyruss.c \
$(MAME_DIR)/src/machine/konami.c \
$(MAME_DIR)/src/vidhrdw/trackfld.c \
$(MAME_DIR)/src/sndhrdw/trackfld.c \
$(MAME_DIR)/src/drivers/trackfld.c \
$(MAME_DIR)/src/vidhrdw/rocnrope.c \
$(MAME_DIR)/src/drivers/rocnrope.c \
$(MAME_DIR)/src/vidhrdw/circusc.c \
$(MAME_DIR)/src/drivers/circusc.c \
$(MAME_DIR)/src/vidhrdw/tp84.c \
$(MAME_DIR)/src/drivers/tp84.c \
$(MAME_DIR)/src/vidhrdw/hyperspt.c \
$(MAME_DIR)/src/drivers/hyperspt.c \
$(MAME_DIR)/src/vidhrdw/sbasketb.c \
$(MAME_DIR)/src/drivers/sbasketb.c \
$(MAME_DIR)/src/vidhrdw/mikie.c \
$(MAME_DIR)/src/drivers/mikie.c \
$(MAME_DIR)/src/vidhrdw/yiear.c \
$(MAME_DIR)/src/drivers/yiear.c \
$(MAME_DIR)/src/vidhrdw/shaolins.c \
$(MAME_DIR)/src/drivers/shaolins.c \
$(MAME_DIR)/src/vidhrdw/pingpong.c \
$(MAME_DIR)/src/drivers/pingpong.c \
$(MAME_DIR)/src/vidhrdw/gberet.c \
$(MAME_DIR)/src/drivers/gberet.c \
$(MAME_DIR)/src/vidhrdw/jailbrek.c \
$(MAME_DIR)/src/drivers/jailbrek.c \
$(MAME_DIR)/src/vidhrdw/finalizr.c \
$(MAME_DIR)/src/drivers/finalizr.c \
$(MAME_DIR)/src/vidhrdw/ironhors.c \
$(MAME_DIR)/src/drivers/ironhors.c \
$(MAME_DIR)/src/machine/jackal.c \
$(MAME_DIR)/src/vidhrdw/jackal.c \
$(MAME_DIR)/src/drivers/jackal.c \
$(MAME_DIR)/src/vidhrdw/ddrible.c \
$(MAME_DIR)/src/drivers/ddrible.c \
$(MAME_DIR)/src/vidhrdw/contra.c \
$(MAME_DIR)/src/drivers/contra.c \
$(MAME_DIR)/src/vidhrdw/combatsc.c \
$(MAME_DIR)/src/drivers/combatsc.c \
$(MAME_DIR)/src/vidhrdw/hcastle.c \
$(MAME_DIR)/src/drivers/hcastle.c \
$(MAME_DIR)/src/vidhrdw/nemesis.c \
$(MAME_DIR)/src/drivers/nemesis.c \
$(MAME_DIR)/src/vidhrdw/konamiic.c \
$(MAME_DIR)/src/vidhrdw/rockrage.c \
$(MAME_DIR)/src/drivers/rockrage.c \
$(MAME_DIR)/src/vidhrdw/flkatck.c \
$(MAME_DIR)/src/drivers/flkatck.c \
$(MAME_DIR)/src/vidhrdw/fastlane.c \
$(MAME_DIR)/src/drivers/fastlane.c \
$(MAME_DIR)/src/vidhrdw/labyrunr.c \
$(MAME_DIR)/src/drivers/labyrunr.c \
$(MAME_DIR)/src/vidhrdw/battlnts.c \
$(MAME_DIR)/src/drivers/battlnts.c \
$(MAME_DIR)/src/vidhrdw/bladestl.c \
$(MAME_DIR)/src/drivers/bladestl.c \
$(MAME_DIR)/src/machine/ajax.c \
$(MAME_DIR)/src/vidhrdw/ajax.c \
$(MAME_DIR)/src/drivers/ajax.c \
$(MAME_DIR)/src/vidhrdw/thunderx.c \
$(MAME_DIR)/src/drivers/thunderx.c \
$(MAME_DIR)/src/vidhrdw/mainevt.c \
$(MAME_DIR)/src/drivers/mainevt.c \
$(MAME_DIR)/src/vidhrdw/88games.c \
$(MAME_DIR)/src/drivers/88games.c \
$(MAME_DIR)/src/vidhrdw/gbusters.c \
$(MAME_DIR)/src/drivers/gbusters.c \
$(MAME_DIR)/src/vidhrdw/crimfght.c \
$(MAME_DIR)/src/drivers/crimfght.c \
$(MAME_DIR)/src/vidhrdw/spy.c \
$(MAME_DIR)/src/drivers/spy.c \
$(MAME_DIR)/src/vidhrdw/bottom9.c \
$(MAME_DIR)/src/drivers/bottom9.c \
$(MAME_DIR)/src/vidhrdw/blockhl.c \
$(MAME_DIR)/src/drivers/blockhl.c \
$(MAME_DIR)/src/vidhrdw/aliens.c \
$(MAME_DIR)/src/drivers/aliens.c \
$(MAME_DIR)/src/vidhrdw/surpratk.c \
$(MAME_DIR)/src/drivers/surpratk.c \
$(MAME_DIR)/src/vidhrdw/parodius.c \
$(MAME_DIR)/src/drivers/parodius.c \
$(MAME_DIR)/src/vidhrdw/rollerg.c \
$(MAME_DIR)/src/drivers/rollerg.c \
$(MAME_DIR)/src/vidhrdw/xexex.c \
$(MAME_DIR)/src/drivers/xexex.c \
$(MAME_DIR)/src/vidhrdw/asterix.c \
$(MAME_DIR)/src/drivers/asterix.c \
$(MAME_DIR)/src/vidhrdw/gijoe.c \
$(MAME_DIR)/src/drivers/gijoe.c \
$(MAME_DIR)/src/machine/simpsons.c \
$(MAME_DIR)/src/vidhrdw/simpsons.c \
$(MAME_DIR)/src/drivers/simpsons.c \
$(MAME_DIR)/src/vidhrdw/vendetta.c \
$(MAME_DIR)/src/drivers/vendetta.c \
$(MAME_DIR)/src/vidhrdw/wecleman.c \
$(MAME_DIR)/src/drivers/wecleman.c \
$(MAME_DIR)/src/vidhrdw/chqflag.c \
$(MAME_DIR)/src/vidhrdw/ultraman.c \
$(MAME_DIR)/src/drivers/chqflag.c \
$(MAME_DIR)/src/drivers/ultraman.c \
$(MAME_DIR)/src/vidhrdw/hexion.c \
$(MAME_DIR)/src/drivers/hexion.c \
$(MAME_DIR)/src/vidhrdw/twin16.c \
$(MAME_DIR)/src/drivers/twin16.c \
$(MAME_DIR)/src/vidhrdw/tmnt.c \
$(MAME_DIR)/src/drivers/tmnt.c \
$(MAME_DIR)/src/vidhrdw/xmen.c \
$(MAME_DIR)/src/drivers/xmen.c \
$(MAME_DIR)/src/vidhrdw/overdriv.c \
$(MAME_DIR)/src/drivers/overdriv.c \
$(MAME_DIR)/src/vidhrdw/gradius3.c \
$(MAME_DIR)/src/drivers/gradius3.c \
$(MAME_DIR)/src/vidhrdw/moo.c \
$(MAME_DIR)/src/drivers/moo.c \
$(MAME_DIR)/src/vidhrdw/mystwarr.c \
$(MAME_DIR)/src/drivers/mystwarr.c \
$(MAME_DIR)/src/vidhrdw/rungun.c \
$(MAME_DIR)/src/drivers/rungun.c \
$(MAME_DIR)/src/vidhrdw/dbz2.c \
$(MAME_DIR)/src/drivers/dbz2.c \
$(MAME_DIR)/src/vidhrdw/bishi.c \
$(MAME_DIR)/src/drivers/bishi.c \
$(MAME_DIR)/src/machine/konamigx.c \
$(MAME_DIR)/src/vidhrdw/konamigx.c \
$(MAME_DIR)/src/drivers/konamigx.c \
$(MAME_DIR)/src/vidhrdw/djmain.c \
$(MAME_DIR)/src/drivers/djmain.c \
$(MAME_DIR)/src/vidhrdw/plygonet.c \
$(MAME_DIR)/src/drivers/plygonet.c \
$(MAME_DIR)/src/drivers/mogura.c \
$(MAME_DIR)/src/machine/am53cf96.c \
$(MAME_DIR)/src/drivers/konamigq.c \
$(MAME_DIR)/src/machine/carpolo.c \
$(MAME_DIR)/src/vidhrdw/carpolo.c \
$(MAME_DIR)/src/drivers/carpolo.c \
$(MAME_DIR)/src/vidhrdw/exidy.c \
$(MAME_DIR)/src/sndhrdw/exidy.c \
$(MAME_DIR)/src/drivers/exidy.c \
$(MAME_DIR)/src/sndhrdw/targ.c \
$(MAME_DIR)/src/vidhrdw/circus.c \
$(MAME_DIR)/src/drivers/circus.c \
$(MAME_DIR)/src/vidhrdw/starfire.c \
$(MAME_DIR)/src/drivers/starfire.c \
$(MAME_DIR)/src/vidhrdw/victory.c \
$(MAME_DIR)/src/drivers/victory.c \
$(MAME_DIR)/src/sndhrdw/exidy440.c \
$(MAME_DIR)/src/vidhrdw/exidy440.c \
$(MAME_DIR)/src/drivers/exidy440.c \
$(MAME_DIR)/src/machine/atari_vg.c \
$(MAME_DIR)/src/vidhrdw/tia.c \
$(MAME_DIR)/src/drivers/tourtabl.c \
$(MAME_DIR)/src/machine/asteroid.c \
$(MAME_DIR)/src/sndhrdw/asteroid.c \
$(MAME_DIR)/src/sndhrdw/llander.c \
$(MAME_DIR)/src/drivers/asteroid.c \
$(MAME_DIR)/src/drivers/bwidow.c \
$(MAME_DIR)/src/sndhrdw/bzone.c \
$(MAME_DIR)/src/drivers/bzone.c \
$(MAME_DIR)/src/sndhrdw/redbaron.c \
$(MAME_DIR)/src/drivers/tempest.c \
$(MAME_DIR)/src/machine/starwars.c \
$(MAME_DIR)/src/drivers/starwars.c \
$(MAME_DIR)/src/sndhrdw/starwars.c \
$(MAME_DIR)/src/machine/mhavoc.c \
$(MAME_DIR)/src/drivers/mhavoc.c \
$(MAME_DIR)/src/drivers/quantum.c \
$(MAME_DIR)/src/vidhrdw/copsnrob.c \
$(MAME_DIR)/src/machine/copsnrob.c \
$(MAME_DIR)/src/drivers/copsnrob.c \
$(MAME_DIR)/src/vidhrdw/flyball.c \
$(MAME_DIR)/src/drivers/flyball.c \
$(MAME_DIR)/src/vidhrdw/sprint2.c \
$(MAME_DIR)/src/drivers/sprint2.c \
$(MAME_DIR)/src/vidhrdw/sprint4.c \
$(MAME_DIR)/src/drivers/sprint4.c \
$(MAME_DIR)/src/vidhrdw/sprint8.c \
$(MAME_DIR)/src/drivers/sprint8.c \
$(MAME_DIR)/src/vidhrdw/nitedrvr.c \
$(MAME_DIR)/src/machine/nitedrvr.c \
$(MAME_DIR)/src/drivers/nitedrvr.c \
$(MAME_DIR)/src/machine/dominos.c \
$(MAME_DIR)/src/vidhrdw/triplhnt.c \
$(MAME_DIR)/src/drivers/triplhnt.c \
$(MAME_DIR)/src/vidhrdw/dragrace.c \
$(MAME_DIR)/src/drivers/dragrace.c \
$(MAME_DIR)/src/vidhrdw/poolshrk.c \
$(MAME_DIR)/src/drivers/poolshrk.c \
$(MAME_DIR)/src/vidhrdw/starshp1.c \
$(MAME_DIR)/src/drivers/starshp1.c \
$(MAME_DIR)/src/vidhrdw/canyon.c \
$(MAME_DIR)/src/drivers/canyon.c \
$(MAME_DIR)/src/vidhrdw/destroyr.c \
$(MAME_DIR)/src/drivers/destroyr.c \
$(MAME_DIR)/src/drivers/ultratnk.c \
$(MAME_DIR)/src/vidhrdw/wolfpack.c \
$(MAME_DIR)/src/drivers/wolfpack.c \
$(MAME_DIR)/src/vidhrdw/boxer.c \
$(MAME_DIR)/src/drivers/boxer.c \
$(MAME_DIR)/src/vidhrdw/skyraid.c \
$(MAME_DIR)/src/drivers/skyraid.c \
$(MAME_DIR)/src/machine/avalnche.c \
$(MAME_DIR)/src/vidhrdw/avalnche.c \
$(MAME_DIR)/src/drivers/avalnche.c \
$(MAME_DIR)/src/drivers/firetrk.c \
$(MAME_DIR)/src/vidhrdw/firetrk.c \
$(MAME_DIR)/src/vidhrdw/skydiver.c \
$(MAME_DIR)/src/drivers/skydiver.c \
$(MAME_DIR)/src/machine/sbrkout.c \
$(MAME_DIR)/src/vidhrdw/sbrkout.c \
$(MAME_DIR)/src/drivers/sbrkout.c \
$(MAME_DIR)/src/machine/atarifb.c \
$(MAME_DIR)/src/vidhrdw/atarifb.c \
$(MAME_DIR)/src/drivers/atarifb.c \
$(MAME_DIR)/src/vidhrdw/orbit.c \
$(MAME_DIR)/src/drivers/orbit.c \
$(MAME_DIR)/src/vidhrdw/videopin.c \
$(MAME_DIR)/src/drivers/videopin.c \
$(MAME_DIR)/src/machine/subs.c \
$(MAME_DIR)/src/vidhrdw/subs.c \
$(MAME_DIR)/src/drivers/subs.c \
$(MAME_DIR)/src/vidhrdw/bsktball.c \
$(MAME_DIR)/src/machine/bsktball.c \
$(MAME_DIR)/src/drivers/bsktball.c \
$(MAME_DIR)/src/vidhrdw/centiped.c \
$(MAME_DIR)/src/drivers/centiped.c \
$(MAME_DIR)/src/vidhrdw/runaway.c \
$(MAME_DIR)/src/drivers/runaway.c \
$(MAME_DIR)/src/machine/missile.c \
$(MAME_DIR)/src/vidhrdw/missile.c \
$(MAME_DIR)/src/drivers/missile.c \
$(MAME_DIR)/src/vidhrdw/foodf.c \
$(MAME_DIR)/src/drivers/foodf.c \
$(MAME_DIR)/src/drivers/tunhunt.c \
$(MAME_DIR)/src/vidhrdw/tunhunt.c \
$(MAME_DIR)/src/vidhrdw/liberatr.c \
$(MAME_DIR)/src/drivers/liberatr.c \
$(MAME_DIR)/src/vidhrdw/ccastles.c \
$(MAME_DIR)/src/drivers/ccastles.c \
$(MAME_DIR)/src/vidhrdw/cloak.c \
$(MAME_DIR)/src/drivers/cloak.c \
$(MAME_DIR)/src/vidhrdw/cloud9.c \
$(MAME_DIR)/src/drivers/cloud9.c \
$(MAME_DIR)/src/vidhrdw/jedi.c \
$(MAME_DIR)/src/drivers/jedi.c \
$(MAME_DIR)/src/machine/atarigen.c \
$(MAME_DIR)/src/sndhrdw/atarijsa.c \
$(MAME_DIR)/src/vidhrdw/atarimo.c \
$(MAME_DIR)/src/vidhrdw/atarirle.c \
$(MAME_DIR)/src/machine/slapstic.c \
$(MAME_DIR)/src/vidhrdw/atarisy1.c \
$(MAME_DIR)/src/drivers/atarisy1.c \
$(MAME_DIR)/src/vidhrdw/atarisy2.c \
$(MAME_DIR)/src/drivers/atarisy2.c \
$(MAME_DIR)/src/machine/irobot.c \
$(MAME_DIR)/src/vidhrdw/irobot.c \
$(MAME_DIR)/src/drivers/irobot.c \
$(MAME_DIR)/src/machine/harddriv.c \
$(MAME_DIR)/src/vidhrdw/harddriv.c \
$(MAME_DIR)/src/sndhrdw/harddriv.c \
$(MAME_DIR)/src/drivers/harddriv.c \
$(MAME_DIR)/src/vidhrdw/gauntlet.c \
$(MAME_DIR)/src/drivers/gauntlet.c \
$(MAME_DIR)/src/vidhrdw/atetris.c \
$(MAME_DIR)/src/drivers/atetris.c \
$(MAME_DIR)/src/vidhrdw/toobin.c \
$(MAME_DIR)/src/drivers/toobin.c \
$(MAME_DIR)/src/vidhrdw/vindictr.c \
$(MAME_DIR)/src/drivers/vindictr.c \
$(MAME_DIR)/src/vidhrdw/klax.c \
$(MAME_DIR)/src/drivers/klax.c \
$(MAME_DIR)/src/vidhrdw/blstroid.c \
$(MAME_DIR)/src/drivers/blstroid.c \
$(MAME_DIR)/src/vidhrdw/xybots.c \
$(MAME_DIR)/src/drivers/xybots.c \
$(MAME_DIR)/src/vidhrdw/eprom.c \
$(MAME_DIR)/src/drivers/eprom.c \
$(MAME_DIR)/src/vidhrdw/skullxbo.c \
$(MAME_DIR)/src/drivers/skullxbo.c \
$(MAME_DIR)/src/vidhrdw/badlands.c \
$(MAME_DIR)/src/drivers/badlands.c \
$(MAME_DIR)/src/vidhrdw/cyberbal.c \
$(MAME_DIR)/src/sndhrdw/cyberbal.c \
$(MAME_DIR)/src/drivers/cyberbal.c \
$(MAME_DIR)/src/vidhrdw/rampart.c \
$(MAME_DIR)/src/drivers/rampart.c \
$(MAME_DIR)/src/vidhrdw/shuuz.c \
$(MAME_DIR)/src/drivers/shuuz.c \
$(MAME_DIR)/src/vidhrdw/atarig1.c \
$(MAME_DIR)/src/drivers/atarig1.c \
$(MAME_DIR)/src/vidhrdw/thunderj.c \
$(MAME_DIR)/src/drivers/thunderj.c \
$(MAME_DIR)/src/vidhrdw/batman.c \
$(MAME_DIR)/src/drivers/batman.c \
$(MAME_DIR)/src/vidhrdw/relief.c \
$(MAME_DIR)/src/drivers/relief.c \
$(MAME_DIR)/src/vidhrdw/offtwall.c \
$(MAME_DIR)/src/drivers/offtwall.c \
$(MAME_DIR)/src/vidhrdw/arcadecl.c \
$(MAME_DIR)/src/drivers/arcadecl.c \
$(MAME_DIR)/src/vidhrdw/beathead.c \
$(MAME_DIR)/src/drivers/beathead.c \
$(MAME_DIR)/src/vidhrdw/atarig42.c \
$(MAME_DIR)/src/drivers/atarig42.c \
$(MAME_DIR)/src/machine/asic65.c \
$(MAME_DIR)/src/vidhrdw/atarigx2.c \
$(MAME_DIR)/src/drivers/atarigx2.c \
$(MAME_DIR)/src/vidhrdw/atarigt.c \
$(MAME_DIR)/src/drivers/atarigt.c \
$(MAME_DIR)/src/vidhrdw/jaguar.c \
$(MAME_DIR)/src/sndhrdw/jaguar.c \
$(MAME_DIR)/src/drivers/cojag.c \
$(MAME_DIR)/src/sndhrdw/cage.c \
$(MAME_DIR)/src/vidhrdw/rockola.c \
$(MAME_DIR)/src/sndhrdw/rockola.c \
$(MAME_DIR)/src/drivers/rockola.c \
$(MAME_DIR)/src/vidhrdw/lasso.c \
$(MAME_DIR)/src/drivers/lasso.c \
$(MAME_DIR)/src/drivers/munchmo.c \
$(MAME_DIR)/src/vidhrdw/munchmo.c \
$(MAME_DIR)/src/vidhrdw/marvins.c \
$(MAME_DIR)/src/drivers/marvins.c \
$(MAME_DIR)/src/vidhrdw/jcross.c \
$(MAME_DIR)/src/drivers/jcross.c \
$(MAME_DIR)/src/vidhrdw/mainsnk.c \
$(MAME_DIR)/src/drivers/mainsnk.c \
$(MAME_DIR)/src/drivers/hal21.c \
$(MAME_DIR)/src/vidhrdw/snk.c \
$(MAME_DIR)/src/drivers/snk.c \
$(MAME_DIR)/src/drivers/sgladiat.c \
$(MAME_DIR)/src/vidhrdw/snk68.c \
$(MAME_DIR)/src/drivers/snk68.c \
$(MAME_DIR)/src/vidhrdw/prehisle.c \
$(MAME_DIR)/src/drivers/prehisle.c \
$(MAME_DIR)/src/vidhrdw/bbusters.c \
$(MAME_DIR)/src/drivers/bbusters.c \
$(MAME_DIR)/src/drivers/shougi.c \
$(MAME_DIR)/src/machine/equites.c \
$(MAME_DIR)/src/vidhrdw/equites.c \
$(MAME_DIR)/src/drivers/equites.c \
$(MAME_DIR)/src/vidhrdw/alpha68k.c \
$(MAME_DIR)/src/drivers/alpha68k.c \
$(MAME_DIR)/src/vidhrdw/champbas.c \
$(MAME_DIR)/src/drivers/champbas.c \
$(MAME_DIR)/src/machine/exctsccr.c \
$(MAME_DIR)/src/vidhrdw/exctsccr.c \
$(MAME_DIR)/src/drivers/exctsccr.c \
$(MAME_DIR)/src/drivers/scregg.c \
$(MAME_DIR)/src/vidhrdw/tagteam.c \
$(MAME_DIR)/src/drivers/tagteam.c \
$(MAME_DIR)/src/vidhrdw/ssozumo.c \
$(MAME_DIR)/src/drivers/ssozumo.c \
$(MAME_DIR)/src/vidhrdw/mystston.c \
$(MAME_DIR)/src/drivers/mystston.c \
$(MAME_DIR)/src/vidhrdw/dogfgt.c \
$(MAME_DIR)/src/drivers/dogfgt.c \
$(MAME_DIR)/src/vidhrdw/bogeyman.c \
$(MAME_DIR)/src/drivers/bogeyman.c \
$(MAME_DIR)/src/vidhrdw/matmania.c \
$(MAME_DIR)/src/drivers/matmania.c \
$(MAME_DIR)/src/machine/maniach.c \
$(MAME_DIR)/src/vidhrdw/renegade.c \
$(MAME_DIR)/src/drivers/renegade.c \
$(MAME_DIR)/src/vidhrdw/xain.c \
$(MAME_DIR)/src/drivers/xain.c \
$(MAME_DIR)/src/vidhrdw/battlane.c \
$(MAME_DIR)/src/drivers/battlane.c \
$(MAME_DIR)/src/vidhrdw/ddragon.c \
$(MAME_DIR)/src/drivers/ddragon.c \
$(MAME_DIR)/src/drivers/chinagat.c \
$(MAME_DIR)/src/vidhrdw/spdodgeb.c \
$(MAME_DIR)/src/drivers/spdodgeb.c \
$(MAME_DIR)/src/vidhrdw/wwfsstar.c \
$(MAME_DIR)/src/drivers/wwfsstar.c \
$(MAME_DIR)/src/vidhrdw/vball.c \
$(MAME_DIR)/src/drivers/vball.c \
$(MAME_DIR)/src/vidhrdw/blockout.c \
$(MAME_DIR)/src/vidhrdw/ddragon3.c \
$(MAME_DIR)/src/drivers/blockout.c \
$(MAME_DIR)/src/drivers/ddragon3.c \
$(MAME_DIR)/src/vidhrdw/wwfwfest.c \
$(MAME_DIR)/src/drivers/wwfwfest.c \
$(MAME_DIR)/src/vidhrdw/shadfrce.c \
$(MAME_DIR)/src/drivers/shadfrce.c \
$(MAME_DIR)/src/machine/berzerk.c \
$(MAME_DIR)/src/vidhrdw/berzerk.c \
$(MAME_DIR)/src/sndhrdw/berzerk.c \
$(MAME_DIR)/src/drivers/berzerk.c \
$(MAME_DIR)/src/drivers/mazerbla.c \
$(MAME_DIR)/src/drivers/supdrapo.c \
$(MAME_DIR)/src/drivers/toratora.c \
$(MAME_DIR)/src/vidhrdw/gameplan.c \
$(MAME_DIR)/src/drivers/gameplan.c \
$(MAME_DIR)/src/vidhrdw/zac2650.c \
$(MAME_DIR)/src/drivers/zac2650.c \
$(MAME_DIR)/src/vidhrdw/zaccaria.c \
$(MAME_DIR)/src/drivers/zaccaria.c \
$(MAME_DIR)/src/vidhrdw/mouser.c \
$(MAME_DIR)/src/drivers/mouser.c \
$(MAME_DIR)/src/vidhrdw/nova2001.c \
$(MAME_DIR)/src/drivers/nova2001.c \
$(MAME_DIR)/src/vidhrdw/ninjakid.c \
$(MAME_DIR)/src/drivers/ninjakid.c \
$(MAME_DIR)/src/vidhrdw/raiders5.c \
$(MAME_DIR)/src/drivers/raiders5.c \
$(MAME_DIR)/src/vidhrdw/pkunwar.c \
$(MAME_DIR)/src/drivers/pkunwar.c \
$(MAME_DIR)/src/vidhrdw/xxmissio.c \
$(MAME_DIR)/src/drivers/xxmissio.c \
$(MAME_DIR)/src/vidhrdw/ninjakd2.c \
$(MAME_DIR)/src/drivers/ninjakd2.c \
$(MAME_DIR)/src/vidhrdw/mnight.c \
$(MAME_DIR)/src/drivers/mnight.c \
$(MAME_DIR)/src/vidhrdw/omegaf.c \
$(MAME_DIR)/src/drivers/omegaf.c \
$(MAME_DIR)/src/vidhrdw/nmk16.c \
$(MAME_DIR)/src/drivers/nmk16.c \
$(MAME_DIR)/src/drivers/jalmah.c \
$(MAME_DIR)/src/drivers/quizpani.c \
$(MAME_DIR)/src/vidhrdw/quizpani.c \
$(MAME_DIR)/src/vidhrdw/macrossp.c \
$(MAME_DIR)/src/drivers/macrossp.c \
$(MAME_DIR)/src/vidhrdw/quizdna.c \
$(MAME_DIR)/src/drivers/quizdna.c \
$(MAME_DIR)/src/vidhrdw/jack.c \
$(MAME_DIR)/src/drivers/jack.c \
$(MAME_DIR)/src/drivers/embargo.c \
$(MAME_DIR)/src/sndhrdw/cinemat.c \
$(MAME_DIR)/src/drivers/cinemat.c \
$(MAME_DIR)/src/machine/cchasm.c \
$(MAME_DIR)/src/vidhrdw/cchasm.c \
$(MAME_DIR)/src/sndhrdw/cchasm.c \
$(MAME_DIR)/src/drivers/cchasm.c \
$(MAME_DIR)/src/vidhrdw/thepit.c \
$(MAME_DIR)/src/drivers/thepit.c \
$(MAME_DIR)/src/vidhrdw/timelimt.c \
$(MAME_DIR)/src/drivers/timelimt.c \
$(MAME_DIR)/src/machine/bagman.c \
$(MAME_DIR)/src/vidhrdw/bagman.c \
$(MAME_DIR)/src/drivers/bagman.c \
$(MAME_DIR)/src/vidhrdw/tankbust.c \
$(MAME_DIR)/src/drivers/tankbust.c \
$(MAME_DIR)/src/vidhrdw/wiz.c \
$(MAME_DIR)/src/drivers/wiz.c \
$(MAME_DIR)/src/vidhrdw/kncljoe.c \
$(MAME_DIR)/src/drivers/kncljoe.c \
$(MAME_DIR)/src/machine/stfight.c \
$(MAME_DIR)/src/vidhrdw/stfight.c \
$(MAME_DIR)/src/drivers/stfight.c \
$(MAME_DIR)/src/drivers/cshooter.c \
$(MAME_DIR)/src/sndhrdw/seibu.c \
$(MAME_DIR)/src/vidhrdw/deadang.c \
$(MAME_DIR)/src/drivers/deadang.c \
$(MAME_DIR)/src/vidhrdw/dynduke.c \
$(MAME_DIR)/src/drivers/dynduke.c \
$(MAME_DIR)/src/vidhrdw/raiden.c \
$(MAME_DIR)/src/drivers/raiden.c \
$(MAME_DIR)/src/drivers/raiden2.c \
$(MAME_DIR)/src/vidhrdw/dcon.c \
$(MAME_DIR)/src/drivers/dcon.c \
$(MAME_DIR)/src/vidhrdw/sengokmj.c \
$(MAME_DIR)/src/drivers/sengokmj.c \
$(MAME_DIR)/src/vidhrdw/mustache.c \
$(MAME_DIR)/src/drivers/mustache.c \
$(MAME_DIR)/src/vidhrdw/cabal.c \
$(MAME_DIR)/src/drivers/cabal.c \
$(MAME_DIR)/src/vidhrdw/toki.c \
$(MAME_DIR)/src/drivers/toki.c \
$(MAME_DIR)/src/vidhrdw/bloodbro.c \
$(MAME_DIR)/src/drivers/bloodbro.c \
$(MAME_DIR)/src/vidhrdw/legionna.c \
$(MAME_DIR)/src/drivers/legionna.c \
$(MAME_DIR)/src/vidhrdw/goal92.c \
$(MAME_DIR)/src/drivers/goal92.c \
$(MAME_DIR)/src/vidhrdw/exerion.c \
$(MAME_DIR)/src/drivers/exerion.c \
$(MAME_DIR)/src/drivers/fcombat.c \
$(MAME_DIR)/src/vidhrdw/aeroboto.c \
$(MAME_DIR)/src/drivers/aeroboto.c \
$(MAME_DIR)/src/vidhrdw/citycon.c \
$(MAME_DIR)/src/drivers/citycon.c \
$(MAME_DIR)/src/vidhrdw/momoko.c \
$(MAME_DIR)/src/drivers/momoko.c \
$(MAME_DIR)/src/vidhrdw/argus.c \
$(MAME_DIR)/src/drivers/argus.c \
$(MAME_DIR)/src/vidhrdw/psychic5.c \
$(MAME_DIR)/src/drivers/psychic5.c \
$(MAME_DIR)/src/vidhrdw/ginganin.c \
$(MAME_DIR)/src/drivers/ginganin.c \
$(MAME_DIR)/src/vidhrdw/skyfox.c \
$(MAME_DIR)/src/drivers/skyfox.c \
$(MAME_DIR)/src/vidhrdw/homerun.c \
$(MAME_DIR)/src/drivers/homerun.c \
$(MAME_DIR)/src/vidhrdw/cischeat.c \
$(MAME_DIR)/src/drivers/cischeat.c \
$(MAME_DIR)/src/vidhrdw/tetrisp2.c \
$(MAME_DIR)/src/drivers/tetrisp2.c \
$(MAME_DIR)/src/vidhrdw/megasys1.c \
$(MAME_DIR)/src/drivers/megasys1.c \
$(MAME_DIR)/src/vidhrdw/ms32.c \
$(MAME_DIR)/src/drivers/ms32.c \
$(MAME_DIR)/src/vidhrdw/bigstrkb.c \
$(MAME_DIR)/src/drivers/bigstrkb.c \
$(MAME_DIR)/src/vidhrdw/rpunch.c \
$(MAME_DIR)/src/drivers/rpunch.c \
$(MAME_DIR)/src/vidhrdw/tail2nos.c \
$(MAME_DIR)/src/drivers/tail2nos.c \
$(MAME_DIR)/src/vidhrdw/ojankohs.c \
$(MAME_DIR)/src/drivers/ojankohs.c \
$(MAME_DIR)/src/vidhrdw/fromance.c \
$(MAME_DIR)/src/drivers/fromance.c \
$(MAME_DIR)/src/drivers/pipedrm.c \
$(MAME_DIR)/src/vidhrdw/aerofgt.c \
$(MAME_DIR)/src/drivers/aerofgt.c \
$(MAME_DIR)/src/vidhrdw/welltris.c \
$(MAME_DIR)/src/drivers/welltris.c \
$(MAME_DIR)/src/vidhrdw/f1gp.c \
$(MAME_DIR)/src/drivers/f1gp.c \
$(MAME_DIR)/src/vidhrdw/taotaido.c \
$(MAME_DIR)/src/drivers/taotaido.c \
$(MAME_DIR)/src/vidhrdw/crshrace.c \
$(MAME_DIR)/src/drivers/crshrace.c \
$(MAME_DIR)/src/vidhrdw/gstriker.c \
$(MAME_DIR)/src/drivers/gstriker.c \
$(MAME_DIR)/src/vidhrdw/suprslam.c \
$(MAME_DIR)/src/drivers/suprslam.c \
$(MAME_DIR)/src/vidhrdw/fromanc2.c \
$(MAME_DIR)/src/drivers/fromanc2.c \
$(MAME_DIR)/src/vidhrdw/inufuku.c \
$(MAME_DIR)/src/drivers/inufuku.c \
$(MAME_DIR)/src/vidhrdw/psikyo.c \
$(MAME_DIR)/src/drivers/psikyo.c \
$(MAME_DIR)/src/vidhrdw/psikyosh.c \
$(MAME_DIR)/src/drivers/psikyosh.c \
$(MAME_DIR)/src/vidhrdw/psikyo4.c \
$(MAME_DIR)/src/drivers/psikyo4.c \
$(MAME_DIR)/src/machine/8254pit.c \
$(MAME_DIR)/src/drivers/leland.c \
$(MAME_DIR)/src/vidhrdw/leland.c \
$(MAME_DIR)/src/machine/leland.c \
$(MAME_DIR)/src/sndhrdw/leland.c \
$(MAME_DIR)/src/drivers/ataxx.c \
$(MAME_DIR)/src/vidhrdw/marineb.c \
$(MAME_DIR)/src/drivers/marineb.c \
$(MAME_DIR)/src/vidhrdw/funkybee.c \
$(MAME_DIR)/src/drivers/funkybee.c \
$(MAME_DIR)/src/vidhrdw/zodiack.c \
$(MAME_DIR)/src/drivers/zodiack.c \
$(MAME_DIR)/src/vidhrdw/espial.c \
$(MAME_DIR)/src/drivers/espial.c \
$(MAME_DIR)/src/vidhrdw/vastar.c \
$(MAME_DIR)/src/drivers/vastar.c \
$(MAME_DIR)/src/vidhrdw/xorworld.c \
$(MAME_DIR)/src/drivers/xorworld.c \
$(MAME_DIR)/src/vidhrdw/splash.c \
$(MAME_DIR)/src/drivers/splash.c \
$(MAME_DIR)/src/vidhrdw/thoop2.c \
$(MAME_DIR)/src/drivers/thoop2.c \
$(MAME_DIR)/src/vidhrdw/gaelco.c \
$(MAME_DIR)/src/drivers/gaelco.c \
$(MAME_DIR)/src/machine/wrally.c \
$(MAME_DIR)/src/vidhrdw/wrally.c \
$(MAME_DIR)/src/drivers/wrally.c \
$(MAME_DIR)/src/vidhrdw/targeth.c \
$(MAME_DIR)/src/drivers/targeth.c \
$(MAME_DIR)/src/machine/gaelco2.c \
$(MAME_DIR)/src/vidhrdw/gaelco2.c \
$(MAME_DIR)/src/drivers/gaelco2.c \
$(MAME_DIR)/src/vidhrdw/glass.c \
$(MAME_DIR)/src/drivers/glass.c \
$(MAME_DIR)/src/vidhrdw/airbustr.c \
$(MAME_DIR)/src/drivers/airbustr.c \
$(MAME_DIR)/src/vidhrdw/djboy.c \
$(MAME_DIR)/src/drivers/djboy.c \
$(MAME_DIR)/src/vidhrdw/galpanic.c \
$(MAME_DIR)/src/drivers/galpanic.c \
$(MAME_DIR)/src/vidhrdw/galpani2.c \
$(MAME_DIR)/src/drivers/galpani2.c \
$(MAME_DIR)/src/drivers/jchan.c \
$(MAME_DIR)/src/vidhrdw/kaneko16.c \
$(MAME_DIR)/src/drivers/kaneko16.c \
$(MAME_DIR)/src/vidhrdw/suprnova.c \
$(MAME_DIR)/src/drivers/suprnova.c \
$(MAME_DIR)/src/machine/neogeo.c \
$(MAME_DIR)/src/machine/pd4990a.c \
$(MAME_DIR)/src/machine/neocrypt.c \
$(MAME_DIR)/src/vidhrdw/neogeo.c \
$(MAME_DIR)/src/drivers/neogeo.c \
$(MAME_DIR)/src/vidhrdw/hanaawas.c \
$(MAME_DIR)/src/drivers/hanaawas.c \
$(MAME_DIR)/src/vidhrdw/speedatk.c \
$(MAME_DIR)/src/drivers/speedatk.c \
$(MAME_DIR)/src/vidhrdw/srmp2.c \
$(MAME_DIR)/src/drivers/srmp2.c \
$(MAME_DIR)/src/vidhrdw/seta.c \
$(MAME_DIR)/src/drivers/seta.c \
$(MAME_DIR)/src/vidhrdw/seta2.c \
$(MAME_DIR)/src/drivers/seta2.c \
$(MAME_DIR)/src/vidhrdw/ssv.c \
$(MAME_DIR)/src/drivers/ssv.c \
$(MAME_DIR)/src/vidhrdw/powerins.c \
$(MAME_DIR)/src/drivers/powerins.c \
$(MAME_DIR)/src/vidhrdw/ohmygod.c \
$(MAME_DIR)/src/drivers/ohmygod.c \
$(MAME_DIR)/src/vidhrdw/blmbycar.c \
$(MAME_DIR)/src/drivers/blmbycar.c \
$(MAME_DIR)/src/vidhrdw/route16.c \
$(MAME_DIR)/src/drivers/route16.c \
$(MAME_DIR)/src/vidhrdw/ttmahjng.c \
$(MAME_DIR)/src/drivers/ttmahjng.c \
$(MAME_DIR)/src/vidhrdw/kangaroo.c \
$(MAME_DIR)/src/drivers/kangaroo.c \
$(MAME_DIR)/src/vidhrdw/arabian.c \
$(MAME_DIR)/src/drivers/arabian.c \
$(MAME_DIR)/src/vidhrdw/markham.c \
$(MAME_DIR)/src/drivers/markham.c \
$(MAME_DIR)/src/vidhrdw/strnskil.c \
$(MAME_DIR)/src/drivers/strnskil.c \
$(MAME_DIR)/src/vidhrdw/ikki.c \
$(MAME_DIR)/src/drivers/ikki.c \
$(MAME_DIR)/src/drivers/shanghai.c \
$(MAME_DIR)/src/vidhrdw/shangha3.c \
$(MAME_DIR)/src/drivers/shangha3.c \
$(MAME_DIR)/src/vidhrdw/goindol.c \
$(MAME_DIR)/src/drivers/goindol.c \
$(MAME_DIR)/src/vidhrdw/suna8.c \
$(MAME_DIR)/src/drivers/suna8.c \
$(MAME_DIR)/src/vidhrdw/suna16.c \
$(MAME_DIR)/src/drivers/suna16.c \
$(MAME_DIR)/src/vidhrdw/gundealr.c \
$(MAME_DIR)/src/drivers/gundealr.c \
$(MAME_DIR)/src/vidhrdw/dooyong.c \
$(MAME_DIR)/src/drivers/dooyong.c \
$(MAME_DIR)/src/machine/leprechn.c \
$(MAME_DIR)/src/vidhrdw/leprechn.c \
$(MAME_DIR)/src/drivers/leprechn.c \
$(MAME_DIR)/src/machine/beezer.c \
$(MAME_DIR)/src/vidhrdw/beezer.c \
$(MAME_DIR)/src/drivers/beezer.c \
$(MAME_DIR)/src/vidhrdw/pushman.c \
$(MAME_DIR)/src/drivers/pushman.c \
$(MAME_DIR)/src/vidhrdw/zerozone.c \
$(MAME_DIR)/src/drivers/zerozone.c \
$(MAME_DIR)/src/vidhrdw/galspnbl.c \
$(MAME_DIR)/src/drivers/galspnbl.c \
$(MAME_DIR)/src/vidhrdw/sslam.c \
$(MAME_DIR)/src/drivers/sslam.c \
$(MAME_DIR)/src/vidhrdw/playmark.c \
$(MAME_DIR)/src/drivers/playmark.c \
$(MAME_DIR)/src/vidhrdw/thief.c \
$(MAME_DIR)/src/drivers/thief.c \
$(MAME_DIR)/src/vidhrdw/mrflea.c \
$(MAME_DIR)/src/drivers/mrflea.c \
$(MAME_DIR)/src/vidhrdw/holeland.c \
$(MAME_DIR)/src/drivers/holeland.c \
$(MAME_DIR)/src/vidhrdw/speedbal.c \
$(MAME_DIR)/src/drivers/speedbal.c \
$(MAME_DIR)/src/vidhrdw/sauro.c \
$(MAME_DIR)/src/drivers/sauro.c \
$(MAME_DIR)/src/vidhrdw/metro.c \
$(MAME_DIR)/src/drivers/metro.c \
$(MAME_DIR)/src/vidhrdw/hyprduel.c \
$(MAME_DIR)/src/drivers/hyprduel.c \
$(MAME_DIR)/src/vidhrdw/spcforce.c \
$(MAME_DIR)/src/drivers/spcforce.c \
$(MAME_DIR)/src/drivers/looping.c \
$(MAME_DIR)/src/vidhrdw/paradise.c \
$(MAME_DIR)/src/drivers/paradise.c \
$(MAME_DIR)/src/vidhrdw/yunsung8.c \
$(MAME_DIR)/src/drivers/yunsung8.c \
$(MAME_DIR)/src/vidhrdw/yunsun16.c \
$(MAME_DIR)/src/drivers/yunsun16.c \
$(MAME_DIR)/src/vidhrdw/blueprnt.c \
$(MAME_DIR)/src/drivers/blueprnt.c \
$(MAME_DIR)/src/vidhrdw/fuukifg2.c \
$(MAME_DIR)/src/drivers/fuukifg2.c \
$(MAME_DIR)/src/vidhrdw/fuukifg3.c \
$(MAME_DIR)/src/drivers/fuukifg3.c \
$(MAME_DIR)/src/vidhrdw/drgnmst.c \
$(MAME_DIR)/src/drivers/drgnmst.c \
$(MAME_DIR)/src/vidhrdw/unico.c \
$(MAME_DIR)/src/drivers/unico.c \
$(MAME_DIR)/src/vidhrdw/silkroad.c \
$(MAME_DIR)/src/drivers/silkroad.c \
$(MAME_DIR)/src/vidhrdw/afega.c \
$(MAME_DIR)/src/drivers/afega.c \
$(MAME_DIR)/src/vidhrdw/esd16.c \
$(MAME_DIR)/src/drivers/esd16.c \
$(MAME_DIR)/src/drivers/royalmah.c \
$(MAME_DIR)/src/vidhrdw/hnayayoi.c \
$(MAME_DIR)/src/drivers/hnayayoi.c \
$(MAME_DIR)/src/vidhrdw/dynax.c \
$(MAME_DIR)/src/drivers/dynax.c \
$(MAME_DIR)/src/drivers/ddenlovr.c \
$(MAME_DIR)/src/drivers/realbrk.c \
$(MAME_DIR)/src/vidhrdw/realbrk.c \
$(MAME_DIR)/src/vidhrdw/crtc6845.c \
$(MAME_DIR)/src/vidhrdw/nyny.c \
$(MAME_DIR)/src/drivers/nyny.c \
$(MAME_DIR)/src/drivers/r2dtank.c \
$(MAME_DIR)/src/machine/spiders.c \
$(MAME_DIR)/src/vidhrdw/spiders.c \
$(MAME_DIR)/src/drivers/spiders.c \
$(MAME_DIR)/src/vidhrdw/iqblock.c \
$(MAME_DIR)/src/drivers/iqblock.c \
$(MAME_DIR)/src/drivers/chindrag.c \
$(MAME_DIR)/src/drivers/grtwall.c \
$(MAME_DIR)/src/vidhrdw/pgm.c \
$(MAME_DIR)/src/drivers/pgm.c \
$(MAME_DIR)/src/machine/pgmprot.c \
$(MAME_DIR)/src/machine/pgmcrypt.c \
$(MAME_DIR)/src/vidhrdw/hitme.c \
$(MAME_DIR)/src/drivers/hitme.c \
$(MAME_DIR)/src/vidhrdw/starcrus.c \
$(MAME_DIR)/src/drivers/starcrus.c \
$(MAME_DIR)/src/vidhrdw/battlex.c \
$(MAME_DIR)/src/drivers/battlex.c \
$(MAME_DIR)/src/vidhrdw/carjmbre.c \
$(MAME_DIR)/src/drivers/carjmbre.c \
$(MAME_DIR)/src/vidhrdw/popper.c \
$(MAME_DIR)/src/drivers/popper.c \
$(MAME_DIR)/src/vidhrdw/speedspn.c \
$(MAME_DIR)/src/drivers/speedspn.c \
$(MAME_DIR)/src/vidhrdw/kickgoal.c \
$(MAME_DIR)/src/drivers/kickgoal.c \
$(MAME_DIR)/src/vidhrdw/usgames.c \
$(MAME_DIR)/src/drivers/usgames.c \
$(MAME_DIR)/src/vidhrdw/mermaid.c \
$(MAME_DIR)/src/drivers/mermaid.c \
$(MAME_DIR)/src/vidhrdw/drmicro.c \
$(MAME_DIR)/src/drivers/drmicro.c \
$(MAME_DIR)/src/vidhrdw/appoooh.c \
$(MAME_DIR)/src/drivers/appoooh.c \
$(MAME_DIR)/src/vidhrdw/bankp.c \
$(MAME_DIR)/src/drivers/bankp.c \
$(MAME_DIR)/src/vidhrdw/mjkjidai.c \
$(MAME_DIR)/src/drivers/mjkjidai.c \
$(MAME_DIR)/src/vidhrdw/mayumi.c \
$(MAME_DIR)/src/drivers/mayumi.c \
$(MAME_DIR)/src/vidhrdw/btoads.c \
$(MAME_DIR)/src/drivers/btoads.c \
$(MAME_DIR)/src/vidhrdw/kinst.c \
$(MAME_DIR)/src/drivers/kinst.c \
$(MAME_DIR)/src/vidhrdw/freekick.c \
$(MAME_DIR)/src/drivers/freekick.c \
$(MAME_DIR)/src/drivers/rmhaihai.c \
$(MAME_DIR)/src/drivers/hanaroku.c \
$(MAME_DIR)/src/drivers/yumefuda.c \
$(MAME_DIR)/src/vidhrdw/homedata.c \
$(MAME_DIR)/src/drivers/homedata.c \
$(MAME_DIR)/src/vidhrdw/artmagic.c \
$(MAME_DIR)/src/drivers/artmagic.c \
$(MAME_DIR)/src/vidhrdw/shangkid.c \
$(MAME_DIR)/src/drivers/shangkid.c \
$(MAME_DIR)/src/vidhrdw/astinvad.c \
$(MAME_DIR)/src/sndhrdw/astinvad.c \
$(MAME_DIR)/src/drivers/astinvad.c \
$(MAME_DIR)/src/vidhrdw/spacefb.c \
$(MAME_DIR)/src/drivers/spacefb.c \
$(MAME_DIR)/src/drivers/omegrace.c \
$(MAME_DIR)/src/vidhrdw/dday.c \
$(MAME_DIR)/src/drivers/dday.c \
$(MAME_DIR)/src/vidhrdw/hexa.c \
$(MAME_DIR)/src/drivers/hexa.c \
$(MAME_DIR)/src/vidhrdw/redalert.c \
$(MAME_DIR)/src/sndhrdw/redalert.c \
$(MAME_DIR)/src/drivers/redalert.c \
$(MAME_DIR)/src/machine/stactics.c \
$(MAME_DIR)/src/vidhrdw/stactics.c \
$(MAME_DIR)/src/drivers/stactics.c \
$(MAME_DIR)/src/vidhrdw/kingobox.c \
$(MAME_DIR)/src/drivers/kingobox.c \
$(MAME_DIR)/src/vidhrdw/ambush.c \
$(MAME_DIR)/src/drivers/ambush.c \
$(MAME_DIR)/src/drivers/dlair.c \
$(MAME_DIR)/src/vidhrdw/aztarac.c \
$(MAME_DIR)/src/sndhrdw/aztarac.c \
$(MAME_DIR)/src/drivers/aztarac.c \
$(MAME_DIR)/src/vidhrdw/mole.c \
$(MAME_DIR)/src/drivers/mole.c \
$(MAME_DIR)/src/vidhrdw/gotya.c \
$(MAME_DIR)/src/sndhrdw/gotya.c \
$(MAME_DIR)/src/drivers/gotya.c \
$(MAME_DIR)/src/vidhrdw/mrjong.c \
$(MAME_DIR)/src/drivers/mrjong.c \
$(MAME_DIR)/src/vidhrdw/polyplay.c \
$(MAME_DIR)/src/sndhrdw/polyplay.c \
$(MAME_DIR)/src/drivers/polyplay.c \
$(MAME_DIR)/src/vidhrdw/amspdwy.c \
$(MAME_DIR)/src/drivers/amspdwy.c \
$(MAME_DIR)/src/vidhrdw/othldrby.c \
$(MAME_DIR)/src/drivers/othldrby.c \
$(MAME_DIR)/src/vidhrdw/mosaic.c \
$(MAME_DIR)/src/drivers/mosaic.c \
$(MAME_DIR)/src/drivers/spdbuggy.c \
$(MAME_DIR)/src/vidhrdw/sprcros2.c \
$(MAME_DIR)/src/drivers/sprcros2.c \
$(MAME_DIR)/src/vidhrdw/mugsmash.c \
$(MAME_DIR)/src/drivers/mugsmash.c \
$(MAME_DIR)/src/vidhrdw/stlforce.c \
$(MAME_DIR)/src/drivers/stlforce.c \
$(MAME_DIR)/src/vidhrdw/gcpinbal.c \
$(MAME_DIR)/src/drivers/gcpinbal.c \
$(MAME_DIR)/src/vidhrdw/aquarium.c \
$(MAME_DIR)/src/drivers/aquarium.c \
$(MAME_DIR)/src/vidhrdw/policetr.c \
$(MAME_DIR)/src/drivers/policetr.c \
$(MAME_DIR)/src/vidhrdw/pass.c \
$(MAME_DIR)/src/drivers/pass.c \
$(MAME_DIR)/src/vidhrdw/news.c \
$(MAME_DIR)/src/drivers/news.c \
$(MAME_DIR)/src/vidhrdw/taxidrvr.c \
$(MAME_DIR)/src/drivers/taxidrvr.c \
$(MAME_DIR)/src/vidhrdw/xyonix.c \
$(MAME_DIR)/src/drivers/xyonix.c \
$(MAME_DIR)/src/drivers/findout.c \
$(MAME_DIR)/src/vidhrdw/dribling.c \
$(MAME_DIR)/src/drivers/dribling.c \
$(MAME_DIR)/src/drivers/ace.c \
$(MAME_DIR)/src/vidhrdw/clayshoo.c \
$(MAME_DIR)/src/machine/clayshoo.c \
$(MAME_DIR)/src/drivers/clayshoo.c \
$(MAME_DIR)/src/vidhrdw/pirates.c \
$(MAME_DIR)/src/drivers/pirates.c \
$(MAME_DIR)/src/vidhrdw/fitfight.c \
$(MAME_DIR)/src/drivers/fitfight.c \
$(MAME_DIR)/src/vidhrdw/flower.c \
$(MAME_DIR)/src/sndhrdw/flower.c \
$(MAME_DIR)/src/drivers/flower.c \
$(MAME_DIR)/src/vidhrdw/diverboy.c \
$(MAME_DIR)/src/drivers/diverboy.c \
$(MAME_DIR)/src/vidhrdw/beaminv.c \
$(MAME_DIR)/src/drivers/beaminv.c \
$(MAME_DIR)/src/vidhrdw/mcatadv.c \
$(MAME_DIR)/src/drivers/mcatadv.c \
$(MAME_DIR)/src/vidhrdw/4enraya.c \
$(MAME_DIR)/src/drivers/4enraya.c \
$(MAME_DIR)/src/vidhrdw/oneshot.c \
$(MAME_DIR)/src/drivers/oneshot.c \
$(MAME_DIR)/src/drivers/tugboat.c \
$(MAME_DIR)/src/vidhrdw/gotcha.c \
$(MAME_DIR)/src/drivers/gotcha.c \
$(MAME_DIR)/src/drivers/coolpool.c \
$(MAME_DIR)/src/vidhrdw/gumbo.c \
$(MAME_DIR)/src/drivers/gumbo.c \
$(MAME_DIR)/src/drivers/statriv2.c \
$(MAME_DIR)/src/vidhrdw/tickee.c \
$(MAME_DIR)/src/drivers/tickee.c \
$(MAME_DIR)/src/vidhrdw/crgolf.c \
$(MAME_DIR)/src/drivers/crgolf.c \
$(MAME_DIR)/src/vidhrdw/truco.c \
$(MAME_DIR)/src/drivers/truco.c \
$(MAME_DIR)/src/vidhrdw/thedeep.c \
$(MAME_DIR)/src/drivers/thedeep.c \
$(MAME_DIR)/src/vidhrdw/fantland.c \
$(MAME_DIR)/src/drivers/fantland.c \
$(MAME_DIR)/src/drivers/wallc.c \
$(MAME_DIR)/src/drivers/skyarmy.c \
$(MAME_DIR)/src/vidhrdw/lethalj.c \
$(MAME_DIR)/src/drivers/lethalj.c \
$(MAME_DIR)/src/vidhrdw/sbugger.c \
$(MAME_DIR)/src/drivers/sbugger.c \
$(MAME_DIR)/src/vidhrdw/portrait.c \
$(MAME_DIR)/src/drivers/portrait.c \
$(MAME_DIR)/src/drivers/enigma2.c \
$(MAME_DIR)/src/drivers/ltcasino.c \
$(MAME_DIR)/src/drivers/vamphalf.c \
$(MAME_DIR)/src/drivers/strvmstr.c \
$(MAME_DIR)/src/vidhrdw/dorachan.c \
$(MAME_DIR)/src/drivers/dorachan.c \
$(MAME_DIR)/src/vidhrdw/ladyfrog.c \
$(MAME_DIR)/src/drivers/ladyfrog.c \
$(MAME_DIR)/src/drivers/rabbit.c \
$(MAME_DIR)/src/drivers/malzak.c \
$(MAME_DIR)/src/vidhrdw/malzak.c \
$(MAME_DIR)/src/drivers/supertnk.c \
$(MAME_DIR)/src/drivers/crospang.c \
$(MAME_DIR)/src/drivers/funybubl.c \
$(MAME_DIR)/src/driver.c \
$(MAME_DIR)/src/cheat.c \
$(MAME_DIR)/src/libretro/libretro.c \
$(MAME_DIR)/src/libretro/osd.c \
$(MAME_DIR)/src/libretro/keyboard.c \
$(MAME_DIR)/src/libretro/joystick.c \
$(MAME_DIR)/src/libretro/video.c

LOCAL_SRC_FILES    = $(SOURCES)
HAS_CPUS := -DHAS_Z80=1 \
-DHAS_Z180=1 \
-DHAS_8080=1 \
-DHAS_8085A=1 \
-DHAS_M6502=1 \
-DHAS_M65C02=1 \
-DHAS_M65SC02=1 \
-DHAS_M6509=1 \
-DHAS_M6510=1 \
-DHAS_M6510T=1 \
-DHAS_M7501=1 \
-DHAS_M8502=1 \
-DHAS_N2A03=1 \
-DHAS_DECO16=1 \
-DHAS_M4510=1 \
-DHAS_H6280=1 \
-DHAS_I86=1 \
-DHAS_I88=1 \
-DHAS_I186=1 \
-DHAS_I188=1 \
-DHAS_I286=1 \
-DHAS_V20=1 \
-DHAS_V30=1 \
-DHAS_V33=1 \
-DHAS_V60=1 \
-DHAS_V70=1 \
-DHAS_I8035=1 \
-DHAS_I8039=1 \
-DHAS_I8048=1 \
-DHAS_N7751=1 \
-DHAS_I8X41=1 \
-DHAS_M6800=1 \
-DHAS_M6801=1 \
-DHAS_M6802=1 \
-DHAS_M6803=1 \
-DHAS_M6808=1 \
-DHAS_HD63701=1 \
-DHAS_NSC8105=1 \
-DHAS_M6805=1 \
-DHAS_M68705=1 \
-DHAS_HD63705=1 \
-DHAS_HD6309=1 \
-DHAS_M6809=1 \
-DHAS_KONAMI=1 \
-DHAS_M68000=1 \
-DHAS_M68010=1 \
-DHAS_M68EC020=1 \
-DHAS_M68020=1 \
-DHAS_T11=1 \
-DHAS_S2650=1 \
-DHAS_TMS34010=1 \
-DHAS_TMS34020=1 \
-DHAS_TMS9900=1 \
-DHAS_TMS9940=1 \
-DHAS_TMS9980=1 \
-DHAS_TMS9985=1 \
-DHAS_TMS9989=1 \
-DHAS_TMS9995=1 \
-DHAS_TMS99105A=1 \
-DHAS_Z8000=1 \
-DHAS_TMS32010=1 \
-DHAS_TMS32025=1 \
-DHAS_TMS32031=1 \
-DHAS_CCPU=1 \
-DHAS_ADSP2100=1 \
-DHAS_ADSP2101=1 \
-DHAS_ADSP2104=1 \
-DHAS_ADSP2105=1 \
-DHAS_ADSP2115=1 \
-DHAS_PSXCPU=1 \
-DHAS_ASAP=1 \
-DHAS_UPD7810=1 \
-DHAS_UPD7807=1 \
-DHAS_ARM=1 \
-DHAS_JAGUAR=1 \
-DHAS_R3000=1 \
-DHAS_R4600=1 \
-DHAS_R5000=1 \
-DHAS_SH2=1 \
-DHAS_DSP32C=1 \
-DHAS_PIC16C54=1 \
-DHAS_PIC16C55=1 \
-DHAS_PIC16C56=1 \
-DHAS_PIC16C57=1 \
-DHAS_PIC16C58=1 \
-DHAS_G65816=1 \
-DHAS_SPC700=1 \
-DHAS_E132XS=1 \
-DHAS_CUSTOM=1 \
-DHAS_SAMPLES=1 \
-DHAS_DAC=1 \
-DHAS_DISCRETE=1 \
-DHAS_AY8910=1 \
-DHAS_YM2203=1 \
-DHAS_YM2608=1 \
-DHAS_YM2610=1 \
-DHAS_YM2610B=1 \
-DHAS_YM2612=1 \
-DHAS_YM3438=1 \
-DHAS_YM2413=1 \
-DHAS_YM3812=1 \
-DHAS_YM3526=1 \
-DHAS_YMZ280B=1 \
-DHAS_Y8950=1 \
-DHAS_SN76477=1 \
-DHAS_SN76496=1 \
-DHAS_POKEY=1 \
-DHAS_TIA=1 \
-DHAS_NES=1 \
-DHAS_ASTROCADE=1 \
-DHAS_NAMCO=1 \
-DHAS_NAMCONA=1 \
-DHAS_TMS36XX=1 \
-DHAS_TMS5110=1 \
-DHAS_TMS5220=1 \
-DHAS_VLM5030=1 \
-DHAS_ADPCM=1 \
-DHAS_OKIM6295=1 \
-DHAS_OKIM6295=1 \
-DHAS_MSM5205=1 \
-DHAS_MSM5232=1 \
-DHAS_UPD7759=1 \
-DHAS_HC55516=1 \
-DHAS_K005289=1 \
-DHAS_K007232=1 \
-DHAS_K051649=1 \
-DHAS_K053260=1 \
-DHAS_K054539=1 \
-DHAS_SEGAPCM=1 \
-DHAS_RF5C68=1 \
-DHAS_CEM3394=1 \
-DHAS_C140=1 \
-DHAS_QSOUND=1 \
-DHAS_SAA1099=1 \
-DHAS_IREMGA20=1 \
-DHAS_ES5505=1 \
-DHAS_ES5506=1 \
-DHAS_BSMT2000=1 \
-DHAS_YMF262=1 \
-DHAS_YMF278B=1 \
-DHAS_YM2151_ALT=1 \
-DHAS_GAELCO_CG1V=1 \
-DHAS_GAELCO_GAE1=1 \
-DHAS_X1_010=1 \
-DHAS_MULTIPCM=1 

HAS_CPUS2 = -DHAS_C6280=1 \
-DHAS_SP0250=1 \
-DHAS_SCSP=1 \
-DHAS_PSXSPU=1 \
-DHAS_YMF271=1

LOCAL_CFLAGS = -DINLINE=inline -DHAVE_STDINT_H -DHAVE_INTTYPES_H -D__LIBRETRO__ -DFRONTEND_SUPPORTS_RGB565 $(HAS_CPUS) $(HAS_CPUS2) -DPI=3.1415927

LOCAL_C_INCLUDES = ../ ../../ ../../includes
LOCAL_LDLIBS += -lz

include $(BUILD_SHARED_LIBRARY)
