/**********************************************************
 * mame2003-plus control description data stuctures
 *
 * Originally dervied from
 * controls.dat Version=0.141.1, Time=2011-01-05 18:17:26, Generated by=SirPoonga
 *********************************************************/

#ifndef CONTROLS_H
#define CONTROLS_H

#include "inptport.h"

extern const struct ControlInfo a88games_ctrls;
const char *a88games_get_btn(int type);

extern const struct ControlInfo a005_ctrls;
const char *a005_get_btn(int type);

extern const struct ControlInfo a10yardj_ctrls;
const char *a10yardj_get_btn(int type);

extern const struct ControlInfo gtmr_ctrls;
const char *gtmr_get_btn(int type);

extern const struct ControlInfo a1941_ctrls;
const char *a1941_get_btn(int type);

extern const struct ControlInfo a1942_ctrls;
const char *a1942_get_btn(int type);

extern const struct ControlInfo a1943kai_ctrls;
const char *a1943kai_get_btn(int type);

extern const struct ControlInfo a1943_ctrls;
const char *a1943_get_btn(int type);

extern const struct ControlInfo a1944_ctrls;
const char *a1944_get_btn(int type);

extern const struct ControlInfo a19xx_ctrls;
const char *a19xx_get_btn(int type);

extern const struct ControlInfo openice_ctrls;
const char *openice_get_btn(int type);

extern const struct ControlInfo a39in1_ctrls;
const char *a39in1_get_btn(int type);

extern const struct ControlInfo a4enraya_ctrls;
const char *a4enraya_get_btn(int type);

extern const struct ControlInfo a4in1_ctrls;
const char *a4in1_get_btn(int type);

extern const struct ControlInfo a4dwarrio_ctrls;
const char *a4dwarrio_get_btn(int type);

extern const struct ControlInfo a64street_ctrls;
const char *a64street_get_btn(int type);

extern const struct ControlInfo a720_ctrls;
const char *a720_get_btn(int type);

extern const struct ControlInfo a7jigen_ctrls;
const char *a7jigen_get_btn(int type);

extern const struct ControlInfo ace_ctrls;
const char *ace_get_btn(int type);

extern const struct ControlInfo acrobatm_ctrls;
const char *acrobatm_get_btn(int type);

extern const struct ControlInfo actfancr_ctrls;
const char *actfancr_get_btn(int type);

extern const struct ControlInfo hatena_ctrls;
const char *hatena_get_btn(int type);

extern const struct ControlInfo aerofgt_ctrls;
const char *aerofgt_get_btn(int type);

extern const struct ControlInfo aburner2_ctrls;
const char *aburner2_get_btn(int type);

extern const struct ControlInfo koshien_ctrls;
const char *koshien_get_btn(int type);

extern const struct ControlInfo airbustr_ctrls;
const char *airbustr_get_btn(int type);

extern const struct ControlInfo airduel_ctrls;
const char *airduel_get_btn(int type);

extern const struct ControlInfo airwolf_ctrls;
const char *airwolf_get_btn(int type);

extern const struct ControlInfo ajax_ctrls;
const char *ajax_get_btn(int type);

extern const struct ControlInfo alexkidd_ctrls;
const char *alexkidd_get_btn(int type);

extern const struct ControlInfo alibaba_ctrls;
const char *alibaba_get_btn(int type);

extern const struct ControlInfo astorm_ctrls;
const char *astorm_get_btn(int type);

extern const struct ControlInfo aliensyn_ctrls;
const char *aliensyn_get_btn(int type);

extern const struct ControlInfo avsp_ctrls;
const char *avsp_get_btn(int type);

extern const struct ControlInfo alien3_ctrls;
const char *alien3_get_btn(int type);

extern const struct ControlInfo aliens_ctrls;
const char *aliens_get_btn(int type);

extern const struct ControlInfo aafb_ctrls;
const char *aafb_get_btn(int type);

extern const struct ControlInfo alleymas_ctrls;
const char *alleymas_get_btn(int type);

extern const struct ControlInfo alphaho_ctrls;
const char *alphaho_get_btn(int type);

extern const struct ControlInfo alpinerd_ctrls;
const char *alpinerd_get_btn(int type);

extern const struct ControlInfo alpine_ctrls;
const char *alpine_get_btn(int type);

extern const struct ControlInfo altbeast_ctrls;
const char *altbeast_get_btn(int type);

extern const struct ControlInfo maze_ctrls;
const char *maze_get_btn(int type);

extern const struct ControlInfo horshoes_ctrls;
const char *horshoes_get_btn(int type);

extern const struct ControlInfo amspdwy_ctrls;
const char *amspdwy_get_btn(int type);

extern const struct ControlInfo amerdart_ctrls;
const char *amerdart_get_btn(int type);

extern const struct ControlInfo amidar_ctrls;
const char *amidar_get_btn(int type);

extern const struct ControlInfo angelkds_ctrls;
const char *angelkds_get_btn(int type);

extern const struct ControlInfo anteater_ctrls;
const char *anteater_get_btn(int type);

extern const struct ControlInfo apb_ctrls;
const char *apb_get_btn(int type);

extern const struct ControlInfo apparel_ctrls;
const char *apparel_get_btn(int type);

extern const struct ControlInfo aquajack_ctrls;
const char *aquajack_get_btn(int type);

extern const struct ControlInfo aquarium_ctrls;
const char *aquarium_get_btn(int type);

extern const struct ControlInfo arabian_ctrls;
const char *arabian_get_btn(int type);

extern const struct ControlInfo arbalest_ctrls;
const char *arbalest_get_btn(int type);

extern const struct ControlInfo arcadecl_ctrls;
const char *arcadecl_get_btn(int type);

extern const struct ControlInfo archrivl_ctrls;
const char *archrivl_get_btn(int type);

extern const struct ControlInfo area51_ctrls;
const char *area51_get_btn(int type);

extern const struct ControlInfo area51mx_ctrls;
const char *area51mx_get_btn(int type);

extern const struct ControlInfo a51site4_ctrls;
const char *a51site4_get_btn(int type);

extern const struct ControlInfo argus_ctrls;
const char *argus_get_btn(int type);

extern const struct ControlInfo arkarea_ctrls;
const char *arkarea_get_btn(int type);

extern const struct ControlInfo arkanoid_ctrls;
const char *arkanoid_get_btn(int type);

extern const struct ControlInfo arknoid2_ctrls;
const char *arknoid2_get_btn(int type);

extern const struct ControlInfo arlingtn_ctrls;
const char *arlingtn_get_btn(int type);

extern const struct ControlInfo armwrest_ctrls;
const char *armwrest_get_btn(int type);

extern const struct ControlInfo armedf_ctrls;
const char *armedf_get_btn(int type);

extern const struct ControlInfo armora_ctrls;
const char *armora_get_btn(int type);

extern const struct ControlInfo armorcar_ctrls;
const char *armorcar_get_btn(int type);

extern const struct ControlInfo ashura_ctrls;
const char *ashura_get_btn(int type);

extern const struct ControlInfo aso_ctrls;
const char *aso_get_btn(int type);

extern const struct ControlInfo assault_ctrls;
const char *assault_get_btn(int type);

extern const struct ControlInfo asterix_ctrls;
const char *asterix_get_btn(int type);

extern const struct ControlInfo asteroid_ctrls;
const char *asteroid_get_btn(int type);

extern const struct ControlInfo astdelux_ctrls;
const char *astdelux_get_btn(int type);

extern const struct ControlInfo astrob_ctrls;
const char *astrob_get_btn(int type);

extern const struct ControlInfo astrof_ctrls;
const char *astrof_get_btn(int type);

extern const struct ControlInfo astinvad_ctrls;
const char *astinvad_get_btn(int type);

extern const struct ControlInfo asuka_ctrls;
const char *asuka_get_btn(int type);

extern const struct ControlInfo asylum_ctrls;
const char *asylum_get_btn(int type);

extern const struct ControlInfo abaseb_ctrls;
const char *abaseb_get_btn(int type);

extern const struct ControlInfo atarifb_ctrls;
const char *atarifb_get_btn(int type);

extern const struct ControlInfo ataxx_ctrls;
const char *ataxx_get_btn(int type);

extern const struct ControlInfo athena_ctrls;
const char *athena_get_btn(int type);

extern const struct ControlInfo atehate_ctrls;
const char *atehate_get_btn(int type);

extern const struct ControlInfo atomicp_ctrls;
const char *atomicp_get_btn(int type);

extern const struct ControlInfo robokid_ctrls;
const char *robokid_get_btn(int type);

extern const struct ControlInfo aurail_ctrls;
const char *aurail_get_btn(int type);

extern const struct ControlInfo av2mj1bb_ctrls;
const char *av2mj1bb_get_btn(int type);

extern const struct ControlInfo av2mj2rg_ctrls;
const char *av2mj2rg_get_btn(int type);

extern const struct ControlInfo avalnche_ctrls;
const char *avalnche_get_btn(int type);

extern const struct ControlInfo avengers_ctrls;
const char *avengers_get_btn(int type);

extern const struct ControlInfo avspirit_ctrls;
const char *avspirit_get_btn(int type);

extern const struct ControlInfo aztarac_ctrls;
const char *aztarac_get_btn(int type);

extern const struct ControlInfo azurian_ctrls;
const char *azurian_get_btn(int type);

extern const struct ControlInfo baddudes_ctrls;
const char *baddudes_get_btn(int type);

extern const struct ControlInfo badlands_ctrls;
const char *badlands_get_btn(int type);

extern const struct ControlInfo bagman_ctrls;
const char *bagman_get_btn(int type);

extern const struct ControlInfo bkrtmaq_ctrls;
const char *bkrtmaq_get_btn(int type);

extern const struct ControlInfo bakutotu_ctrls;
const char *bakutotu_get_btn(int type);

extern const struct ControlInfo ballbomb_ctrls;
const char *ballbomb_get_btn(int type);

extern const struct ControlInfo ballbros_ctrls;
const char *ballbros_get_btn(int type);

extern const struct ControlInfo baluba_ctrls;
const char *baluba_get_btn(int type);

extern const struct ControlInfo bangball_ctrls;
const char *bangball_get_btn(int type);

extern const struct ControlInfo bang_ctrls;
const char *bang_get_btn(int type);

extern const struct ControlInfo bankp_ctrls;
const char *bankp_get_btn(int type);

extern const struct ControlInfo baraduke_ctrls;
const char *baraduke_get_btn(int type);

extern const struct ControlInfo barricad_ctrls;
const char *barricad_get_btn(int type);

extern const struct ControlInfo barrier_ctrls;
const char *barrier_get_btn(int type);

extern const struct ControlInfo bsktball_ctrls;
const char *bsktball_get_btn(int type);

extern const struct ControlInfo batman_ctrls;
const char *batman_get_btn(int type);

extern const struct ControlInfo batsugun_ctrls;
const char *batsugun_get_btn(int type);

extern const struct ControlInfo battlnts_ctrls;
const char *battlnts_get_btn(int type);

extern const struct ControlInfo bkraidj_ctrls;
const char *bkraidj_get_btn(int type);

extern const struct ControlInfo battlex_ctrls;
const char *battlex_get_btn(int type);

extern const struct ControlInfo bcruzm12_ctrls;
const char *bcruzm12_get_btn(int type);

extern const struct ControlInfo btlkroad_ctrls;
const char *btlkroad_get_btn(int type);

extern const struct ControlInfo battlane_ctrls;
const char *battlane_get_btn(int type);

extern const struct ControlInfo atlantis_ctrls;
const char *atlantis_get_btn(int type);

extern const struct ControlInfo battlera_ctrls;
const char *battlera_get_btn(int type);

extern const struct ControlInfo bshark_ctrls;
const char *bshark_get_btn(int type);

extern const struct ControlInfo btoads_ctrls;
const char *btoads_get_btn(int type);

extern const struct ControlInfo bzone_ctrls;
const char *bzone_get_btn(int type);

extern const struct ControlInfo bayroute_ctrls;
const char *bayroute_get_btn(int type);

extern const struct ControlInfo beaminv_ctrls;
const char *beaminv_get_btn(int type);

extern const struct ControlInfo bbusters_ctrls;
const char *bbusters_get_btn(int type);

extern const struct ControlInfo beathead_ctrls;
const char *beathead_get_btn(int type);

extern const struct ControlInfo bm1stmix_ctrls;
const char *bm1stmix_get_btn(int type);

extern const struct ControlInfo bm2ndmix_ctrls;
const char *bm2ndmix_get_btn(int type);

extern const struct ControlInfo bm4thmix_ctrls;
const char *bm4thmix_get_btn(int type);

extern const struct ControlInfo bm5thmix_ctrls;
const char *bm5thmix_get_btn(int type);

extern const struct ControlInfo bm6thmix_ctrls;
const char *bm6thmix_get_btn(int type);

extern const struct ControlInfo bmcompmx_ctrls;
const char *bmcompmx_get_btn(int type);

extern const struct ControlInfo bmcompm2_ctrls;
const char *bmcompm2_get_btn(int type);

extern const struct ControlInfo bmcorerm_ctrls;
const char *bmcorerm_get_btn(int type);

extern const struct ControlInfo bmdct_ctrls;
const char *bmdct_get_btn(int type);

extern const struct ControlInfo beezer_ctrls;
const char *beezer_get_btn(int type);

extern const struct ControlInfo bel_ctrls;
const char *bel_get_btn(int type);

extern const struct ControlInfo blswhstl_ctrls;
const char *blswhstl_get_btn(int type);

extern const struct ControlInfo berabohm_ctrls;
const char *berabohm_get_btn(int type);

extern const struct ControlInfo bermudat_ctrls;
const char *bermudat_get_btn(int type);

extern const struct ControlInfo berzerk_ctrls;
const char *berzerk_get_btn(int type);

extern const struct ControlInfo bigevglf_ctrls;
const char *bigevglf_get_btn(int type);

extern const struct ControlInfo bigkarnk_ctrls;
const char *bigkarnk_get_btn(int type);

extern const struct ControlInfo bigrun_ctrls;
const char *bigrun_get_btn(int type);

extern const struct ControlInfo bigstrik_ctrls;
const char *bigstrik_get_btn(int type);

extern const struct ControlInfo bigtwin_ctrls;
const char *bigtwin_get_btn(int type);

extern const struct ControlInfo bbonk_ctrls;
const char *bbonk_get_btn(int type);

extern const struct ControlInfo bijokkog_ctrls;
const char *bijokkog_get_btn(int type);

extern const struct ControlInfo bijokkoy_ctrls;
const char *bijokkoy_get_btn(int type);

extern const struct ControlInfo bioatack_ctrls;
const char *bioatack_get_btn(int type);

extern const struct ControlInfo bioship_ctrls;
const char *bioship_get_btn(int type);

extern const struct ControlInfo biofreak_ctrls;
const char *biofreak_get_btn(int type);

extern const struct ControlInfo biomtoy_ctrls;
const char *biomtoy_get_btn(int type);

extern const struct ControlInfo bionicc_ctrls;
const char *bionicc_get_btn(int type);

extern const struct ControlInfo bking_ctrls;
const char *bking_get_btn(int type);

extern const struct ControlInfo bking2_ctrls;
const char *bking2_get_btn(int type);

extern const struct ControlInfo bking3_ctrls;
const char *bking3_get_btn(int type);

extern const struct ControlInfo birdtry_ctrls;
const char *birdtry_get_btn(int type);

extern const struct ControlInfo psailor1_ctrls;
const char *psailor1_get_btn(int type);

extern const struct ControlInfo psailor2_ctrls;
const char *psailor2_get_btn(int type);

extern const struct ControlInfo blkheart_ctrls;
const char *blkheart_get_btn(int type);

extern const struct ControlInfo blkhole_ctrls;
const char *blkhole_get_btn(int type);

extern const struct ControlInfo blkpnthr_ctrls;
const char *blkpnthr_get_btn(int type);

extern const struct ControlInfo blktiger_ctrls;
const char *blktiger_get_btn(int type);

extern const struct ControlInfo bwidow_ctrls;
const char *bwidow_get_btn(int type);

extern const struct ControlInfo bmaster_ctrls;
const char *bmaster_get_btn(int type);

extern const struct ControlInfo bladestl_ctrls;
const char *bladestl_get_btn(int type);

extern const struct ControlInfo blandia_ctrls;
const char *blandia_get_btn(int type);

extern const struct ControlInfo blastoff_ctrls;
const char *blastoff_get_btn(int type);

extern const struct ControlInfo blasted_ctrls;
const char *blasted_get_btn(int type);

extern const struct ControlInfo blaster_ctrls;
const char *blaster_get_btn(int type);

extern const struct ControlInfo blstroid_ctrls;
const char *blstroid_get_btn(int type);

extern const struct ControlInfo blasto_ctrls;
const char *blasto_get_btn(int type);

extern const struct ControlInfo blazeon_ctrls;
const char *blazeon_get_btn(int type);

extern const struct ControlInfo blockout_ctrls;
const char *blockout_get_btn(int type);

extern const struct ControlInfo blockade_ctrls;
const char *blockade_get_btn(int type);

extern const struct ControlInfo bloodbro_ctrls;
const char *bloodbro_get_btn(int type);

extern const struct ControlInfo bloxeed_ctrls;
const char *bloxeed_get_btn(int type);

extern const struct ControlInfo blueprnt_ctrls;
const char *blueprnt_get_btn(int type);

extern const struct ControlInfo blueshrk_ctrls;
const char *blueshrk_get_btn(int type);

extern const struct ControlInfo bodyslam_ctrls;
const char *bodyslam_get_btn(int type);

extern const struct ControlInfo bogeyman_ctrls;
const char *bogeyman_get_btn(int type);

extern const struct ControlInfo bombjack_ctrls;
const char *bombjack_get_btn(int type);

extern const struct ControlInfo boogwing_ctrls;
const char *boogwing_get_btn(int type);

extern const struct ControlInfo boothill_ctrls;
const char *boothill_get_btn(int type);

extern const struct ControlInfo bosco_ctrls;
const char *bosco_get_btn(int type);

extern const struct ControlInfo bottom9_ctrls;
const char *bottom9_get_btn(int type);

extern const struct ControlInfo bouldash_ctrls;
const char *bouldash_get_btn(int type);

extern const struct ControlInfo bowler_ctrls;
const char *bowler_get_btn(int type);

extern const struct ControlInfo boxingb_ctrls;
const char *boxingb_get_btn(int type);

extern const struct ControlInfo bradley_ctrls;
const char *bradley_get_btn(int type);

extern const struct ControlInfo brkthru_ctrls;
const char *brkthru_get_btn(int type);

extern const struct ControlInfo bublbobl_ctrls;
const char *bublbobl_get_btn(int type);

extern const struct ControlInfo bubbles_ctrls;
const char *bubbles_get_btn(int type);

extern const struct ControlInfo buckrog_ctrls;
const char *buckrog_get_btn(int type);

extern const struct ControlInfo buggychl_ctrls;
const char *buggychl_get_btn(int type);

extern const struct ControlInfo btime_ctrls;
const char *btime_get_btn(int type);

extern const struct ControlInfo brubber_ctrls;
const char *brubber_get_btn(int type);

extern const struct ControlInfo cabal_ctrls;
const char *cabal_get_btn(int type);

extern const struct ControlInfo cadash_ctrls;
const char *cadash_get_btn(int type);

extern const struct ControlInfo dino_ctrls;
const char *dino_get_btn(int type);

extern const struct ControlInfo calibr50_ctrls;
const char *calibr50_get_btn(int type);

extern const struct ControlInfo cameltry_ctrls;
const char *cameltry_get_btn(int type);

extern const struct ControlInfo canyon_ctrls;
const char *canyon_get_btn(int type);

extern const struct ControlInfo capbowl_ctrls;
const char *capbowl_get_btn(int type);

extern const struct ControlInfo captaven_ctrls;
const char *captaven_get_btn(int type);

extern const struct ControlInfo captcomm_ctrls;
const char *captcomm_get_btn(int type);

extern const struct ControlInfo carnevil_ctrls;
const char *carnevil_get_btn(int type);

extern const struct ControlInfo carnival_ctrls;
const char *carnival_get_btn(int type);

extern const struct ControlInfo cawing_ctrls;
const char *cawing_get_btn(int type);

extern const struct ControlInfo cavelon_ctrls;
const char *cavelon_get_btn(int type);

extern const struct ControlInfo cninja_ctrls;
const char *cninja_get_btn(int type);

extern const struct ControlInfo centiped_ctrls;
const char *centiped_get_btn(int type);

extern const struct ControlInfo challeng_ctrls;
const char *challeng_get_btn(int type);

extern const struct ControlInfo champbas_ctrls;
const char *champbas_get_btn(int type);

extern const struct ControlInfo csprint_ctrls;
const char *csprint_get_btn(int type);

extern const struct ControlInfo checkman_ctrls;
const char *checkman_get_btn(int type);

extern const struct ControlInfo checkmat_ctrls;
const char *checkmat_get_btn(int type);

extern const struct ControlInfo cheekyms_ctrls;
const char *cheekyms_get_btn(int type);

extern const struct ControlInfo cheyenne_ctrls;
const char *cheyenne_get_btn(int type);

extern const struct ControlInfo cshift_ctrls;
const char *cshift_get_btn(int type);

extern const struct ControlInfo chiller_ctrls;
const char *chiller_get_btn(int type);

extern const struct ControlInfo ccasino_ctrls;
const char *ccasino_get_btn(int type);

extern const struct ControlInfo chopper_ctrls;
const char *chopper_get_btn(int type);

extern const struct ControlInfo circus_ctrls;
const char *circus_get_btn(int type);

extern const struct ControlInfo circusc_ctrls;
const char *circusc_get_btn(int type);

extern const struct ControlInfo cischeat_ctrls;
const char *cischeat_get_btn(int type);

extern const struct ControlInfo citycon_ctrls;
const char *citycon_get_btn(int type);

extern const struct ControlInfo citylove_ctrls;
const char *citylove_get_btn(int type);

extern const struct ControlInfo cloak_ctrls;
const char *cloak_get_btn(int type);

extern const struct ControlInfo clowns_ctrls;
const char *clowns_get_btn(int type);

extern const struct ControlInfo cltchitr_ctrls;
const char *cltchitr_get_btn(int type);

extern const struct ControlInfo colony7_ctrls;
const char *colony7_get_btn(int type);

extern const struct ControlInfo columns_ctrls;
const char *columns_get_btn(int type);

extern const struct ControlInfo combat_ctrls;
const char *combat_get_btn(int type);

extern const struct ControlInfo commsega_ctrls;
const char *commsega_get_btn(int type);

extern const struct ControlInfo commando_ctrls;
const char *commando_get_btn(int type);

extern const struct ControlInfo comotion_ctrls;
const char *comotion_get_btn(int type);

extern const struct ControlInfo congo_ctrls;
const char *congo_get_btn(int type);

extern const struct ControlInfo contra_ctrls;
const char *contra_get_btn(int type);

extern const struct ControlInfo cosmica_ctrls;
const char *cosmica_get_btn(int type);

extern const struct ControlInfo cavenger_ctrls;
const char *cavenger_get_btn(int type);

extern const struct ControlInfo cchasm_ctrls;
const char *cchasm_get_btn(int type);

extern const struct ControlInfo cosmicg_ctrls;
const char *cosmicg_get_btn(int type);

extern const struct ControlInfo cracksht_ctrls;
const char *cracksht_get_btn(int type);

extern const struct ControlInfo crash_ctrls;
const char *crash_get_btn(int type);

extern const struct ControlInfo crater_ctrls;
const char *crater_get_btn(int type);

extern const struct ControlInfo cclimber_ctrls;
const char *cclimber_get_btn(int type);

extern const struct ControlInfo cclimbr2_ctrls;
const char *cclimbr2_get_btn(int type);

extern const struct ControlInfo ckong_ctrls;
const char *ckong_get_btn(int type);

extern const struct ControlInfo crimec_ctrls;
const char *crimec_get_btn(int type);

extern const struct ControlInfo crimfght_ctrls;
const char *crimfght_get_btn(int type);

extern const struct ControlInfo crossbow_ctrls;
const char *crossbow_get_btn(int type);

extern const struct ControlInfo crgolf_ctrls;
const char *crgolf_get_btn(int type);

extern const struct ControlInfo cbuster_ctrls;
const char *cbuster_get_btn(int type);

extern const struct ControlInfo crush_ctrls;
const char *crush_get_btn(int type);

extern const struct ControlInfo cryptklr_ctrls;
const char *cryptklr_get_btn(int type);

extern const struct ControlInfo ccastles_ctrls;
const char *ccastles_get_btn(int type);

extern const struct ControlInfo crystalg_ctrls;
const char *crystalg_get_btn(int type);

extern const struct ControlInfo crystal2_ctrls;
const char *crystal2_get_btn(int type);

extern const struct ControlInfo curvebal_ctrls;
const char *curvebal_get_btn(int type);

extern const struct ControlInfo cybsled_ctrls;
const char *cybsled_get_btn(int type);

extern const struct ControlInfo cyberbal_ctrls;
const char *cyberbal_get_btn(int type);

extern const struct ControlInfo cybots_ctrls;
const char *cybots_get_btn(int type);

extern const struct ControlInfo daioh_ctrls;
const char *daioh_get_btn(int type);

extern const struct ControlInfo dangar_ctrls;
const char *dangar_get_btn(int type);

extern const struct ControlInfo dangerz_ctrls;
const char *dangerz_get_btn(int type);

extern const struct ControlInfo indyheat_ctrls;
const char *indyheat_get_btn(int type);

extern const struct ControlInfo darkplnt_ctrls;
const char *darkplnt_get_btn(int type);

extern const struct ControlInfo darkseal_ctrls;
const char *darkseal_get_btn(int type);

extern const struct ControlInfo dstlk_ctrls;
const char *dstlk_get_btn(int type);

extern const struct ControlInfo deadang_ctrls;
const char *deadang_get_btn(int type);

extern const struct ControlInfo redufo_ctrls;
const char *redufo_get_btn(int type);

extern const struct ControlInfo defender_ctrls;
const char *defender_get_btn(int type);

extern const struct ControlInfo demoderb_ctrls;
const char *demoderb_get_btn(int type);

extern const struct ControlInfo depthch_ctrls;
const char *depthch_get_btn(int type);

extern const struct ControlInfo desertgu_ctrls;
const char *desertgu_get_btn(int type);

extern const struct ControlInfo destroyr_ctrls;
const char *destroyr_get_btn(int type);

extern const struct ControlInfo devstors_ctrls;
const char *devstors_get_btn(int type);

extern const struct ControlInfo devilfsh_ctrls;
const char *devilfsh_get_btn(int type);

extern const struct ControlInfo devzone_ctrls;
const char *devzone_get_btn(int type);

extern const struct ControlInfo digdug_ctrls;
const char *digdug_get_btn(int type);

extern const struct ControlInfo digdug2_ctrls;
const char *digdug2_get_btn(int type);

extern const struct ControlInfo digger_ctrls;
const char *digger_get_btn(int type);

extern const struct ControlInfo dimahoo_ctrls;
const char *dimahoo_get_btn(int type);

extern const struct ControlInfo otatidai_ctrls;
const char *otatidai_get_btn(int type);

extern const struct ControlInfo dotron_ctrls;
const char *dotron_get_btn(int type);

extern const struct ControlInfo dorunrun_ctrls;
const char *dorunrun_get_btn(int type);

extern const struct ControlInfo domino_ctrls;
const char *domino_get_btn(int type);

extern const struct ControlInfo dominos_ctrls;
const char *dominos_get_btn(int type);

extern const struct ControlInfo dondenmj_ctrls;
const char *dondenmj_get_btn(int type);

extern const struct ControlInfo dkong_ctrls;
const char *dkong_get_btn(int type);

extern const struct ControlInfo dkong3_ctrls;
const char *dkong3_get_btn(int type);

extern const struct ControlInfo dkongjr_ctrls;
const char *dkongjr_get_btn(int type);

extern const struct ControlInfo ddragon_ctrls;
const char *ddragon_get_btn(int type);

extern const struct ControlInfo ddragon3_ctrls;
const char *ddragon3_get_btn(int type);

extern const struct ControlInfo ddragon2_ctrls;
const char *ddragon2_get_btn(int type);

extern const struct ControlInfo ddribble_ctrls;
const char *ddribble_get_btn(int type);

extern const struct ControlInfo downtown_ctrls;
const char *downtown_get_btn(int type);

extern const struct ControlInfo dragrace_ctrls;
const char *dragrace_get_btn(int type);

extern const struct ControlInfo dragngun_ctrls;
const char *dragngun_get_btn(int type);

extern const struct ControlInfo dspirit_ctrls;
const char *dspirit_get_btn(int type);

extern const struct ControlInfo drgnunit_ctrls;
const char *drgnunit_get_btn(int type);

extern const struct ControlInfo ddsom_ctrls;
const char *ddsom_get_btn(int type);

extern const struct ControlInfo ddtod_ctrls;
const char *ddtod_get_btn(int type);

extern const struct ControlInfo dynamcop_ctrls;
const char *dynamcop_get_btn(int type);

extern const struct ControlInfo eswat_ctrls;
const char *eswat_get_btn(int type);

extern const struct ControlInfo ecofghtr_ctrls;
const char *ecofghtr_get_btn(int type);

extern const struct ControlInfo eggventr_ctrls;
const char *eggventr_get_btn(int type);

extern const struct ControlInfo elevator_ctrls;
const char *elevator_get_btn(int type);

extern const struct ControlInfo elim2_ctrls;
const char *elim2_get_btn(int type);

extern const struct ControlInfo enigma2_ctrls;
const char *enigma2_get_btn(int type);

extern const struct ControlInfo eprom_ctrls;
const char *eprom_get_btn(int type);

extern const struct ControlInfo exerion_ctrls;
const char *exerion_get_btn(int type);

extern const struct ControlInfo exterm_ctrls;
const char *exterm_get_btn(int type);

extern const struct ControlInfo eyes_ctrls;
const char *eyes_get_btn(int type);

extern const struct ControlInfo f1dream_ctrls;
const char *f1dream_get_btn(int type);

extern const struct ControlInfo f1en_ctrls;
const char *f1en_get_btn(int type);

extern const struct ControlInfo fantasy_ctrls;
const char *fantasy_get_btn(int type);

extern const struct ControlInfo sqbert_ctrls;
const char *sqbert_get_btn(int type);

extern const struct ControlInfo fax_ctrls;
const char *fax_get_btn(int type);

extern const struct ControlInfo fgoal_ctrls;
const char *fgoal_get_btn(int type);

extern const struct ControlInfo fghtatck_ctrls;
const char *fghtatck_get_btn(int type);

extern const struct ControlInfo fvipers_ctrls;
const char *fvipers_get_btn(int type);

extern const struct ControlInfo finalb_ctrls;
const char *finalb_get_btn(int type);

extern const struct ControlInfo ffight_ctrls;
const char *ffight_get_btn(int type);

extern const struct ControlInfo finalap2_ctrls;
const char *finalap2_get_btn(int type);

extern const struct ControlInfo firetrap_ctrls;
const char *firetrap_get_btn(int type);

extern const struct ControlInfo firetrk_ctrls;
const char *firetrk_get_btn(int type);

extern const struct ControlInfo fshark_ctrls;
const char *fshark_get_btn(int type);

extern const struct ControlInfo foodf_ctrls;
const char *foodf_get_btn(int type);

extern const struct ControlInfo forgottn_ctrls;
const char *forgottn_get_btn(int type);

extern const struct ControlInfo formatz_ctrls;
const char *formatz_get_btn(int type);

extern const struct ControlInfo frenzy_ctrls;
const char *frenzy_get_btn(int type);

extern const struct ControlInfo frogger_ctrls;
const char *frogger_get_btn(int type);

extern const struct ControlInfo frogs_ctrls;
const char *frogs_get_btn(int type);

extern const struct ControlInfo frontlin_ctrls;
const char *frontlin_get_btn(int type);

extern const struct ControlInfo futspy_ctrls;
const char *futspy_get_btn(int type);

extern const struct ControlInfo gloc_ctrls;
const char *gloc_get_btn(int type);

extern const struct ControlInfo gijoe_ctrls;
const char *gijoe_get_btn(int type);

extern const struct ControlInfo gground_ctrls;
const char *gground_get_btn(int type);

extern const struct ControlInfo galaga88_ctrls;
const char *galaga88_get_btn(int type);

extern const struct ControlInfo galaga_ctrls;
const char *galaga_get_btn(int type);

extern const struct ControlInfo galaxian_ctrls;
const char *galaxian_get_btn(int type);

extern const struct ControlInfo gforce2_ctrls;
const char *gforce2_get_btn(int type);

extern const struct ControlInfo galxwars_ctrls;
const char *galxwars_get_btn(int type);

extern const struct ControlInfo galpanic_ctrls;
const char *galpanic_get_btn(int type);

extern const struct ControlInfo galpani2_ctrls;
const char *galpani2_get_btn(int type);

extern const struct ControlInfo gaplus_ctrls;
const char *gaplus_get_btn(int type);

extern const struct ControlInfo gauntlet_ctrls;
const char *gauntlet_get_btn(int type);

extern const struct ControlInfo gaunt2_ctrls;
const char *gaunt2_get_btn(int type);

extern const struct ControlInfo geebee_ctrls;
const char *geebee_get_btn(int type);

extern const struct ControlInfo gng_ctrls;
const char *gng_get_btn(int type);

extern const struct ControlInfo ghouls_ctrls;
const char *ghouls_get_btn(int type);

extern const struct ControlInfo gigawing_ctrls;
const char *gigawing_get_btn(int type);

extern const struct ControlInfo goldmedl_ctrls;
const char *goldmedl_get_btn(int type);

extern const struct ControlInfo goldnaxe_ctrls;
const char *goldnaxe_get_btn(int type);

extern const struct ControlInfo ga2_ctrls;
const char *ga2_get_btn(int type);

extern const struct ControlInfo gt97_ctrls;
const char *gt97_get_btn(int type);

extern const struct ControlInfo gt98_ctrls;
const char *gt98_get_btn(int type);

extern const struct ControlInfo gt99_ctrls;
const char *gt99_get_btn(int type);

extern const struct ControlInfo gt2k_ctrls;
const char *gt2k_get_btn(int type);

extern const struct ControlInfo gt3d_ctrls;
const char *gt3d_get_btn(int type);

extern const struct ControlInfo gtg2_ctrls;
const char *gtg2_get_btn(int type);

extern const struct ControlInfo glfgreat_ctrls;
const char *glfgreat_get_btn(int type);

extern const struct ControlInfo golgo13_ctrls;
const char *golgo13_get_btn(int type);

extern const struct ControlInfo gollygho_ctrls;
const char *gollygho_get_btn(int type);

extern const struct ControlInfo gondo_ctrls;
const char *gondo_get_btn(int type);

extern const struct ControlInfo gorf_ctrls;
const char *gorf_get_btn(int type);

extern const struct ControlInfo grchamp_ctrls;
const char *grchamp_get_btn(int type);

extern const struct ControlInfo f1gpstar_ctrls;
const char *f1gpstar_get_btn(int type);

extern const struct ControlInfo gravitar_ctrls;
const char *gravitar_get_btn(int type);

extern const struct ControlInfo greatgun_ctrls;
const char *greatgun_get_btn(int type);

extern const struct ControlInfo gberet_ctrls;
const char *gberet_get_btn(int type);

extern const struct ControlInfo gridiron_ctrls;
const char *gridiron_get_btn(int type);

extern const struct ControlInfo gridlee_ctrls;
const char *gridlee_get_btn(int type);

extern const struct ControlInfo guardian_ctrls;
const char *guardian_get_btn(int type);

extern const struct ControlInfo gwar_ctrls;
const char *gwar_get_btn(int type);

extern const struct ControlInfo gunsmoke_ctrls;
const char *gunsmoke_get_btn(int type);

extern const struct ControlInfo gunbird_ctrls;
const char *gunbird_get_btn(int type);

extern const struct ControlInfo gunbustr_ctrls;
const char *gunbustr_get_btn(int type);

extern const struct ControlInfo gyruss_ctrls;
const char *gyruss_get_btn(int type);

extern const struct ControlInfo halleys_ctrls;
const char *halleys_get_btn(int type);

extern const struct ControlInfo hardyard_ctrls;
const char *hardyard_get_btn(int type);

extern const struct ControlInfo hattrick_ctrls;
const char *hattrick_get_btn(int type);

extern const struct ControlInfo hcastle_ctrls;
const char *hcastle_get_btn(int type);

extern const struct ControlInfo hbarrel_ctrls;
const char *hbarrel_get_btn(int type);

extern const struct ControlInfo hiimpact_ctrls;
const char *hiimpact_get_btn(int type);

extern const struct ControlInfo hippodrm_ctrls;
const char *hippodrm_get_btn(int type);

extern const struct ControlInfo hitme_ctrls;
const char *hitme_get_btn(int type);

extern const struct ControlInfo hitice_ctrls;
const char *hitice_get_btn(int type);

extern const struct ControlInfo holo_ctrls;
const char *holo_get_btn(int type);

extern const struct ControlInfo hotrod_ctrls;
const char *hotrod_get_btn(int type);

extern const struct ControlInfo hstennis_ctrls;
const char *hstennis_get_btn(int type);

extern const struct ControlInfo housemnq_ctrls;
const char *housemnq_get_btn(int type);

extern const struct ControlInfo housemn2_ctrls;
const char *housemn2_get_btn(int type);

extern const struct ControlInfo hustle_ctrls;
const char *hustle_get_btn(int type);

extern const struct ControlInfo hng64_ctrls;
const char *hng64_get_btn(int type);

extern const struct ControlInfo hyperspt_ctrls;
const char *hyperspt_get_btn(int type);

extern const struct ControlInfo irobot_ctrls;
const char *irobot_get_btn(int type);

extern const struct ControlInfo a47pie2_ctrls;
const char *a47pie2_get_btn(int type);

extern const struct ControlInfo idhimitu_ctrls;
const char *idhimitu_get_btn(int type);

extern const struct ControlInfo fromance_ctrls;
const char *fromance_get_btn(int type);

extern const struct ControlInfo idolmj_ctrls;
const char *idolmj_get_btn(int type);

extern const struct ControlInfo iemoto_ctrls;
const char *iemoto_get_btn(int type);

extern const struct ControlInfo ikari3_ctrls;
const char *ikari3_get_btn(int type);

extern const struct ControlInfo ikari_ctrls;
const char *ikari_get_btn(int type);

extern const struct ControlInfo imekura_ctrls;
const char *imekura_get_btn(int type);

extern const struct ControlInfo indytemp_ctrls;
const char *indytemp_get_btn(int type);

extern const struct ControlInfo inferno_ctrls;
const char *inferno_get_btn(int type);

extern const struct ControlInfo invrvnge_ctrls;
const char *invrvnge_get_btn(int type);

extern const struct ControlInfo invho2_ctrls;
const char *invho2_get_btn(int type);

extern const struct ControlInfo offroad_ctrls;
const char *offroad_get_btn(int type);

extern const struct ControlInfo offroadt_ctrls;
const char *offroadt_get_btn(int type);

extern const struct ControlInfo jackal_ctrls;
const char *jackal_get_btn(int type);

extern const struct ControlInfo jailbrek_ctrls;
const char *jailbrek_get_btn(int type);

extern const struct ControlInfo teamqb_ctrls;
const char *teamqb_get_btn(int type);

extern const struct ControlInfo jantouki_ctrls;
const char *jantouki_get_btn(int type);

extern const struct ControlInfo journey_ctrls;
const char *journey_get_btn(int type);

extern const struct ControlInfo joust_ctrls;
const char *joust_get_btn(int type);

extern const struct ControlInfo joust2_ctrls;
const char *joust2_get_btn(int type);

extern const struct ControlInfo joyfulr_ctrls;
const char *joyfulr_get_btn(int type);

extern const struct ControlInfo jrpacman_ctrls;
const char *jrpacman_get_btn(int type);

extern const struct ControlInfo jumpbug_ctrls;
const char *jumpbug_get_btn(int type);

extern const struct ControlInfo junglek_ctrls;
const char *junglek_get_btn(int type);

extern const struct ControlInfo jungler_ctrls;
const char *jungler_get_btn(int type);

extern const struct ControlInfo jpark_ctrls;
const char *jpark_get_btn(int type);

extern const struct ControlInfo kageki_ctrls;
const char *kageki_get_btn(int type);

extern const struct ControlInfo kanatuen_ctrls;
const char *kanatuen_get_btn(int type);

extern const struct ControlInfo kangaroo_ctrls;
const char *kangaroo_get_btn(int type);

extern const struct ControlInfo kaos_ctrls;
const char *kaos_get_btn(int type);

extern const struct ControlInfo kchamp_ctrls;
const char *kchamp_get_btn(int type);

extern const struct ControlInfo karnov_ctrls;
const char *karnov_get_btn(int type);

extern const struct ControlInfo kick_ctrls;
const char *kick_get_btn(int type);

extern const struct ControlInfo kicker_ctrls;
const char *kicker_get_btn(int type);

extern const struct ControlInfo mayumi_ctrls;
const char *mayumi_get_btn(int type);

extern const struct ControlInfo killcom_ctrls;
const char *killcom_get_btn(int type);

extern const struct ControlInfo kinst_ctrls;
const char *kinst_get_btn(int type);

extern const struct ControlInfo kinst2_ctrls;
const char *kinst2_get_btn(int type);

extern const struct ControlInfo kingball_ctrls;
const char *kingball_get_btn(int type);

extern const struct ControlInfo kingofb_ctrls;
const char *kingofb_get_btn(int type);

extern const struct ControlInfo klax_ctrls;
const char *klax_get_btn(int type);

extern const struct ControlInfo knights_ctrls;
const char *knights_get_btn(int type);

extern const struct ControlInfo konamigt_ctrls;
const char *konamigt_get_btn(int type);

extern const struct ControlInfo kroozr_ctrls;
const char *kroozr_get_btn(int type);

extern const struct ControlInfo kram_ctrls;
const char *kram_get_btn(int type);

extern const struct ControlInfo krull_ctrls;
const char *krull_get_btn(int type);

extern const struct ControlInfo kungfum_ctrls;
const char *kungfum_get_btn(int type);

extern const struct ControlInfo kurikint_ctrls;
const char *kurikint_get_btn(int type);

extern const struct ControlInfo ladybug_ctrls;
const char *ladybug_get_btn(int type);

extern const struct ControlInfo lagunar_ctrls;
const char *lagunar_get_btn(int type);

extern const struct ControlInfo lghost_ctrls;
const char *lghost_get_btn(int type);

extern const struct ControlInfo lastduel_ctrls;
const char *lastduel_get_btn(int type);

extern const struct ControlInfo lethalen_ctrls;
const char *lethalen_get_btn(int type);

extern const struct ControlInfo lethalj_ctrls;
const char *lethalj_get_btn(int type);

extern const struct ControlInfo liberatr_ctrls;
const char *liberatr_get_btn(int type);

extern const struct ControlInfo lnc_ctrls;
const char *lnc_get_btn(int type);

extern const struct ControlInfo lockon_ctrls;
const char *lockon_get_btn(int type);

extern const struct ControlInfo locomotn_ctrls;
const char *locomotn_get_btn(int type);

extern const struct ControlInfo ldrun_ctrls;
const char *ldrun_get_btn(int type);

extern const struct ControlInfo looping_ctrls;
const char *looping_get_btn(int type);

extern const struct ControlInfo losttomb_ctrls;
const char *losttomb_get_btn(int type);

extern const struct ControlInfo janjans1_ctrls;
const char *janjans1_get_btn(int type);

extern const struct ControlInfo llander_ctrls;
const char *llander_get_btn(int type);

extern const struct ControlInfo lrescue_ctrls;
const char *lrescue_get_btn(int type);

extern const struct ControlInfo lupin3_ctrls;
const char *lupin3_get_btn(int type);

extern const struct ControlInfo m4_ctrls;
const char *m4_get_btn(int type);

extern const struct ControlInfo mplanets_ctrls;
const char *mplanets_get_btn(int type);

extern const struct ControlInfo msword_ctrls;
const char *msword_get_btn(int type);

extern const struct ControlInfo magspot_ctrls;
const char *magspot_get_btn(int type);

extern const struct ControlInfo akiss_ctrls;
const char *akiss_get_btn(int type);

extern const struct ControlInfo mjangels_ctrls;
const char *mjangels_get_btn(int type);

extern const struct ControlInfo bananadr_ctrls;
const char *bananadr_get_btn(int type);

extern const struct ControlInfo mjcamera_ctrls;
const char *mjcamera_get_btn(int type);

extern const struct ControlInfo mcnpshnt_ctrls;
const char *mcnpshnt_get_btn(int type);

extern const struct ControlInfo chinmoku_ctrls;
const char *chinmoku_get_btn(int type);

extern const struct ControlInfo cmehyou_ctrls;
const char *cmehyou_get_btn(int type);

extern const struct ControlInfo mjclinic_ctrls;
const char *mjclinic_get_btn(int type);

extern const struct ControlInfo club90s_ctrls;
const char *club90s_get_btn(int type);

extern const struct ControlInfo daiyogen_ctrls;
const char *daiyogen_get_btn(int type);

extern const struct ControlInfo mjderngr_ctrls;
const char *mjderngr_get_btn(int type);

extern const struct ControlInfo mjdialq2_ctrls;
const char *mjdialq2_get_btn(int type);

extern const struct ControlInfo mjdiplob_ctrls;
const char *mjdiplob_get_btn(int type);

extern const struct ControlInfo dokyusei_ctrls;
const char *dokyusei_get_btn(int type);

extern const struct ControlInfo dokyusp_ctrls;
const char *dokyusp_get_btn(int type);

extern const struct ControlInfo mjelctrn_ctrls;
const char *mjelctrn_get_btn(int type);

extern const struct ControlInfo mjegolf_ctrls;
const char *mjegolf_get_btn(int type);

extern const struct ControlInfo mjfocus_ctrls;
const char *mjfocus_get_btn(int type);

extern const struct ControlInfo mjfriday_ctrls;
const char *mjfriday_get_btn(int type);

extern const struct ControlInfo mfunclub_ctrls;
const char *mfunclub_get_btn(int type);

extern const struct ControlInfo mgmen89_ctrls;
const char *mgmen89_get_btn(int type);

extern const struct ControlInfo mgakuen_ctrls;
const char *mgakuen_get_btn(int type);

extern const struct ControlInfo mgakuen2_ctrls;
const char *mgakuen2_get_btn(int type);

extern const struct ControlInfo gakusai_ctrls;
const char *gakusai_get_btn(int type);

extern const struct ControlInfo gakusai2_ctrls;
const char *gakusai2_get_btn(int type);

extern const struct ControlInfo gal10ren_ctrls;
const char *gal10ren_get_btn(int type);

extern const struct ControlInfo galkaika_ctrls;
const char *galkaika_get_btn(int type);

extern const struct ControlInfo galkoku_ctrls;
const char *galkoku_get_btn(int type);

extern const struct ControlInfo mjgottsu_ctrls;
const char *mjgottsu_get_btn(int type);

extern const struct ControlInfo hanamomo_ctrls;
const char *hanamomo_get_btn(int type);

extern const struct ControlInfo mhgaiden_ctrls;
const char *mhgaiden_get_btn(int type);

extern const struct ControlInfo mjhokite_ctrls;
const char *mjhokite_get_btn(int type);

extern const struct ControlInfo hourouki_ctrls;
const char *hourouki_get_btn(int type);

extern const struct ControlInfo hypreact_ctrls;
const char *hypreact_get_btn(int type);

extern const struct ControlInfo hypreac2_ctrls;
const char *hypreac2_get_btn(int type);

extern const struct ControlInfo mjikaga_ctrls;
const char *mjikaga_get_btn(int type);

extern const struct ControlInfo janbari_ctrls;
const char *janbari_get_btn(int type);

extern const struct ControlInfo mjlstory_ctrls;
const char *mjlstory_get_btn(int type);

extern const struct ControlInfo jogakuen_ctrls;
const char *jogakuen_get_btn(int type);

extern const struct ControlInfo kaguya_ctrls;
const char *kaguya_get_btn(int type);

extern const struct ControlInfo mkeibaou_ctrls;
const char *mkeibaou_get_btn(int type);

extern const struct ControlInfo mjkinjas_ctrls;
const char *mjkinjas_get_btn(int type);

extern const struct ControlInfo koinomp_ctrls;
const char *koinomp_get_btn(int type);

extern const struct ControlInfo mjkoiura_ctrls;
const char *mjkoiura_get_btn(int type);

extern const struct ControlInfo mjkojink_ctrls;
const char *mjkojink_get_btn(int type);

extern const struct ControlInfo mjkjidai_ctrls;
const char *mjkjidai_get_btn(int type);

extern const struct ControlInfo mjlaman_ctrls;
const char *mjlaman_get_btn(int type);

extern const struct ControlInfo lemnangl_ctrls;
const char *lemnangl_get_btn(int type);

extern const struct ControlInfo mjnanpas_ctrls;
const char *mjnanpas_get_btn(int type);

extern const struct ControlInfo mjnatsu_ctrls;
const char *mjnatsu_get_btn(int type);

extern const struct ControlInfo ntopstar_ctrls;
const char *ntopstar_get_btn(int type);

extern const struct ControlInfo neruton_ctrls;
const char *neruton_get_btn(int type);

extern const struct ControlInfo patimono_ctrls;
const char *patimono_get_btn(int type);

extern const struct ControlInfo pstadium_ctrls;
const char *pstadium_get_btn(int type);

extern const struct ControlInfo ponchin_ctrls;
const char *ponchin_get_btn(int type);

extern const struct ControlInfo mjnquest_ctrls;
const char *mjnquest_get_btn(int type);

extern const struct ControlInfo renaiclb_ctrls;
const char *renaiclb_get_btn(int type);

extern const struct ControlInfo mrokumei_ctrls;
const char *mrokumei_get_btn(int type);

extern const struct ControlInfo sailorws_ctrls;
const char *sailorws_get_btn(int type);

extern const struct ControlInfo msjiken_ctrls;
const char *msjiken_get_btn(int type);

extern const struct ControlInfo mscoutm_ctrls;
const char *mscoutm_get_btn(int type);

extern const struct ControlInfo mjsikaku_ctrls;
const char *mjsikaku_get_btn(int type);

extern const struct ControlInfo mjsister_ctrls;
const char *mjsister_get_btn(int type);

extern const struct ControlInfo majs101b_ctrls;
const char *majs101b_get_btn(int type);

extern const struct ControlInfo mladyhtr_ctrls;
const char *mladyhtr_get_btn(int type);

extern const struct ControlInfo triplew1_ctrls;
const char *triplew1_get_btn(int type);

extern const struct ControlInfo triplew2_ctrls;
const char *triplew2_get_btn(int type);

extern const struct ControlInfo uchuuai_ctrls;
const char *uchuuai_get_btn(int type);

extern const struct ControlInfo mjuraden_ctrls;
const char *mjuraden_get_btn(int type);

extern const struct ControlInfo vanilla_ctrls;
const char *vanilla_get_btn(int type);

extern const struct ControlInfo vitaminc_ctrls;
const char *vitaminc_get_btn(int type);

extern const struct ControlInfo yarunara_ctrls;
const char *yarunara_get_btn(int type);

extern const struct ControlInfo mjyuugi_ctrls;
const char *mjyuugi_get_btn(int type);

extern const struct ControlInfo mjyougo_ctrls;
const char *mjyougo_get_btn(int type);

extern const struct ControlInfo korinai_ctrls;
const char *korinai_get_btn(int type);

extern const struct ControlInfo mhavoc_ctrls;
const char *mhavoc_get_btn(int type);

extern const struct ControlInfo maniach_ctrls;
const char *maniach_get_btn(int type);

extern const struct ControlInfo mappy_ctrls;
const char *mappy_get_btn(int type);

extern const struct ControlInfo marble_ctrls;
const char *marble_get_btn(int type);

extern const struct ControlInfo mario_ctrls;
const char *mario_get_btn(int type);

extern const struct ControlInfo mars_ctrls;
const char *mars_get_btn(int type);

extern const struct ControlInfo mmatrix_ctrls;
const char *mmatrix_get_btn(int type);

extern const struct ControlInfo msh_ctrls;
const char *msh_get_btn(int type);

extern const struct ControlInfo mshvsf_ctrls;
const char *mshvsf_get_btn(int type);

extern const struct ControlInfo mvsc_ctrls;
const char *mvsc_get_btn(int type);

extern const struct ControlInfo matmania_ctrls;
const char *matmania_get_btn(int type);

extern const struct ControlInfo maxrpm_ctrls;
const char *maxrpm_get_btn(int type);

extern const struct ControlInfo maxforce_ctrls;
const char *maxforce_get_btn(int type);

extern const struct ControlInfo mayday_ctrls;
const char *mayday_get_btn(int type);

extern const struct ControlInfo mechatt_ctrls;
const char *mechatt_get_btn(int type);

extern const struct ControlInfo mmehyou_ctrls;
const char *mmehyou_get_btn(int type);

extern const struct ControlInfo pachiten_ctrls;
const char *pachiten_get_btn(int type);

extern const struct ControlInfo megaman2_ctrls;
const char *megaman2_get_btn(int type);

extern const struct ControlInfo megazone_ctrls;
const char *megazone_get_btn(int type);

extern const struct ControlInfo mercs_ctrls;
const char *mercs_get_btn(int type);

extern const struct ControlInfo metamrph_ctrls;
const char *metamrph_get_btn(int type);

extern const struct ControlInfo metrocrs_ctrls;
const char *metrocrs_get_btn(int type);

extern const struct ControlInfo mwalk_ctrls;
const char *mwalk_get_btn(int type);

extern const struct ControlInfo midres_ctrls;
const char *midres_get_btn(int type);

extern const struct ControlInfo gtmr2_ctrls;
const char *gtmr2_get_btn(int type);

extern const struct ControlInfo milliped_ctrls;
const char *milliped_get_btn(int type);

extern const struct ControlInfo minefld_ctrls;
const char *minefld_get_btn(int type);

extern const struct ControlInfo mineswpr_ctrls;
const char *mineswpr_get_btn(int type);

extern const struct ControlInfo minigolf_ctrls;
const char *minigolf_get_btn(int type);

extern const struct ControlInfo mcontest_ctrls;
const char *mcontest_get_btn(int type);

extern const struct ControlInfo missile_ctrls;
const char *missile_get_btn(int type);

extern const struct ControlInfo gmissile_ctrls;
const char *gmissile_get_btn(int type);

extern const struct ControlInfo moguchan_ctrls;
const char *moguchan_get_btn(int type);

extern const struct ControlInfo mole_ctrls;
const char *mole_get_btn(int type);

extern const struct ControlInfo monymony_ctrls;
const char *monymony_get_btn(int type);

extern const struct ControlInfo monsterb_ctrls;
const char *monsterb_get_btn(int type);

extern const struct ControlInfo montecar_ctrls;
const char *montecar_get_btn(int type);

extern const struct ControlInfo mooncrst_ctrls;
const char *mooncrst_get_btn(int type);

extern const struct ControlInfo mpatrol_ctrls;
const char *mpatrol_get_btn(int type);

extern const struct ControlInfo moonwar_ctrls;
const char *moonwar_get_btn(int type);

extern const struct ControlInfo mk_ctrls;
const char *mk_get_btn(int type);

extern const struct ControlInfo mk3_ctrls;
const char *mk3_get_btn(int type);

extern const struct ControlInfo mk4_ctrls;
const char *mk4_get_btn(int type);

extern const struct ControlInfo mk2_ctrls;
const char *mk2_get_btn(int type);

extern const struct ControlInfo mtrap_ctrls;
const char *mtrap_get_btn(int type);

extern const struct ControlInfo mrdo_ctrls;
const char *mrdo_get_btn(int type);

extern const struct ControlInfo docastle_ctrls;
const char *docastle_get_btn(int type);

extern const struct ControlInfo dowild_ctrls;
const char *dowild_get_btn(int type);

extern const struct ControlInfo mrdrillr_ctrls;
const char *mrdrillr_get_btn(int type);

extern const struct ControlInfo mspacman_ctrls;
const char *mspacman_get_btn(int type);

extern const struct ControlInfo mvp_ctrls;
const char *mvp_get_btn(int type);

extern const struct ControlInfo mx5000_ctrls;
const char *mx5000_get_btn(int type);

extern const struct ControlInfo mysticm_ctrls;
const char *mysticm_get_btn(int type);

extern const struct ControlInfo mystwarr_ctrls;
const char *mystwarr_get_btn(int type);

extern const struct ControlInfo nametune_ctrls;
const char *nametune_get_btn(int type);

extern const struct ControlInfo narc_ctrls;
const char *narc_get_btn(int type);

extern const struct ControlInfo nastar_ctrls;
const char *nastar_get_btn(int type);

extern const struct ControlInfo natodef_ctrls;
const char *natodef_get_btn(int type);

extern const struct ControlInfo naughtyb_ctrls;
const char *naughtyb_get_btn(int type);

extern const struct ControlInfo nbahangt_ctrls;
const char *nbahangt_get_btn(int type);

extern const struct ControlInfo nbajam_ctrls;
const char *nbajam_get_btn(int type);

extern const struct ControlInfo neckneck_ctrls;
const char *neckneck_get_btn(int type);

extern const struct ControlInfo ngpgal_ctrls;
const char *ngpgal_get_btn(int type);

extern const struct ControlInfo nmsengen_ctrls;
const char *nmsengen_get_btn(int type);

extern const struct ControlInfo neogeo_ctrls;
const char *neogeo_get_btn(int type);

extern const struct ControlInfo nyny_ctrls;
const char *nyny_get_btn(int type);

extern const struct ControlInfo blitz_ctrls;
const char *blitz_get_btn(int type);

extern const struct ControlInfo nibbler_ctrls;
const char *nibbler_get_btn(int type);

extern const struct ControlInfo nss_ctrls;
const char *nss_get_btn(int type);

extern const struct ControlInfo nomnlnd_ctrls;
const char *nomnlnd_get_btn(int type);

extern const struct ControlInfo nova2001_ctrls;
const char *nova2001_get_btn(int type);

extern const struct ControlInfo ojankoc_ctrls;
const char *ojankoc_get_btn(int type);

extern const struct ControlInfo ojankohs_ctrls;
const char *ojankohs_get_btn(int type);

extern const struct ControlInfo ojankoy_ctrls;
const char *ojankoy_get_btn(int type);

extern const struct ControlInfo ojanko2_ctrls;
const char *ojanko2_get_btn(int type);

extern const struct ControlInfo ojousan_ctrls;
const char *ojousan_get_btn(int type);

extern const struct ControlInfo olibochu_ctrls;
const char *olibochu_get_btn(int type);

extern const struct ControlInfo omegrace_ctrls;
const char *omegrace_get_btn(int type);

extern const struct ControlInfo oneshot_ctrls;
const char *oneshot_get_btn(int type);

extern const struct ControlInfo othunder_ctrls;
const char *othunder_get_btn(int type);

extern const struct ControlInfo opwolf_ctrls;
const char *opwolf_get_btn(int type);

extern const struct ControlInfo opwolf3_ctrls;
const char *opwolf3_get_btn(int type);

extern const struct ControlInfo orangec_ctrls;
const char *orangec_get_btn(int type);

extern const struct ControlInfo otonano_ctrls;
const char *otonano_get_btn(int type);

extern const struct ControlInfo outrun_ctrls;
const char *outrun_get_btn(int type);

extern const struct ControlInfo overdriv_ctrls;
const char *overdriv_get_btn(int type);

extern const struct ControlInfo pow_ctrls;
const char *pow_get_btn(int type);

extern const struct ControlInfo pacland_ctrls;
const char *pacland_get_btn(int type);

extern const struct ControlInfo pacplus_ctrls;
const char *pacplus_get_btn(int type);

extern const struct ControlInfo pacmania_ctrls;
const char *pacmania_get_btn(int type);

extern const struct ControlInfo paddlema_ctrls;
const char *paddlema_get_btn(int type);

extern const struct ControlInfo pandoras_ctrls;
const char *pandoras_get_btn(int type);

extern const struct ControlInfo paperboy_ctrls;
const char *paperboy_get_btn(int type);

extern const struct ControlInfo pastelg_ctrls;
const char *pastelg_get_btn(int type);

extern const struct ControlInfo pengo_ctrls;
const char *pengo_get_btn(int type);

extern const struct ControlInfo pepper2_ctrls;
const char *pepper2_get_btn(int type);

extern const struct ControlInfo peterpak_ctrls;
const char *peterpak_get_btn(int type);

extern const struct ControlInfo phoenix_ctrls;
const char *phoenix_get_btn(int type);

extern const struct ControlInfo pigout_ctrls;
const char *pigout_get_btn(int type);

extern const struct ControlInfo pigskin_ctrls;
const char *pigskin_get_btn(int type);

extern const struct ControlInfo pbaction_ctrls;
const char *pbaction_get_btn(int type);

extern const struct ControlInfo piratetr_ctrls;
const char *piratetr_get_btn(int type);

extern const struct ControlInfo pitfight_ctrls;
const char *pitfight_get_btn(int type);

extern const struct ControlInfo pitfall2_ctrls;
const char *pitfall2_get_btn(int type);

extern const struct ControlInfo playch10_ctrls;
const char *playch10_get_btn(int type);

extern const struct ControlInfo pleiads_ctrls;
const char *pleiads_get_btn(int type);

extern const struct ControlInfo plotting_ctrls;
const char *plotting_get_btn(int type);

extern const struct ControlInfo ptblank_ctrls;
const char *ptblank_get_btn(int type);

extern const struct ControlInfo polaris_ctrls;
const char *polaris_get_btn(int type);

extern const struct ControlInfo polepos_ctrls;
const char *polepos_get_btn(int type);

extern const struct ControlInfo polepos2_ctrls;
const char *polepos2_get_btn(int type);

extern const struct ControlInfo policetr_ctrls;
const char *policetr_get_btn(int type);

extern const struct ControlInfo polyplay_ctrls;
const char *polyplay_get_btn(int type);

extern const struct ControlInfo ponpoko_ctrls;
const char *ponpoko_get_btn(int type);

extern const struct ControlInfo pooyan_ctrls;
const char *pooyan_get_btn(int type);

extern const struct ControlInfo popeye_ctrls;
const char *popeye_get_btn(int type);

extern const struct ControlInfo popper_ctrls;
const char *popper_get_btn(int type);

extern const struct ControlInfo pdrift_ctrls;
const char *pdrift_get_btn(int type);

extern const struct ControlInfo powerdrv_ctrls;
const char *powerdrv_get_btn(int type);

extern const struct ControlInfo pclubj_ctrls;
const char *pclubj_get_btn(int type);

extern const struct ControlInfo kiwame_ctrls;
const char *kiwame_get_btn(int type);

extern const struct ControlInfo profpac_ctrls;
const char *profpac_get_btn(int type);

extern const struct ControlInfo psychos_ctrls;
const char *psychos_get_btn(int type);

extern const struct ControlInfo puckman_ctrls;
const char *puckman_get_btn(int type);

extern const struct ControlInfo pulsar_ctrls;
const char *pulsar_get_btn(int type);

extern const struct ControlInfo punchout_ctrls;
const char *punchout_get_btn(int type);

extern const struct ControlInfo punkshot_ctrls;
const char *punkshot_get_btn(int type);

extern const struct ControlInfo pbobble_ctrls;
const char *pbobble_get_btn(int type);

extern const struct ControlInfo pbobble2_ctrls;
const char *pbobble2_get_btn(int type);

extern const struct ControlInfo pbobble3_ctrls;
const char *pbobble3_get_btn(int type);

extern const struct ControlInfo qbert_ctrls;
const char *qbert_get_btn(int type);

extern const struct ControlInfo qbertqub_ctrls;
const char *qbertqub_get_btn(int type);

extern const struct ControlInfo qix_ctrls;
const char *qix_get_btn(int type);

extern const struct ControlInfo quantum_ctrls;
const char *quantum_get_btn(int type);

extern const struct ControlInfo quarterb_ctrls;
const char *quarterb_get_btn(int type);

extern const struct ControlInfo quartet_ctrls;
const char *quartet_get_btn(int type);

extern const struct ControlInfo quasar_ctrls;
const char *quasar_get_btn(int type);

extern const struct ControlInfo qad_ctrls;
const char *qad_get_btn(int type);

extern const struct ControlInfo qndream_ctrls;
const char *qndream_get_btn(int type);

extern const struct ControlInfo qmhayaku_ctrls;
const char *qmhayaku_get_btn(int type);

extern const struct ControlInfo rtype_ctrls;
const char *rtype_get_btn(int type);

extern const struct ControlInfo radarscp_ctrls;
const char *radarscp_get_btn(int type);

extern const struct ControlInfo radrad_ctrls;
const char *radrad_get_btn(int type);

extern const struct ControlInfo rchase_ctrls;
const char *rchase_get_btn(int type);

extern const struct ControlInfo rainbow_ctrls;
const char *rainbow_get_btn(int type);

extern const struct ControlInfo rallyx_ctrls;
const char *rallyx_get_btn(int type);

extern const struct ControlInfo rampage_ctrls;
const char *rampage_get_btn(int type);

extern const struct ControlInfo rmpgwt_ctrls;
const char *rmpgwt_get_btn(int type);

extern const struct ControlInfo rampart_ctrls;
const char *rampart_get_btn(int type);

extern const struct ControlInfo rastan_ctrls;
const char *rastan_get_btn(int type);

extern const struct ControlInfo reactor_ctrls;
const char *reactor_get_btn(int type);

extern const struct ControlInfo rmhaihai_ctrls;
const char *rmhaihai_get_btn(int type);

extern const struct ControlInfo rmhaijin_ctrls;
const char *rmhaijin_get_btn(int type);

extern const struct ControlInfo rmhaisei_ctrls;
const char *rmhaisei_get_btn(int type);

extern const struct ControlInfo redlin2p_ctrls;
const char *redlin2p_get_btn(int type);

extern const struct ControlInfo regulus_ctrls;
const char *regulus_get_btn(int type);

extern const struct ControlInfo renegade_ctrls;
const char *renegade_get_btn(int type);

extern const struct ControlInfo rescue_ctrls;
const char *rescue_get_btn(int type);

extern const struct ControlInfo rescraid_ctrls;
const char *rescraid_get_btn(int type);

extern const struct ControlInfo nekkyoku_ctrls;
const char *nekkyoku_get_btn(int type);

extern const struct ControlInfo jedi_ctrls;
const char *jedi_get_btn(int type);

extern const struct ControlInfo revx_ctrls;
const char *revx_get_btn(int type);

extern const struct ControlInfo ripoff_ctrls;
const char *ripoff_get_btn(int type);

extern const struct ControlInfo roadblst_ctrls;
const char *roadblst_get_btn(int type);

extern const struct ControlInfo roadf_ctrls;
const char *roadf_get_btn(int type);

extern const struct ControlInfo roadrunn_ctrls;
const char *roadrunn_get_btn(int type);

extern const struct ControlInfo robby_ctrls;
const char *robby_get_btn(int type);

extern const struct ControlInfo robocop_ctrls;
const char *robocop_get_btn(int type);

extern const struct ControlInfo robocop2_ctrls;
const char *robocop2_get_btn(int type);

extern const struct ControlInfo robotron_ctrls;
const char *robotron_get_btn(int type);

extern const struct ControlInfo rocnrope_ctrls;
const char *rocnrope_get_btn(int type);

extern const struct ControlInfo rollerg_ctrls;
const char *rollerg_get_btn(int type);

extern const struct ControlInfo rthunder_ctrls;
const char *rthunder_get_btn(int type);

extern const struct ControlInfo rranger_ctrls;
const char *rranger_get_btn(int type);

extern const struct ControlInfo roundup_ctrls;
const char *roundup_get_btn(int type);

extern const struct ControlInfo royalmah_ctrls;
const char *royalmah_get_btn(int type);

extern const struct ControlInfo rungun_ctrls;
const char *rungun_get_btn(int type);

extern const struct ControlInfo runaway_ctrls;
const char *runaway_get_btn(int type);

extern const struct ControlInfo kirarast_ctrls;
const char *kirarast_get_btn(int type);

extern const struct ControlInfo stunrun_ctrls;
const char *stunrun_get_btn(int type);

extern const struct ControlInfo salamand_ctrls;
const char *salamand_get_btn(int type);

extern const struct ControlInfo searchar_ctrls;
const char *searchar_get_btn(int type);

extern const struct ControlInfo sarge_ctrls;
const char *sarge_get_btn(int type);

extern const struct ControlInfo satansat_ctrls;
const char *satansat_get_btn(int type);

extern const struct ControlInfo shollow_ctrls;
const char *shollow_get_btn(int type);

extern const struct ControlInfo scandal_ctrls;
const char *scandal_get_btn(int type);

extern const struct ControlInfo scramble_ctrls;
const char *scramble_get_btn(int type);

extern const struct ControlInfo sdi_ctrls;
const char *sdi_get_btn(int type);

extern const struct ControlInfo seawolf_ctrls;
const char *seawolf_get_btn(int type);

extern const struct ControlInfo seawolf2_ctrls;
const char *seawolf2_get_btn(int type);

extern const struct ControlInfo secolove_ctrls;
const char *secolove_get_btn(int type);

extern const struct ControlInfo seiha_ctrls;
const char *seiha_get_btn(int type);

extern const struct ControlInfo sengokmj_ctrls;
const char *sengokmj_get_btn(int type);

extern const struct ControlInfo shdancer_ctrls;
const char *shdancer_get_btn(int type);

extern const struct ControlInfo shadoww_ctrls;
const char *shadoww_get_btn(int type);

extern const struct ControlInfo sharkatt_ctrls;
const char *sharkatt_get_btn(int type);

extern const struct ControlInfo sshooter_ctrls;
const char *sshooter_get_btn(int type);

extern const struct ControlInfo sheriff_ctrls;
const char *sheriff_get_btn(int type);

extern const struct ControlInfo shinobi_ctrls;
const char *shinobi_get_btn(int type);

extern const struct ControlInfo shootout_ctrls;
const char *shootout_get_btn(int type);

extern const struct ControlInfo shootbul_ctrls;
const char *shootbul_get_btn(int type);

extern const struct ControlInfo shuffle_ctrls;
const char *shuffle_get_btn(int type);

extern const struct ControlInfo shufshot_ctrls;
const char *shufshot_get_btn(int type);

extern const struct ControlInfo sidearms_ctrls;
const char *sidearms_get_btn(int type);

extern const struct ControlInfo sidetrac_ctrls;
const char *sidetrac_get_btn(int type);

extern const struct ControlInfo sinistar_ctrls;
const char *sinistar_get_btn(int type);

extern const struct ControlInfo skullxbo_ctrls;
const char *skullxbo_get_btn(int type);

extern const struct ControlInfo skydiver_ctrls;
const char *skydiver_get_btn(int type);

extern const struct ControlInfo skysoldr_ctrls;
const char *skysoldr_get_btn(int type);

extern const struct ControlInfo slapfigh_ctrls;
const char *slapfigh_get_btn(int type);

extern const struct ControlInfo slikshot_ctrls;
const char *slikshot_get_btn(int type);

extern const struct ControlInfo slither_ctrls;
const char *slither_get_btn(int type);

extern const struct ControlInfo slyspy_ctrls;
const char *slyspy_get_btn(int type);

extern const struct ControlInfo smashtv_ctrls;
const char *smashtv_get_btn(int type);

extern const struct ControlInfo snakjack_ctrls;
const char *snakjack_get_btn(int type);

extern const struct ControlInfo snapjack_ctrls;
const char *snapjack_get_btn(int type);

extern const struct ControlInfo snowbros_ctrls;
const char *snowbros_get_btn(int type);

extern const struct ControlInfo solarfox_ctrls;
const char *solarfox_get_btn(int type);

extern const struct ControlInfo solarq_ctrls;
const char *solarq_get_btn(int type);

extern const struct ControlInfo amazon_ctrls;
const char *amazon_get_btn(int type);

extern const struct ControlInfo sbm_ctrls;
const char *sbm_get_btn(int type);

extern const struct ControlInfo souledge_ctrls;
const char *souledge_get_btn(int type);

extern const struct ControlInfo sspaceat_ctrls;
const char *sspaceat_get_btn(int type);

extern const struct ControlInfo spacduel_ctrls;
const char *spacduel_get_btn(int type);

extern const struct ControlInfo spacefb_ctrls;
const char *spacefb_get_btn(int type);

extern const struct ControlInfo spacfury_ctrls;
const char *spacfury_get_btn(int type);

extern const struct ControlInfo spacegun_ctrls;
const char *spacegun_get_btn(int type);

extern const struct ControlInfo sharrier_ctrls;
const char *sharrier_get_btn(int type);

extern const struct ControlInfo invaders_ctrls;
const char *invaders_get_btn(int type);

extern const struct ControlInfo spacedx_ctrls;
const char *spacedx_get_btn(int type);

extern const struct ControlInfo invadpt2_ctrls;
const char *invadpt2_get_btn(int type);

extern const struct ControlInfo spacelnc_ctrls;
const char *spacelnc_get_btn(int type);

extern const struct ControlInfo spaceod_ctrls;
const char *spaceod_get_btn(int type);

extern const struct ControlInfo panic_ctrls;
const char *panic_get_btn(int type);

extern const struct ControlInfo spacezap_ctrls;
const char *spacezap_get_btn(int type);

extern const struct ControlInfo speakres_ctrls;
const char *speakres_get_btn(int type);

extern const struct ControlInfo spectar_ctrls;
const char *spectar_get_btn(int type);

extern const struct ControlInfo spdcoin_ctrls;
const char *spdcoin_get_btn(int type);

extern const struct ControlInfo speedfrk_ctrls;
const char *speedfrk_get_btn(int type);

extern const struct ControlInfo speedrcr_ctrls;
const char *speedrcr_get_btn(int type);

extern const struct ControlInfo spidman_ctrls;
const char *spidman_get_btn(int type);

extern const struct ControlInfo spiders_ctrls;
const char *spiders_get_btn(int type);

extern const struct ControlInfo sprint1_ctrls;
const char *sprint1_get_btn(int type);

extern const struct ControlInfo starcas_ctrls;
const char *starcas_get_btn(int type);

extern const struct ControlInfo starforc_ctrls;
const char *starforc_get_btn(int type);

extern const struct ControlInfo stargrds_ctrls;
const char *stargrds_get_btn(int type);

extern const struct ControlInfo starhawk_ctrls;
const char *starhawk_get_btn(int type);

extern const struct ControlInfo starjack_ctrls;
const char *starjack_get_btn(int type);

extern const struct ControlInfo startrek_ctrls;
const char *startrek_get_btn(int type);

extern const struct ControlInfo starwars_ctrls;
const char *starwars_get_btn(int type);

extern const struct ControlInfo stargate_ctrls;
const char *stargate_get_btn(int type);

extern const struct ControlInfo sgunner_ctrls;
const char *sgunner_get_btn(int type);

extern const struct ControlInfo sgunner2_ctrls;
const char *sgunner2_get_btn(int type);

extern const struct ControlInfo stocker_ctrls;
const char *stocker_get_btn(int type);

extern const struct ControlInfo stratab_ctrls;
const char *stratab_get_btn(int type);

extern const struct ControlInfo stratgyx_ctrls;
const char *stratgyx_get_btn(int type);

extern const struct ControlInfo sf_ctrls;
const char *sf_get_btn(int type);

extern const struct ControlInfo sfa2_ctrls;
const char *sfa2_get_btn(int type);

extern const struct ControlInfo sfa3_ctrls;
const char *sfa3_get_btn(int type);

extern const struct ControlInfo sfa_ctrls;
const char *sfa_get_btn(int type);

extern const struct ControlInfo sf2ce_ctrls;
const char *sf2ce_get_btn(int type);

extern const struct ControlInfo sf2_ctrls;
const char *sf2_get_btn(int type);

extern const struct ControlInfo sfiii2_ctrls;
const char *sfiii2_get_btn(int type);

extern const struct ControlInfo sfiii3_ctrls;
const char *sfiii3_get_btn(int type);

extern const struct ControlInfo sfiii_ctrls;
const char *sfiii_get_btn(int type);

extern const struct ControlInfo sftm_ctrls;
const char *sftm_get_btn(int type);

extern const struct ControlInfo strider_ctrls;
const char *strider_get_btn(int type);

extern const struct ControlInfo sbowling_ctrls;
const char *sbowling_get_btn(int type);

extern const struct ControlInfo strkforc_ctrls;
const char *strkforc_get_btn(int type);

extern const struct ControlInfo s1945_ctrls;
const char *s1945_get_btn(int type);

extern const struct ControlInfo s1945iii_ctrls;
const char *s1945iii_get_btn(int type);

extern const struct ControlInfo subs_ctrls;
const char *subs_get_btn(int type);

extern const struct ControlInfo ssriders_ctrls;
const char *ssriders_get_btn(int type);

extern const struct ControlInfo sbagman_ctrls;
const char *sbagman_get_btn(int type);

extern const struct ControlInfo sbrkout_ctrls;
const char *sbrkout_get_btn(int type);

extern const struct ControlInfo scobra_ctrls;
const char *scobra_get_btn(int type);

extern const struct ControlInfo scontra_ctrls;
const char *scontra_get_btn(int type);

extern const struct ControlInfo spdodgeb_ctrls;
const char *spdodgeb_get_btn(int type);

extern const struct ControlInfo sgemf_ctrls;
const char *sgemf_get_btn(int type);

extern const struct ControlInfo shimpact_ctrls;
const char *shimpact_get_btn(int type);

extern const struct ControlInfo marukin_ctrls;
const char *marukin_get_btn(int type);

extern const struct ControlInfo smgp_ctrls;
const char *smgp_get_btn(int type);

extern const struct ControlInfo superpac_ctrls;
const char *superpac_get_btn(int type);

extern const struct ControlInfo spbactn_ctrls;
const char *spbactn_get_btn(int type);

extern const struct ControlInfo spnchout_ctrls;
const char *spnchout_get_btn(int type);

extern const struct ControlInfo sqix_ctrls;
const char *sqix_get_btn(int type);

extern const struct ControlInfo srmp7_ctrls;
const char *srmp7_get_btn(int type);

extern const struct ControlInfo srmp2_ctrls;
const char *srmp2_get_btn(int type);

extern const struct ControlInfo srmp3_ctrls;
const char *srmp3_get_btn(int type);

extern const struct ControlInfo srmp4_ctrls;
const char *srmp4_get_btn(int type);

extern const struct ControlInfo sspeedr_ctrls;
const char *sspeedr_get_btn(int type);

extern const struct ControlInfo ssprint_ctrls;
const char *ssprint_get_btn(int type);

extern const struct ControlInfo ssf2_ctrls;
const char *ssf2_get_btn(int type);

extern const struct ControlInfo sstrike_ctrls;
const char *sstrike_get_btn(int type);

extern const struct ControlInfo szaxxon_ctrls;
const char *szaxxon_get_btn(int type);

extern const struct ControlInfo superman_ctrls;
const char *superman_get_btn(int type);

extern const struct ControlInfo swimmer_ctrls;
const char *swimmer_get_btn(int type);

extern const struct ControlInfo tnk3_ctrls;
const char *tnk3_get_btn(int type);

extern const struct ControlInfo ttmahjng_ctrls;
const char *ttmahjng_get_btn(int type);

extern const struct ControlInfo tailg_ctrls;
const char *tailg_get_btn(int type);

extern const struct ControlInfo hotgmck_ctrls;
const char *hotgmck_get_btn(int type);

extern const struct ControlInfo hotgmck3_ctrls;
const char *hotgmck3_get_btn(int type);

extern const struct ControlInfo hgkairak_ctrls;
const char *hgkairak_get_btn(int type);

extern const struct ControlInfo fromanc2_ctrls;
const char *fromanc2_get_btn(int type);

extern const struct ControlInfo fromanc4_ctrls;
const char *fromanc4_get_btn(int type);

extern const struct ControlInfo fromancr_ctrls;
const char *fromancr_get_btn(int type);

extern const struct ControlInfo tank8_ctrls;
const char *tank8_get_btn(int type);

extern const struct ControlInfo tankbatt_ctrls;
const char *tankbatt_get_btn(int type);

extern const struct ControlInfo tapper_ctrls;
const char *tapper_get_btn(int type);

extern const struct ControlInfo targ_ctrls;
const char *targ_get_btn(int type);

extern const struct ControlInfo tazmania_ctrls;
const char *tazmania_get_btn(int type);

extern const struct ControlInfo tbowl_ctrls;
const char *tbowl_get_btn(int type);

extern const struct ControlInfo tmnt_ctrls;
const char *tmnt_get_btn(int type);

extern const struct ControlInfo tmnt2_ctrls;
const char *tmnt2_get_btn(int type);

extern const struct ControlInfo tehkanwc_ctrls;
const char *tehkanwc_get_btn(int type);

extern const struct ControlInfo tekken_ctrls;
const char *tekken_get_btn(int type);

extern const struct ControlInfo tekken2_ctrls;
const char *tekken2_get_btn(int type);

extern const struct ControlInfo tekken3_ctrls;
const char *tekken3_get_btn(int type);

extern const struct ControlInfo telmahjn_ctrls;
const char *telmahjn_get_btn(int type);

extern const struct ControlInfo tempest_ctrls;
const char *tempest_get_btn(int type);

extern const struct ControlInfo tengai_ctrls;
const char *tengai_get_btn(int type);

extern const struct ControlInfo term2_ctrls;
const char *term2_get_btn(int type);

extern const struct ControlInfo terracre_ctrls;
const char *terracre_get_btn(int type);

extern const struct ControlInfo terraf_ctrls;
const char *terraf_get_btn(int type);

extern const struct ControlInfo atetris_ctrls;
const char *atetris_get_btn(int type);

extern const struct ControlInfo tetris_ctrls;
const char *tetris_get_btn(int type);

extern const struct ControlInfo tetrisp_ctrls;
const char *tetrisp_get_btn(int type);

extern const struct ControlInfo tetrisp2_ctrls;
const char *tetrisp2_get_btn(int type);

extern const struct ControlInfo ctribe_ctrls;
const char *ctribe_get_btn(int type);

extern const struct ControlInfo elecyoyo_ctrls;
const char *elecyoyo_get_btn(int type);

extern const struct ControlInfo esb_ctrls;
const char *esb_get_btn(int type);

extern const struct ControlInfo theend_ctrls;
const char *theend_get_btn(int type);

extern const struct ControlInfo lkage_ctrls;
const char *lkage_get_btn(int type);

extern const struct ControlInfo themj_ctrls;
const char *themj_get_btn(int type);

extern const struct ControlInfo mainevt_ctrls;
const char *mainevt_get_btn(int type);

extern const struct ControlInfo ninjaw_ctrls;
const char *ninjaw_get_btn(int type);

extern const struct ControlInfo thepit_ctrls;
const char *thepit_get_btn(int type);

extern const struct ControlInfo punisher_ctrls;
const char *punisher_get_btn(int type);

extern const struct ControlInfo ghostb_ctrls;
const char *ghostb_get_btn(int type);

extern const struct ControlInfo simpsons_ctrls;
const char *simpsons_get_btn(int type);

extern const struct ControlInfo srumbler_ctrls;
const char *srumbler_get_btn(int type);

extern const struct ControlInfo a3stooges_ctrls;
const char *a3stooges_get_btn(int type);

extern const struct ControlInfo tinstar_ctrls;
const char *tinstar_get_btn(int type);

extern const struct ControlInfo thief_ctrls;
const char *thief_get_btn(int type);

extern const struct ControlInfo a3wonders_ctrls;
const char *a3wonders_get_btn(int type);

extern const struct ControlInfo thndrbld_ctrls;
const char *thndrbld_get_btn(int type);

extern const struct ControlInfo thundfox_ctrls;
const char *thundfox_get_btn(int type);

extern const struct ControlInfo thunderj_ctrls;
const char *thunderj_get_btn(int type);

extern const struct ControlInfo tickee_ctrls;
const char *tickee_get_btn(int type);

extern const struct ControlInfo tigerh_ctrls;
const char *tigerh_get_btn(int type);

extern const struct ControlInfo tigeroad_ctrls;
const char *tigeroad_get_btn(int type);

extern const struct ControlInfo timber_ctrls;
const char *timber_get_btn(int type);

extern const struct ControlInfo timecris_ctrls;
const char *timecris_get_btn(int type);

extern const struct ControlInfo timekill_ctrls;
const char *timekill_get_btn(int type);

extern const struct ControlInfo timeplt_ctrls;
const char *timeplt_get_btn(int type);

extern const struct ControlInfo timesold_ctrls;
const char *timesold_get_btn(int type);

extern const struct ControlInfo titlef_ctrls;
const char *titlef_get_btn(int type);

extern const struct ControlInfo toki_ctrls;
const char *toki_get_btn(int type);

extern const struct ControlInfo tmmjprd_ctrls;
const char *tmmjprd_get_btn(int type);

extern const struct ControlInfo mahmajn_ctrls;
const char *mahmajn_get_btn(int type);

extern const struct ControlInfo mahmajn2_ctrls;
const char *mahmajn2_get_btn(int type);

extern const struct ControlInfo tokyogal_ctrls;
const char *tokyogal_get_btn(int type);

extern const struct ControlInfo tomahawk_ctrls;
const char *tomahawk_get_btn(int type);

extern const struct ControlInfo tontonb_ctrls;
const char *tontonb_get_btn(int type);

extern const struct ControlInfo toobin_ctrls;
const char *toobin_get_btn(int type);

extern const struct ControlInfo topspeed_ctrls;
const char *topspeed_get_btn(int type);

extern const struct ControlInfo totcarn_ctrls;
const char *totcarn_get_btn(int type);

extern const struct ControlInfo tdfever_ctrls;
const char *tdfever_get_btn(int type);

extern const struct ControlInfo toypop_ctrls;
const char *toypop_get_btn(int type);

extern const struct ControlInfo trackfld_ctrls;
const char *trackfld_get_btn(int type);

extern const struct ControlInfo tranqgun_ctrls;
const char *tranqgun_get_btn(int type);

extern const struct ControlInfo trisport_ctrls;
const char *trisport_get_btn(int type);

extern const struct ControlInfo triplhnt_ctrls;
const char *triplhnt_get_btn(int type);

extern const struct ControlInfo statriv2_ctrls;
const char *statriv2_get_btn(int type);

extern const struct ControlInfo gtsers8_ctrls;
const char *gtsers8_get_btn(int type);

extern const struct ControlInfo gt507uk_ctrls;
const char *gt507uk_get_btn(int type);

extern const struct ControlInfo gt5_ctrls;
const char *gt5_get_btn(int type);

extern const struct ControlInfo trvgns_ctrls;
const char *trvgns_get_btn(int type);

extern const struct ControlInfo triviasp_ctrls;
const char *triviasp_get_btn(int type);

extern const struct ControlInfo triviabb_ctrls;
const char *triviabb_get_btn(int type);

extern const struct ControlInfo triviag1_ctrls;
const char *triviag1_get_btn(int type);

extern const struct ControlInfo triviag2_ctrls;
const char *triviag2_get_btn(int type);

extern const struct ControlInfo triviayp_ctrls;
const char *triviayp_get_btn(int type);

extern const struct ControlInfo trog_ctrls;
const char *trog_get_btn(int type);

extern const struct ControlInfo tron_ctrls;
const char *tron_get_btn(int type);

extern const struct ControlInfo tubep_ctrls;
const char *tubep_get_btn(int type);

extern const struct ControlInfo tunhunt_ctrls;
const char *tunhunt_get_btn(int type);

extern const struct ControlInfo turbo_ctrls;
const char *turbo_get_btn(int type);

extern const struct ControlInfo turbofrc_ctrls;
const char *turbofrc_get_btn(int type);

extern const struct ControlInfo toutrun_ctrls;
const char *toutrun_get_btn(int type);

extern const struct ControlInfo tshoot_ctrls;
const char *tshoot_get_btn(int type);

extern const struct ControlInfo tutankhm_ctrls;
const char *tutankhm_get_btn(int type);

extern const struct ControlInfo twincobr_ctrls;
const char *twincobr_get_btn(int type);

extern const struct ControlInfo twineagl_ctrls;
const char *twineagl_get_btn(int type);

extern const struct ControlInfo twineag2_ctrls;
const char *twineag2_get_btn(int type);

extern const struct ControlInfo twotiger_ctrls;
const char *twotiger_get_btn(int type);

extern const struct ControlInfo earthjkr_ctrls;
const char *earthjkr_get_btn(int type);

extern const struct ControlInfo unsquad_ctrls;
const char *unsquad_get_btn(int type);

extern const struct ControlInfo vball_ctrls;
const char *vball_get_btn(int type);

extern const struct ControlInfo usclssic_ctrls;
const char *usclssic_get_btn(int type);

extern const struct ControlInfo ultramhm_ctrls;
const char *ultramhm_get_btn(int type);

extern const struct ControlInfo ultratnk_ctrls;
const char *ultratnk_get_btn(int type);

extern const struct ControlInfo utoukond_ctrls;
const char *utoukond_get_btn(int type);

extern const struct ControlInfo undrfire_ctrls;
const char *undrfire_get_btn(int type);

extern const struct ControlInfo uniwars_ctrls;
const char *uniwars_get_btn(int type);

extern const struct ControlInfo upndown_ctrls;
const char *upndown_get_btn(int type);

extern const struct ControlInfo valkyrie_ctrls;
const char *valkyrie_get_btn(int type);

extern const struct ControlInfo vandyke_ctrls;
const char *vandyke_get_btn(int type);

extern const struct ControlInfo vanguard_ctrls;
const char *vanguard_get_btn(int type);

extern const struct ControlInfo varth_ctrls;
const char *varth_get_btn(int type);

extern const struct ControlInfo vendetta_ctrls;
const char *vendetta_get_btn(int type);

extern const struct ControlInfo venture_ctrls;
const char *venture_get_btn(int type);

extern const struct ControlInfo victory_ctrls;
const char *victory_get_btn(int type);

extern const struct ControlInfo victroad_ctrls;
const char *victroad_get_btn(int type);

extern const struct ControlInfo hustler_ctrls;
const char *hustler_get_btn(int type);

extern const struct ControlInfo videopin_ctrls;
const char *videopin_get_btn(int type);

extern const struct ControlInfo vigilant_ctrls;
const char *vigilant_get_btn(int type);

extern const struct ControlInfo vimana_ctrls;
const char *vimana_get_btn(int type);

extern const struct ControlInfo vindictr_ctrls;
const char *vindictr_get_btn(int type);

extern const struct ControlInfo vindctr2_ctrls;
const char *vindctr2_get_btn(int type);

extern const struct ControlInfo viofight_ctrls;
const char *viofight_get_btn(int type);

extern const struct ControlInfo viper_ctrls;
const char *viper_get_btn(int type);

extern const struct ControlInfo vf_ctrls;
const char *vf_get_btn(int type);

extern const struct ControlInfo vf2_ctrls;
const char *vf2_get_btn(int type);

extern const struct ControlInfo vsgongf_ctrls;
const char *vsgongf_get_btn(int type);

extern const struct ControlInfo rbibb_ctrls;
const char *rbibb_get_btn(int type);

extern const struct ControlInfo balonfgt_ctrls;
const char *balonfgt_get_btn(int type);

extern const struct ControlInfo vsbball_ctrls;
const char *vsbball_get_btn(int type);

extern const struct ControlInfo btlecity_ctrls;
const char *btlecity_get_btn(int type);

extern const struct ControlInfo cstlevna_ctrls;
const char *cstlevna_get_btn(int type);

extern const struct ControlInfo cluclu_ctrls;
const char *cluclu_get_btn(int type);

extern const struct ControlInfo drmario_ctrls;
const char *drmario_get_btn(int type);

extern const struct ControlInfo duckhunt_ctrls;
const char *duckhunt_get_btn(int type);

extern const struct ControlInfo excitebk_ctrls;
const char *excitebk_get_btn(int type);

extern const struct ControlInfo vsfdf_ctrls;
const char *vsfdf_get_btn(int type);

extern const struct ControlInfo vsgradus_ctrls;
const char *vsgradus_get_btn(int type);

extern const struct ControlInfo vsgshoe_ctrls;
const char *vsgshoe_get_btn(int type);

extern const struct ControlInfo hogalley_ctrls;
const char *hogalley_get_btn(int type);

extern const struct ControlInfo hotsmash_ctrls;
const char *hotsmash_get_btn(int type);

extern const struct ControlInfo iceclimb_ctrls;
const char *iceclimb_get_btn(int type);

extern const struct ControlInfo iceclmrj_ctrls;
const char *iceclmrj_get_btn(int type);

extern const struct ControlInfo machridr_ctrls;
const char *machridr_get_btn(int type);

extern const struct ControlInfo vsmahjng_ctrls;
const char *vsmahjng_get_btn(int type);

extern const struct ControlInfo mightybj_ctrls;
const char *mightybj_get_btn(int type);

extern const struct ControlInfo jajamaru_ctrls;
const char *jajamaru_get_btn(int type);

extern const struct ControlInfo vspinbal_ctrls;
const char *vspinbal_get_btn(int type);

extern const struct ControlInfo platoon_ctrls;
const char *platoon_get_btn(int type);

extern const struct ControlInfo bnglngby_ctrls;
const char *bnglngby_get_btn(int type);

extern const struct ControlInfo vsslalom_ctrls;
const char *vsslalom_get_btn(int type);

extern const struct ControlInfo vssoccer_ctrls;
const char *vssoccer_get_btn(int type);

extern const struct ControlInfo starlstr_ctrls;
const char *starlstr_get_btn(int type);

extern const struct ControlInfo smgolf_ctrls;
const char *smgolf_get_btn(int type);

extern const struct ControlInfo suprmrio_ctrls;
const char *suprmrio_get_btn(int type);

extern const struct ControlInfo vsskykid_ctrls;
const char *vsskykid_get_btn(int type);

extern const struct ControlInfo supxevs_ctrls;
const char *supxevs_get_btn(int type);

extern const struct ControlInfo tkoboxng_ctrls;
const char *tkoboxng_get_btn(int type);

extern const struct ControlInfo vstennis_ctrls;
const char *vstennis_get_btn(int type);

extern const struct ControlInfo vstetris_ctrls;
const char *vstetris_get_btn(int type);

extern const struct ControlInfo goonies_ctrls;
const char *goonies_get_btn(int type);

extern const struct ControlInfo topgun_ctrls;
const char *topgun_get_btn(int type);

extern const struct ControlInfo wrecking_ctrls;
const char *wrecking_get_btn(int type);

extern const struct ControlInfo wacko_ctrls;
const char *wacko_get_btn(int type);

extern const struct ControlInfo mj4simai_ctrls;
const char *mj4simai_get_btn(int type);

extern const struct ControlInfo wargods_ctrls;
const char *wargods_get_btn(int type);

extern const struct ControlInfo wotw_ctrls;
const char *wotw_get_btn(int type);

extern const struct ControlInfo warlords_ctrls;
const char *warlords_get_btn(int type);

extern const struct ControlInfo warpwarp_ctrls;
const char *warpwarp_get_btn(int type);

extern const struct ControlInfo warrior_ctrls;
const char *warrior_get_btn(int type);

extern const struct ControlInfo suzume_ctrls;
const char *suzume_get_btn(int type);

extern const struct ControlInfo wecleman_ctrls;
const char *wecleman_get_btn(int type);

extern const struct ControlInfo wfortune_ctrls;
const char *wfortune_get_btn(int type);

extern const struct ControlInfo whodunit_ctrls;
const char *whodunit_get_btn(int type);

extern const struct ControlInfo wildfang_ctrls;
const char *wildfang_get_btn(int type);

extern const struct ControlInfo moo_ctrls;
const char *moo_get_btn(int type);

extern const struct ControlInfo willow_ctrls;
const char *willow_get_btn(int type);

extern const struct ControlInfo wizdfire_ctrls;
const char *wizdfire_get_btn(int type);

extern const struct ControlInfo wow_ctrls;
const char *wow_get_btn(int type);

extern const struct ControlInfo wolfpack_ctrls;
const char *wolfpack_get_btn(int type);

extern const struct ControlInfo wboy_ctrls;
const char *wboy_get_btn(int type);

extern const struct ControlInfo wbml_ctrls;
const char *wbml_get_btn(int type);

extern const struct ControlInfo wbeachvl_ctrls;
const char *wbeachvl_get_btn(int type);

extern const struct ControlInfo wcbowl_ctrls;
const char *wcbowl_get_btn(int type);

extern const struct ControlInfo wcbowldx_ctrls;
const char *wcbowldx_get_btn(int type);

extern const struct ControlInfo wseries_ctrls;
const char *wseries_get_btn(int type);

extern const struct ControlInfo wsf_ctrls;
const char *wsf_get_btn(int type);

extern const struct ControlInfo wtennis_ctrls;
const char *wtennis_get_btn(int type);

extern const struct ControlInfo wwfsstar_ctrls;
const char *wwfsstar_get_btn(int type);

extern const struct ControlInfo wwfwfest_ctrls;
const char *wwfwfest_get_btn(int type);

extern const struct ControlInfo wwfmania_ctrls;
const char *wwfmania_get_btn(int type);

extern const struct ControlInfo xmen_ctrls;
const char *xmen_get_btn(int type);

extern const struct ControlInfo xmvsf_ctrls;
const char *xmvsf_get_btn(int type);

extern const struct ControlInfo xmcota_ctrls;
const char *xmcota_get_btn(int type);

extern const struct ControlInfo xsleena_ctrls;
const char *xsleena_get_btn(int type);

extern const struct ControlInfo xenophob_ctrls;
const char *xenophob_get_btn(int type);

extern const struct ControlInfo xevious_ctrls;
const char *xevious_get_btn(int type);

extern const struct ControlInfo xybots_ctrls;
const char *xybots_get_btn(int type);

extern const struct ControlInfo yesnoj_ctrls;
const char *yesnoj_get_btn(int type);

extern const struct ControlInfo yiear_ctrls;
const char *yiear_get_btn(int type);

extern const struct ControlInfo yosakdon_ctrls;
const char *yosakdon_get_btn(int type);

extern const struct ControlInfo yuyugogo_ctrls;
const char *yuyugogo_get_btn(int type);

extern const struct ControlInfo zaxxon_ctrls;
const char *zaxxon_get_btn(int type);

extern const struct ControlInfo zerohour_ctrls;
const char *zerohour_get_btn(int type);

extern const struct ControlInfo zeropnt_ctrls;
const char *zeropnt_get_btn(int type);

extern const struct ControlInfo zeropnt2_ctrls;
const char *zeropnt2_get_btn(int type);

extern const struct ControlInfo zerowing_ctrls;
const char *zerowing_get_btn(int type);

extern const struct ControlInfo zerozone_ctrls;
const char *zerozone_get_btn(int type);

extern const struct ControlInfo zigzag_ctrls;
const char *zigzag_get_btn(int type);

extern const struct ControlInfo zingzip_ctrls;
const char *zingzip_get_btn(int type);

extern const struct ControlInfo zoar_ctrls;
const char *zoar_get_btn(int type);

extern const struct ControlInfo zodiack_ctrls;
const char *zodiack_get_btn(int type);

extern const struct ControlInfo zombraid_ctrls;
const char *zombraid_get_btn(int type);

extern const struct ControlInfo zookeep_ctrls;
const char *zookeep_get_btn(int type);

extern const struct ControlInfo zunkyou_ctrls;
const char *zunkyou_get_btn(int type);

extern const struct ControlInfo zwackery_ctrls;
const char *zwackery_get_btn(int type);

extern const struct ControlInfo zzyzzyxx_ctrls;
const char *zzyzzyxx_get_btn(int type);

#endif /* CONTROLS_H */